import type { AssessmentQuestion } from "@/types/assessment";

/** Introductory career-topic checks; these are study evidence, not independent job certification. */
export const ADJACENT_CAREER_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "adjacent-foundation-1",
    phaseId: "1",
    moduleId: "1-6",
    type: "multiple-choice",
    question: "A CSV station field contains a quoted comma. How should it be read?",
    options: [
      "Use a CSV parser, then validate the declared columns and values",
      "Split every line on commas",
      "Remove every quote before parsing",
      "Treat each comma as a new record",
    ],
    correct: 0,
    explanation:
      "Quoting changes delimiter interpretation; parsing and schema validation are separate steps.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "1/1-6/47",
  },
  {
    id: "adjacent-foundation-2",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "An ETL batch commits but its acknowledgement is lost. Which retry preserves the fixture’s two-row result?",
    options: [
      "Retry the same stable source IDs and reconcile the destination",
      "Create new IDs for the retry",
      "Advance the watermark before any durable write",
      "Ignore whether the load committed",
    ],
    correct: 0,
    explanation:
      "Stable uniqueness and an explicit upsert policy make repeated loading idempotent for this mutable-state fixture.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/10",
  },
  {
    id: "adjacent-foundation-3",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question:
      "Required telemetry disappears during a bounded failure experiment. What should the reviewed plan do?",
    options: [
      "Abort and restore because impact can no longer be observed",
      "Assume the experiment passed",
      "Continue until production fails",
      "Discard the missing interval from the report",
    ],
    correct: 0,
    explanation:
      "Loss of required observation is an explicit abort condition, not positive resilience evidence.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/10",
  },
  {
    id: "adjacent-foundation-4",
    phaseId: "7",
    moduleId: "7-4",
    type: "multiple-choice",
    question:
      "For60 seconds a service receives300 requests/s and completes250/s. What backlog growth follows under those counting assumptions?",
    options: [
      "3000 requests",
      "50 requests",
      "0 because completed requests were fast",
      "18000 requests",
    ],
    correct: 0,
    explanation: "The deficit is50 requests/s for60 seconds, giving3000 outstanding requests.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "7/7-4/07",
  },
  {
    id: "adjacent-foundation-5",
    phaseId: "8",
    moduleId: "8-1",
    type: "multiple-choice",
    question:
      "A test report says Saved appeared after storage failure, then reload lost the task. Which addition makes the report reproducible?",
    options: [
      "Build, fixture state, exact steps, expected outcome and sanitized evidence",
      "A guess about the developer’s competence",
      "Only a severity label",
      "A claim that all persistence code is defective",
    ],
    correct: 0,
    explanation:
      "A reproducible report separates observed behavior and conditions from unsupported root-cause claims.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-1/08",
  },
  {
    id: "adjacent-foundation-6",
    phaseId: "8",
    moduleId: "8-4",
    type: "multiple-choice",
    question:
      "A search endpoint returns fields from another tenant. What evidence should verify its repair?",
    options: [
      "A cross-tenant negative test plus a valid authorized search",
      "Only a successful same-tenant request",
      "Only a renamed route",
      "A client-side hidden button",
    ],
    correct: 0,
    explanation:
      "Authorization must be enforced at the resource boundary and tested against unauthorized as well as valid requests.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-4/07",
  },
  {
    id: "adjacent-foundation-7",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "An installed PWA has no cached copy of a requested lesson. What is an honest offline response?",
    options: [
      "Show unavailable content and preserve the learner’s current work",
      "Claim every lesson is downloaded",
      "Treat installation as proof of a cache hit",
      "Delete saved work to hide the failure",
    ],
    correct: 0,
    explanation:
      "Installability does not establish content availability; offline behavior needs explicit missing-content handling.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/11",
  },
  {
    id: "adjacent-foundation-8",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "An update reaches a PWA while an old tab is editing a draft. What must the migration contract protect?",
    options: [
      "Durable drafts and compatibility across old and new versions",
      "Only the app icon",
      "A forced reload before saving",
      "Unconditional deletion of all databases",
    ],
    correct: 0,
    explanation:
      "Worker activation and storage compatibility are separate concerns; draft durability must survive the transition.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/12",
  },
  {
    id: "adjacent-data-1",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "An order has two lines and one shipping charge of300 minor units. Why is copying300 onto each line unsafe for a sum?",
    options: [
      "It changes the grain and doubles the charge unless a reconciled allocation is defined",
      "It always improves accuracy",
      "SQL automatically knows which value is duplicated",
      "Dimensions cannot affect aggregation",
    ],
    correct: 0,
    explanation:
      "Facts must respect their declared grain; order-grain amounts cannot simply be repeated on line-grain records.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/11",
  },
  {
    id: "adjacent-data-2",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "A weekly category report does not need customer email. Which governance decision is justified?",
    options: [
      "Omit email from the report dataset unless a reviewed purpose requires it",
      "Copy every available field by default",
      "Treat a policy document as proof of access enforcement",
      "Choose a universal retention period for every jurisdiction",
    ],
    correct: 0,
    explanation:
      "Purpose-based minimization and accountable review are part of the data contract; legal and organizational retention requirements vary.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/12",
  },
  {
    id: "adjacent-data-3",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "An Airflow validation task repeatedly sees the same malformed data. What should the workflow do?",
    options: [
      "Fail validation and prevent success-dependent publication rather than retry indefinitely",
      "Treat three retries as data repair",
      "Publish downstream results regardless",
      "Call DAG parsing proof of scheduler execution",
    ],
    correct: 0,
    explanation:
      "Deterministic invalid data needs correction or quarantine, while retries are appropriate only under a justified failure policy.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/13",
  },
  {
    id: "adjacent-data-4",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "A Spark query groups a large table into two totals. Why can collect be acceptable for the totals but risky for the raw table?",
    options: [
      "collect transfers the result to driver memory, so output size matters",
      "collect always remains distributed",
      "Two rows prove the entire input fits in memory",
      "Spark automatically guarantees unlimited driver memory",
    ],
    correct: 0,
    explanation:
      "Actions materialize work; collecting an unbounded output can exhaust the driver even when transformations run across partitions.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/14",
  },
  {
    id: "adjacent-security-architecture-1",
    phaseId: "8",
    moduleId: "8-4",
    type: "multiple-choice",
    question: "A copied log matches its recorded SHA-256 digest. What does this establish?",
    options: [
      "Byte identity relative to that digest, not original truth or clock accuracy",
      "The event definitely happened as logged",
      "The user identity is legally proven",
      "The source clock was exact",
    ],
    correct: 0,
    explanation:
      "Integrity comparison has a bounded meaning; acquisition context and independent evidence remain important.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-4/08",
  },
  {
    id: "adjacent-security-architecture-2",
    phaseId: "8",
    moduleId: "8-4",
    type: "multiple-choice",
    question:
      "A local authorization fix denies alice access to bob’s document. Which additional test is essential?",
    options: [
      "Alice can still access her own document",
      "Every user is denied every resource",
      "The identifier looks random",
      "The UI hides the document link",
    ],
    correct: 0,
    explanation:
      "A mitigation must preserve legitimate access while blocking the unauthorized case.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-4/09",
  },
  {
    id: "adjacent-security-architecture-3",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question:
      "A workload has valid mTLS credentials. What remains necessary before returning another tenant’s data?",
    options: [
      "Application resource/tenant authorization as well as service policy",
      "No further permission check",
      "Only a longer certificate lifetime",
      "A retry on every denial",
    ],
    correct: 0,
    explanation: "Transport identity does not establish permission for every application resource.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/11",
  },
  {
    id: "adjacent-security-architecture-4",
    phaseId: "8",
    moduleId: "8-3",
    type: "multiple-choice",
    question:
      "The target accepted writes101–105 after cutover, while the source stops at100. What must rollback preserve?",
    options: [
      "Reconcile those acknowledged writes before reopening the source",
      "Only reverse DNS",
      "Only confirm the source process is healthy",
      "Discard target writes because the old system is familiar",
    ],
    correct: 0,
    explanation:
      "Rollback is a data-authority transition; routing reversal alone can lose acknowledged work.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-3/08",
  },
  {
    id: "adjacent-security-architecture-5",
    phaseId: "8",
    moduleId: "8-3",
    type: "multiple-choice",
    question:
      "A two-provider design shares one identity service. Which resilience claim is unsupported without further evidence?",
    options: [
      "It automatically survives an outage of that shared identity service",
      "It uses two providers",
      "It has an identity dependency",
      "It needs operational testing",
    ],
    correct: 0,
    explanation:
      "Shared dependencies can defeat the intended independence; provider count alone does not establish continuity.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-3/09",
  },
  {
    id: "adjacent-mobile-1",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "A mutation was applied remotely but its acknowledgement was lost. Which recovery preserves idempotency?",
    options: [
      "Retry the same owner-bound mutation identity and original payload",
      "Generate a fresh ID for each retry",
      "Discard the local draft immediately",
      "Treat local saving as remote acknowledgement",
    ],
    correct: 0,
    explanation:
      "Stable identity, payload binding and durable receipts are necessary for safe duplicate handling.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/14",
  },
  {
    id: "adjacent-mobile-2",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "A user revokes camera permission outside the app. What should the capture flow do on return?",
    options: [
      "Recheck current permission and preserve the manual-entry draft",
      "Trust yesterday’s cached permission forever",
      "Delete the form data",
      "Repeatedly prompt until permission is granted",
    ],
    correct: 0,
    explanation:
      "Native permission state can change independently; optional capability failure must not erase useful work.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/15",
  },
  {
    id: "adjacent-mobile-3",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question: "A push provider accepts an event. Which stronger claim is not yet justified?",
    options: [
      "The user read the message",
      "The provider accepted the submission",
      "A delivery attempt may follow",
      "Further receipts may contain errors",
    ],
    correct: 0,
    explanation: "Provider acceptance is distinct from presentation and user action.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/16",
  },
  {
    id: "adjacent-mobile-4",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "Build43 changes permission configuration after build42 was tested. What release evidence is needed?",
    options: [
      "Targeted verification tied to build43’s exact artifact and configuration",
      "Only build42’s old test report",
      "Only a successful upload",
      "A claim that all builds of one version behave identically",
    ],
    correct: 0,
    explanation:
      "Test evidence must match the changed artifact; upload, approval and availability are separate statuses.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/17",
  },
  {
    id: "adjacent-mobile-5",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question: "An RTL page contains the identifier ABC-123. What preserves its meaning?",
    options: [
      "Keep its characters and isolate its direction where needed",
      "Reverse its characters manually",
      "Assume lang alone defines every layout rule",
      "Mirror every icon and image automatically",
    ],
    correct: 0,
    explanation:
      "Semantic direction and isolation handle mixed content without corrupting identifiers.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-2/14",
  },
  {
    id: "adjacent-mobile-6",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "Initial transferred resources fall from1000KB to300KB. At idealized1Mb/s, what is the payload-only lower bound for300KB?",
    options: [
      "2.4 seconds, excluding latency and processing",
      "0.3 seconds as a guaranteed page-load time",
      "24 seconds regardless of network",
      "Exactly the page’s full interaction-ready time",
    ],
    correct: 0,
    explanation:
      "300000 bytes times8 divided by1000000 bits/s is2.4 seconds; actual readiness includes additional costs.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/09",
  },
  {
    id: "adjacent-mobile-7",
    phaseId: "2",
    moduleId: "2-1",
    type: "multiple-choice",
    question:
      "A JavaScript search enhancement fails to load. What should progressive enhancement preserve?",
    options: [
      "The labeled HTML form’s normal submission to a real host endpoint",
      "A permanent spinner",
      "Only an empty framework shell",
      "A false claim that a static file implements its backend",
    ],
    correct: 0,
    explanation:
      "A meaningful baseline remains usable; the host must actually implement and validate the endpoint.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-1/12",
  },
  {
    id: "adjacent-mobile-8",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "At60Hz, a fixture has frame durations12,14,35,13,40ms. How many exceed the approximate display interval?",
    options: ["Two", "None", "All five", "One"],
    correct: 0,
    explanation:
      "The interval is about16.7ms, so35 and40 exceed it; interpretation changes with refresh rate and measurement method.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/10",
  },
  {
    id: "adjacent-financial-1",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question: "A journal balances debits and credits. What still needs verification?",
    options: [
      "Correct accounts, business identity and external reconciliation",
      "Nothing; balance proves every business fact",
      "Only that the total is positive",
      "Whether credits always decrease every account",
    ],
    correct: 0,
    explanation:
      "Structural balance is necessary but does not establish correct classification or unique business events.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/01",
  },
  {
    id: "adjacent-financial-2",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question: "A posted transaction needs reversal. What preserves history?",
    options: [
      "A new linked reversing entry while retaining the original",
      "Delete the original entry",
      "Overwrite its amount with zero",
      "Reuse its ID with different lines",
    ],
    correct: 0,
    explanation:
      "An auditable correction preserves the original event and records its reversal separately.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/01",
  },
  {
    id: "adjacent-financial-3",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question: "A valid webhook is delivered twice. What prevents a repeated business effect?",
    options: [
      "Durable event/business idempotency and reconciliation",
      "A new local ID for every delivery",
      "Trusting arrival order",
      "Returning success before durable acceptance",
    ],
    correct: 0,
    explanation:
      "Signature validity does not establish unique delivery; duplicate-safe effects require durable identity controls.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/02",
  },
  {
    id: "adjacent-financial-4",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question: "A delayed processing event arrives after success. What is justified?",
    options: [
      "Reconcile current authoritative state instead of blindly downgrading",
      "Always use the last-arriving payload",
      "Erase the success record",
      "Treat delayed delivery as a new charge",
    ],
    correct: 0,
    explanation: "Delivery order and business chronology are distinct.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/02",
  },
  {
    id: "adjacent-financial-5",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A payment instruction is accepted but settlement evidence is absent. Which label is justified?",
    options: [
      "Accepted or pending settlement under the rail contract",
      "Irrevocably settled for every rail",
      "Returned",
      "Reconciled to all external statements",
    ],
    correct: 0,
    explanation:
      "Acceptance has a rail-specific meaning and is not a universal settlement guarantee.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/03",
  },
  {
    id: "adjacent-financial-6",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "For a currency explicitly using two decimal places,1000 minor units are represented as what decimal amount?",
    options: ["10.00", "1000.00", "1.000", "The same conversion for every currency"],
    correct: 0,
    explanation:
      "Conversion depends on the declared currency exponent; this fixture uses two decimal places.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/04",
  },
  {
    id: "adjacent-financial-7",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question: "A fraud rule flags80 fraudulent and198 legitimate transactions. What is precision?",
    options: ["80/278, about28.8%", "80%", "2%", "100%"],
    correct: 0,
    explanation:
      "Precision is true positives divided by all flagged cases; recall and false-positive rate answer different questions.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/05",
  },
  {
    id: "adjacent-financial-8",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A document upload has a name mismatch under a review-required policy. What status is supported?",
    options: [
      "Review required with the evidence recorded",
      "Automatically verified",
      "Proven fraud",
      "Approved because upload succeeded",
    ],
    correct: 0,
    explanation: "Collection, verification and accountable decision are separate stages.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/06",
  },
  {
    id: "adjacent-financial-9",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A profile control declares three transactions but contains two. What should validation do?",
    options: [
      "Reject or quarantine the business-rule mismatch",
      "Invent a third transaction",
      "Accept because XML parsed",
      "Assume settlement is complete",
    ],
    correct: 0,
    explanation: "Structural parsing does not satisfy business/profile controls.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/07",
  },
  {
    id: "adjacent-financial-10",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "An ISO20022 integration names a message family but no version or community profile. What is missing?",
    options: [
      "The exact definition/version and applicable usage constraints",
      "Only the font used in the XML editor",
      "A guarantee that every receiver accepts every version",
      "Proof of settlement",
    ],
    correct: 0,
    explanation:
      "Interoperability requires the receiver’s adopted message/profile contract, not a family label alone.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/07",
  },
  {
    id: "adjacent-financial-11",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "In the ordinary merchant fixture, does encryption permit retaining card verification codes after authorization?",
    options: [
      "No",
      "Yes, indefinitely",
      "Yes, if copied to analytics",
      "Yes, if the provider is compliant",
    ],
    correct: 0,
    explanation:
      "Encryption does not remove the sensitive-authentication-data retention prohibition in this merchant context.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/08",
  },
  {
    id: "adjacent-financial-12",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A report includes settled1000 and500, excludes pending700, then corrects500 to400. What are the initial and corrected totals?",
    options: ["1500 and1400", "2200 and2100", "1500 and2200", "700 and400"],
    correct: 0,
    explanation:
      "The supplied rule excludes pending records and preserves the corrected report’s lineage.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/09",
  },
  {
    id: "adjacent-platform-security-1",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question:
      "Desired revisionR1 declares three replicas; a manual edit makes two. Why can a GitOps controller restore three?",
    options: [
      "It reconciles toward the unchanged desired state",
      "Manual edits always replace the source declaration",
      "A commit proves workloads are healthy",
      "Repository unavailability means a new revision was applied",
    ],
    correct: 0,
    explanation:
      "The declared source and reconciliation policy remain authoritative until changed or explicitly suspended.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/12",
  },
  {
    id: "adjacent-platform-security-2",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question:
      "A Pod Security warning appears and a NetworkPolicy object exists. What still needs verification?",
    options: [
      "Actual admission enforcement and supported network-policy behavior",
      "Nothing; both boundaries are proven",
      "Only the pod name",
      "That all credentials are inaccessible to non-root processes",
    ],
    correct: 0,
    explanation:
      "Warnings and configuration objects do not by themselves establish enforced denial.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/13",
  },
  {
    id: "adjacent-platform-security-3",
    phaseId: "8",
    moduleId: "8-4",
    type: "multiple-choice",
    question:
      "A CPython disassembly changes opcode offsets after an interpreter upgrade. What is the sound comparison?",
    options: [
      "Compare documented behavior and record interpreter versions instead of assuming stable bytecode",
      "Assume the program is malicious",
      "Treat offsets as a permanent API",
      "Execute arbitrary unknown artifacts to guess",
    ],
    correct: 0,
    explanation:
      "CPython bytecode is an implementation detail; behavioral hypotheses need controlled tests.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-4/10",
  },
  {
    id: "adjacent-platform-security-4",
    phaseId: "8",
    moduleId: "8-4",
    type: "multiple-choice",
    question:
      "A scoped local demo links to a third-party service. Does the link authorize testing that service?",
    options: [
      "No; explicit scope governs authorization",
      "Yes, every linked service is included",
      "Yes, if a bounty might be paid",
      "Yes, if the service is reachable",
    ],
    correct: 0,
    explanation: "Reachability and linkage do not expand written testing permission.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-4/11",
  },
  {
    id: "adjacent-platform-security-5",
    phaseId: "9",
    moduleId: "9-2",
    type: "multiple-choice",
    question:
      "Does encryption at rest prevent an attacker with an authorized database session from reading decrypted records?",
    options: [
      "Not by itself; identity, authorization and key/session boundaries still matter",
      "Always",
      "Only if the table is large",
      "It replaces all authorization checks",
    ],
    correct: 0,
    explanation:
      "At-rest encryption protects particular storage threats, not every path through an authorized application or database session.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-2/08",
  },
  {
    id: "adjacent-data-distributed-1",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question: "Two owners request the same private progress URL. Which cache design is unsafe?",
    options: [
      "A shared URL-only cache that can return the first owner’s response",
      "Excluding owner-specific responses from shared caching",
      "Testing cross-owner isolation",
      "Versioning public lesson assets",
    ],
    correct: 0,
    explanation:
      "A shared URL does not identify the authorized owner; cache behavior must preserve access boundaries.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/14",
  },
  {
    id: "adjacent-data-distributed-2",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "A unique event at time 160 arrives for the half-open window [100,160). What is correct?",
    options: [
      "Exclude it from this window and apply the next window’s policy",
      "Include it because it arrived quickly",
      "Count it twice at the boundary",
      "Treat event time as arrival time",
    ],
    correct: 0,
    explanation: "The inclusive lower and exclusive upper bounds make the boundary unambiguous.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/15",
  },
  {
    id: "adjacent-data-distributed-3",
    phaseId: "4",
    moduleId: "4-3",
    type: "multiple-choice",
    question:
      "One of two files is visible before the snapshot manifest commits. Can it be read as the complete published snapshot?",
    options: [
      "No; visible files do not establish a committed complete snapshot",
      "Yes; any upload proves completeness",
      "Yes; folder names enforce transactions",
      "Only the file extension matters",
    ],
    correct: 0,
    explanation: "Readers need the selected publication protocol’s committed snapshot evidence.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-3/16",
  },
  {
    id: "adjacent-data-distributed-4",
    phaseId: "7",
    moduleId: "7-2",
    type: "multiple-choice",
    question: "A grow-only counter merges A:2 and B:3, then merges B:3 again. What total follows?",
    options: ["5", "8", "3", "2"],
    correct: 0,
    explanation:
      "Componentwise maximum preserves the already known B component; duplicate state is not another increment.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "7/7-2/09",
  },
  {
    id: "adjacent-data-distributed-5",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "A browser cannot expose a resource’s transfer measurement. What should analytics do?",
    options: [
      "Preserve unknown or omit the measurement rather than report zero",
      "Report zero bytes",
      "Copy private page contents to infer the size",
      "Ignore the collection consent decision",
    ],
    correct: 0,
    explanation:
      "Unavailable timing is not a zero-byte transfer; measurement and collection boundaries both matter.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/11",
  },
  {
    id: "adjacent-financial-advanced-1",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A synthetic 100 USD converts at 0.90 EUR/USD with a 2 EUR destination fee. What expected net credit should be reconciled?",
    options: ["88 EUR", "90 USD", "98 EUR", "190 units"],
    correct: 0,
    explanation:
      "The stated conversion yields 90 EUR; the separately stated fee leaves 88 EUR. These are invented terms.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/10",
  },
  {
    id: "adjacent-financial-advanced-2",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "An account has 100 now, owes 120 at noon and expects 80 at 15:00. What does a projected closing balance of 60 miss?",
    options: [
      "A 20-unit noon liquidity shortfall",
      "Nothing; closing cash guarantees noon settlement",
      "An automatic right to an overdraft",
      "That all currencies are interchangeable",
    ],
    correct: 0,
    explanation:
      "Timing and usable funds matter; the future expected receipt is not available at noon.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/11",
  },
  {
    id: "adjacent-financial-advanced-3",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "An account-information connection is revoked but its token has not expired. What should a queued import do?",
    options: [
      "Recheck current authorization and stop collection under the revocation policy",
      "Proceed because tokens override consent",
      "Treat all retained records as automatically erased",
      "Log the token for troubleshooting",
    ],
    correct: 0,
    explanation: "Credential possession is not equivalent to current authorized collection.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/12",
  },
  {
    id: "adjacent-financial-advanced-4",
    phaseId: "4",
    moduleId: "4-7",
    type: "multiple-choice",
    question:
      "A versioned reporting control passes its duplicate and currency tests. What has it not established?",
    options: [
      "That its reporting rule and population are legally applicable",
      "That the selected fixtures meet the programmed checks",
      "That duplicate IDs are rejected in the supplied tests",
      "That the fixture sums its settled records",
    ],
    correct: 0,
    explanation:
      "Automation implements declared rules; obligation selection and substantive approval still require evidence.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-7/09",
  },
  {
    id: "adjacent-mobile-quality-1",
    phaseId: "8",
    moduleId: "8-1",
    type: "multiple-choice",
    question:
      "A visual baseline update hides a removed Save button. What is the sound review decision?",
    options: [
      "Reject it against the required task and functional checks",
      "Accept because the new screenshot passes",
      "Mask the entire form",
      "Treat emulation as proof on every device",
    ],
    correct: 0,
    explanation:
      "A baseline records intended visual behavior; it cannot redefine away a required action.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "8/8-1/09",
  },
  {
    id: "adjacent-mobile-quality-2",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question: "A validated deep link identifies record 42. What must still occur?",
    options: [
      "Normal resource authorization for the current account",
      "Automatic access to record 42",
      "Trusting an owner query parameter",
      "Executing the link as code",
    ],
    correct: 0,
    explanation: "A route identifies a destination, not permission to access it.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/18",
  },
  {
    id: "adjacent-mobile-quality-3",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question: "A React Native counter uses only component state. What does remounting do?",
    options: [
      "Resets it; persistence needs a separate tested contract",
      "Proves the count was saved",
      "Guarantees identical screen-reader behavior",
      "Writes it to the operating system automatically",
    ],
    correct: 0,
    explanation: "Local state and durable native storage are different mechanisms.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/19",
  },
  {
    id: "adjacent-mobile-quality-4",
    phaseId: "9",
    moduleId: "9-5",
    type: "multiple-choice",
    question:
      "A separate service charges 40, costs 25 per customer and has 300 fixed overhead. How many customers cover that overhead under these limited assumptions?",
    options: ["20", "12", "8", "300"],
    correct: 0,
    explanation: "Contribution is 15, and 300 divided by 15 is 20; omitted costs still matter.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-5/09",
  },
  {
    id: "adjacent-mobile-quality-5",
    phaseId: "9",
    moduleId: "9-4",
    type: "multiple-choice",
    question:
      "Three qualitative observations reveal confusing upload status and shared-device privacy concerns. What follows?",
    options: [
      "Test those specific hypotheses with relevant users without claiming population prevalence",
      "Every user in the region has the same needs",
      "The design has proven causal efficacy",
      "Recruit only colleagues with fast Wi-Fi",
    ],
    correct: 0,
    explanation:
      "Small qualitative evidence can expose issues; it does not establish universal preferences or causal improvement.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-4/08",
  },
];
