import type { AssessmentQuestion } from "@/types/assessment";

/** Applied scenarios for previously undersized core assessment pools. */
export const CORE_EXPANSION_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "core-expansion-1-7-1",
    phaseId: "1",
    moduleId: "1-7",
    type: "multiple-choice",
    question: "A subclass rejects inputs that its base class accepts. What contract is at risk?",
    options: [
      "Substitutability: callers of the base contract cannot safely use the subclass",
      "Encapsulation always forbids subclasses",
      "The subclass must expose every private field",
      "The issue is only method naming",
    ],
    correct: 0,
    explanation:
      "A subtype must preserve the behavioral promises clients rely on, not merely share method names.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-2-7-1",
    phaseId: "2",
    moduleId: "2-7",
    type: "multiple-choice",
    question:
      "After reconnecting, a client receives event42 twice. What prevents duplicate application?",
    options: [
      "Track stable event IDs and apply each once",
      "Assume reconnect preserves exactly-once delivery",
      "Discard all future events",
      "Use the socket connection ID as the event ID",
    ],
    correct: 0,
    explanation:
      "Reconnection and retries can repeat data. Stable event identity supports deduplication across connections.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-3-6-1",
    phaseId: "3",
    moduleId: "3-6",
    type: "multiple-choice",
    question: "A directed graph has edges A→B and B→C. Which added edge creates a cycle?",
    options: ["C→A", "A→C", "A→D", "D→C"],
    correct: 0,
    explanation: "C→A closes the directed path A→B→C→A.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-4-6-1",
    phaseId: "4",
    moduleId: "4-6",
    type: "multiple-choice",
    question:
      "A consumer updates a database then crashes before acknowledging a message. What must the handler tolerate?",
    options: [
      "The same message may be delivered again",
      "The broker must undo the database update",
      "The acknowledgment already succeeded",
      "The message cannot be retried",
    ],
    correct: 0,
    explanation:
      "The database commit and broker acknowledgment are separate actions; idempotent processing handles the redelivery window.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-4-6-2",
    phaseId: "4",
    moduleId: "4-6",
    type: "multiple-choice",
    question: "Why store an outbox row in the same transaction as a business update?",
    options: [
      "Avoid committing the update without a durable record of its event",
      "Guarantee every subscriber has already processed the event",
      "Make delivery globally ordered across all producers",
      "Remove the need to retry the publisher",
    ],
    correct: 0,
    explanation:
      "An atomic local transaction records both facts. A separate publisher still needs retry and duplicate handling.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-8-7-1",
    phaseId: "8",
    moduleId: "8-7",
    type: "multiple-choice",
    question:
      "During mitigation, a teammate proposes a speculative root cause as a confirmed customer update. What should the incident lead do?",
    options: [
      "Separate observed impact from hypotheses and publish the next update time",
      "Publish the hypothesis as fact to sound confident",
      "Stop customer communication until root cause is known",
      "Blame the last deployer",
    ],
    correct: 0,
    explanation:
      "Clear incident communication reports verified impact, current actions, uncertainty, and a predictable update cadence.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-4-1",
    phaseId: "9",
    moduleId: "9-4",
    type: "multiple-choice",
    question:
      "A feature has high adoption but no improvement in the target retention cohort. What should a product review examine?",
    options: [
      "Whether adoption is a proxy that fails to measure the intended outcome",
      "Only whether engineers delivered on time",
      "Whether the adoption number can replace retention",
      "Whether every customer received the announcement",
    ],
    correct: 0,
    explanation:
      "Shipping and usage are evidence, but outcome evaluation must use the goal and relevant cohort.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-4-2",
    phaseId: "9",
    moduleId: "9-4",
    type: "multiple-choice",
    question:
      "An experiment shows a tiny conversion gain but large support burden. What should govern rollout?",
    options: [
      "Predefined primary metrics and guardrails, including support cost",
      "Conversion alone, regardless of guardrails",
      "The highest daily conversion result",
      "The executive’s favorite variant",
    ],
    correct: 0,
    explanation:
      "A decision combines the intended benefit with predefined harm constraints and uncertainty.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-4-3",
    phaseId: "9",
    moduleId: "9-4",
    type: "multiple-choice",
    question: "Two customer segments need conflicting workflows. What is a useful next step?",
    options: [
      "State the target segment and test its highest-risk need",
      "Average all preferences into one assumed user",
      "Build both complete products immediately",
      "Choose the loudest customer permanently",
    ],
    correct: 0,
    explanation:
      "Explicit segmentation makes assumptions testable and avoids an incoherent feature bundle.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-4-4",
    phaseId: "9",
    moduleId: "9-4",
    type: "multiple-choice",
    question:
      "A roadmap date depends on an unvalidated integration. How should it be communicated?",
    options: [
      "Expose the dependency, uncertainty, and validation milestone",
      "Treat the estimate as a guaranteed commitment",
      "Remove the integration from risk tracking",
      "Add precision to the date without more evidence",
    ],
    correct: 0,
    explanation:
      "A roadmap communicates decisions and assumptions; validation should reduce material uncertainty before hard commitments.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-7-1",
    phaseId: "9",
    moduleId: "9-7",
    type: "multiple-choice",
    question:
      "Six teams need one shared platform change, but requirements differ. What should the platform group establish first?",
    options: [
      "A small shared contract, adoption criteria, and ownership with representative teams",
      "A mandatory rewrite before discovering needs",
      "A separate incompatible platform per team",
      "A platform success metric based only on lines of code",
    ],
    correct: 0,
    explanation:
      "A platform is useful when its interface solves actual team needs and has accountable ownership.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-7-2",
    phaseId: "9",
    moduleId: "9-7",
    type: "multiple-choice",
    question:
      "Hiring doubles while onboarding remains manual and error-prone. What is the most direct leverage point?",
    options: [
      "A tested onboarding path with owners, documentation, and feedback",
      "More meetings for every established engineer",
      "Lowering production access checks for new hires",
      "Measuring only offer acceptance",
    ],
    correct: 0,
    explanation:
      "Repeatable onboarding reduces recurring coordination burden while preserving appropriate access boundaries.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-7-3",
    phaseId: "9",
    moduleId: "9-7",
    type: "multiple-choice",
    question:
      "A scale-up moves to service ownership but incidents still cross unclear boundaries. What is missing?",
    options: [
      "Explicit ownership and escalation for dependencies as well as individual services",
      "More service names",
      "A rule that teams never communicate",
      "A single uptime metric without response ownership",
    ],
    correct: 0,
    explanation:
      "Service decomposition does not resolve operational accountability unless cross-service responsibilities are explicit.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-7-4",
    phaseId: "9",
    moduleId: "9-7",
    type: "multiple-choice",
    question:
      "A team is praised for utilization while delivery slows due to waiting dependencies. What should change?",
    options: [
      "Measure flow and blocked work across the delivery system",
      "Maximize every person’s queue length",
      "Treat waiting as productive utilization",
      "Add more simultaneous projects",
    ],
    correct: 0,
    explanation:
      "Busy individuals do not imply effective delivery; queueing and handoffs can dominate elapsed time.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-8-1",
    phaseId: "9",
    moduleId: "9-8",
    type: "multiple-choice",
    question: "A governance board approves an architectural exception. What makes it manageable?",
    options: [
      "An owner, rationale, risk boundary, expiry date, and review condition",
      "A permanent undocumented exemption",
      "An approval email with no affected system",
      "A blanket waiver for all teams",
    ],
    correct: 0,
    explanation:
      "Exceptions need accountable scope and reassessment rather than becoming invisible policy.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-8-2",
    phaseId: "9",
    moduleId: "9-8",
    type: "multiple-choice",
    question:
      "An enterprise migration cannot move all clients simultaneously. What must the plan address?",
    options: [
      "Compatibility, staged cutover, observability, and rollback across versions",
      "Only the final target diagram",
      "A date after which all old clients are assumed gone",
      "Disabling logs to reduce migration overhead",
    ],
    correct: 0,
    explanation:
      "Migration risk occurs during coexistence, so the plan must describe intermediate states and recovery.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-8-3",
    phaseId: "9",
    moduleId: "9-8",
    type: "multiple-choice",
    question: "A vendor reports a security certification. What else should due diligence examine?",
    options: [
      "The certification scope and the actual service, contract, and shared responsibilities",
      "Nothing: any certificate covers every product",
      "Only the vendor’s logo",
      "Whether competitors use the vendor",
    ],
    correct: 0,
    explanation:
      "A scoped assurance report is one input; it does not transfer all customer responsibilities or cover every service.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-8-4",
    phaseId: "9",
    moduleId: "9-8",
    type: "multiple-choice",
    question:
      "Business units each report incompatible availability metrics. What is the first governance repair?",
    options: [
      "Agree definitions, observation windows, exclusions, and ownership",
      "Average the percentages without normalization",
      "Select the highest percentage",
      "Remove all metrics",
    ],
    correct: 0,
    explanation: "Comparable decisions require shared measurement definitions and traceable data.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-9-1",
    phaseId: "9",
    moduleId: "9-9",
    type: "multiple-choice",
    question:
      "A target company claims low technical debt but supplies no buildable repository. What evidence should diligence request?",
    options: [
      "A reproducible build, delivery history, and representative code and operational review",
      "Only a slide describing the architecture",
      "Only the number of developers",
      "Only a list of programming languages",
    ],
    correct: 0,
    explanation:
      "Diligence should validate operational and engineering claims using demonstrable artifacts.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-9-2",
    phaseId: "9",
    moduleId: "9-9",
    type: "multiple-choice",
    question:
      "A critical production service depends on one departing contractor. What should the report capture?",
    options: [
      "Key-person dependency, transfer evidence, ownership plan, and business exposure",
      "Only whether the contractor wrote good code",
      "A guarantee that documentation removes all risk",
      "An assumption that acquisition fixes staffing",
    ],
    correct: 0,
    explanation:
      "Continuity risk depends on retained knowledge, access, and realistic transfer and ownership arrangements.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-9-3",
    phaseId: "9",
    moduleId: "9-9",
    type: "multiple-choice",
    question:
      "An acquisition inventory includes code with unclear third-party licenses. What is appropriate?",
    options: [
      "Record provenance gaps and obtain qualified license review before asserting transfer rights",
      "Assume public source means unrestricted use",
      "Delete license headers to simplify transfer",
      "Treat purchase of the company as proof of every code right",
    ],
    correct: 0,
    explanation:
      "Technical diligence identifies evidence gaps; ownership and license conclusions require appropriate review.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "core-expansion-9-9-4",
    phaseId: "9",
    moduleId: "9-9",
    type: "multiple-choice",
    question:
      "A diligence finding may affect the transaction but its remediation estimate is uncertain. How should it be reported?",
    options: [
      "State evidence, impact range, assumptions, and validation work",
      "Hide it until the estimate is precise",
      "Present the optimistic estimate as certain",
      "List only the worst imaginable outcome",
    ],
    correct: 0,
    explanation:
      "Decision-makers need calibrated uncertainty and concrete evidence, not concealed or invented certainty.",
    difficulty: "medium",
    tags: ["applied-scenario"],
  },
  {
    id: "css-bridge-2-2-1",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "Layers are declared base, components, utilities. All declarations are normal author rules. Which matching layered declaration takes precedence?",
    options: [
      "The utilities declaration, before comparing specificity across those layers",
      "Always the selector with the most classes",
      "Always the first source declaration",
      "Whichever color is darker",
    ],
    correct: 0,
    explanation:
      "For normal declarations in the same origin, later layers outrank earlier layers before specificity.",
    difficulty: "medium",
    tags: ["css-architecture"],
    sourceLesson: "2/2-2/11",
  },
  {
    id: "css-bridge-2-2-2",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "A normal unlayered color rule overrides a component inside a named layer. What should a migration review examine?",
    options: [
      "Whether the legacy rule should deliberately belong to a layer",
      "Whether adding more component classes always solves it",
      "Whether all colors need important",
      "Whether HTML should be replaced",
    ],
    correct: 0,
    explanation:
      "Normal unlayered author styles outrank layered normal styles; stronger selectors inside the layer do not change that ordering.",
    difficulty: "medium",
    tags: ["css-architecture"],
    sourceLesson: "2/2-2/11",
  },
  {
    id: "css-bridge-2-2-3",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "A warning button must work in main and sidebar containers. Which rule best expresses its intended variation?",
    options: [".sidebar article button", ".action--warning", "body div div button", "#page button"],
    correct: 1,
    explanation:
      "A named component modifier expresses the intended variation without depending on where the component is placed.",
    difficulty: "medium",
    tags: ["css-architecture"],
    sourceLesson: "2/2-2/11",
  },
  {
    id: "css-bridge-2-2-4",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "A theme changes blue actions to green. Which token name keeps the component independent of the hue?",
    options: ["--blue-action-only", "--green-button", "--action-background", "--color-number-17"],
    correct: 2,
    explanation: "A semantic token names the role of a value rather than a particular hue.",
    difficulty: "medium",
    tags: ["design-systems"],
    sourceLesson: "2/2-2/12",
  },
  {
    id: "css-bridge-2-2-5",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "A disabled button contains the only explanation of why saving is unavailable. What is missing?",
    options: [
      "A reachable explanation outside the control",
      "A more saturated disabled color",
      "A click handler that ignores disabled",
      "A shorter token name",
    ],
    correct: 0,
    explanation:
      "Disabled controls are ordinarily skipped by keyboard tab navigation; their explanation must remain available elsewhere.",
    difficulty: "medium",
    tags: ["design-systems"],
    sourceLesson: "2/2-2/12",
  },
  {
    id: "css-bridge-2-2-6",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "The action background changes to pale yellow. What evidence is needed before retaining white text?",
    options: [
      "A screenshot of the previous theme",
      "Measured contrast for the actual state and background, plus affected-state checks",
      "A successful TypeScript build only",
      "A token name containing accessible",
    ],
    correct: 1,
    explanation:
      "Token reuse and compilation do not establish contrast or usable focus and disabled states.",
    difficulty: "medium",
    tags: ["design-systems"],
    sourceLesson: "2/2-2/12",
  },
  {
    id: "required-bridge-1",
    phaseId: "1",
    moduleId: "1-6",
    type: "multiple-choice",
    question:
      "A Python row has no rpm key. The declared contract requires an ASCII integer string. What should the filter do?",
    options: [
      "Reject the row as invalid",
      "Treat it as a measured zero",
      "Skip all remaining tests",
      "Convert None into an integer",
    ],
    correct: 0,
    explanation: "Missing input violates this contract; zero is a distinct valid reading.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "1/1-6/46",
  },
  {
    id: "required-bridge-2",
    phaseId: "1",
    moduleId: "1-6",
    type: "multiple-choice",
    question:
      "A Python function returns from inside its for-loop. Which test best exposes a premature return?",
    options: [
      "Two qualifying input rows expected in the result",
      "Only one qualifying row",
      "A comment spelling check",
      "Only the function name",
    ],
    correct: 0,
    explanation:
      "Multiple qualifying rows reveal whether processing stopped after the first iteration.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "1/1-6/46",
  },
  {
    id: "required-bridge-3",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "A bundle builds, but querySelector returns null at runtime. What evidence is missing?",
    options: [
      "A page element/timing contract for the loaded script",
      "Proof every import is misspelled",
      "A stronger minifier setting",
      "A private key in client code",
    ],
    correct: 0,
    explanation:
      "The build graph can resolve while the runtime DOM differs from what the entry module expects.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/07",
  },
  {
    id: "required-bridge-4",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "A secret is substituted into emitted browser JavaScript. Which statement is correct?",
    options: [
      "It becomes public to clients receiving that asset",
      "Production mode encrypts it automatically",
      "A private repository keeps the delivered bundle secret",
      "A loader guarantees secrecy",
    ],
    correct: 0,
    explanation: "Build-time substitution does not provide a server-side confidentiality boundary.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/07",
  },
  {
    id: "required-bridge-5",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question:
      "A remote feature times out while the host contains unsaved work. Which contract is appropriate?",
    options: [
      "Preserve host work and show a bounded unavailable panel",
      "Reload the entire page without warning",
      "Declare the remote compatible",
      "Silently retry forever",
    ],
    correct: 0,
    explanation:
      "The feature availability failure should remain within its explicit boundary and preserve unrelated work.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/08",
  },
  {
    id: "required-bridge-6",
    phaseId: "2",
    moduleId: "2-6",
    type: "multiple-choice",
    question: "Why does a mount function return cleanup?",
    options: [
      "To remove listeners and nodes when the host unmounts the feature",
      "To certify same-page remote code is isolated",
      "To avoid all version tests",
      "To authorize every API request",
    ],
    correct: 0,
    explanation:
      "Cleanup prevents leaked listeners and duplicated behavior across navigation; it is not a security sandbox.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-6/08",
  },
  {
    id: "required-bridge-7",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "A logger marks data unavailable when age is greater than200ms. What is expected at exactly200ms?",
    options: [
      "Not expired under this exact requirement",
      "Always expired under every standard",
      "The requirement has no boundary meaning",
      "A physical stop is certified",
    ],
    correct: 0,
    explanation:
      "The supplied greater-than contract differs from greater-than-or-equal; physical timing sufficiency is a separate argument.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/05",
  },
  {
    id: "required-bridge-8",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "A malformed row refreshes last_seen before validation. What evidence should expose the error?",
    options: [
      "A test that invalid input cannot refresh the last valid observation age",
      "A screenshot with a plausible number",
      "A larger timeout chosen without review",
      "Only a successful compilation",
    ],
    correct: 0,
    explanation:
      "Validation and timestamp assignment must preserve the assigned valid-data contract.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/05",
  },
  {
    id: "required-bridge-9",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "A medical-software display patch passes one screenshot check. What remains relevant?",
    options: [
      "Change impact across affected consumers and retained verification evidence",
      "Automatic whole-device release approval",
      "An invented clinical threshold",
      "Ignoring the CSV consumer",
    ],
    correct: 0,
    explanation:
      "A local observation does not close lifecycle impact or establish device validation/release.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/06",
  },
  {
    id: "required-bridge-10",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question: "What does the public IEC62304 scope explicitly exclude?",
    options: [
      "Validation and final release of the medical device as a whole",
      "All software maintenance",
      "All embedded software",
      "Every lifecycle activity",
    ],
    correct: 0,
    explanation:
      "The official scope covers software development/maintenance while distinguishing whole-device validation and final release.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/06",
  },
  {
    id: "required-bridge-11",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "An adapter passes0.2seconds to a function expecting milliseconds. Which test is needed?",
    options: [
      "An integration check converting0.2seconds to200ms",
      "Only a unit check already using200ms",
      "A declaration that every function is ASILD",
      "A renamed variable without checking units",
    ],
    correct: 0,
    explanation:
      "Correct unit behavior does not establish that the adapter supplies correctly normalized inputs.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/07",
  },
  {
    id: "required-bridge-12",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "A scheduler changes from10ms to80ms while comparison logic is unchanged. What should be reviewed?",
    options: [
      "The end-to-end observation/response timing assumptions",
      "Only code line count",
      "Whether a unit pass assigns ASIL",
      "Whether all old evidence automatically applies",
    ],
    correct: 0,
    explanation:
      "Scheduling changes can alter detection delay even when local logic still meets its comparison tests.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/07",
  },
  {
    id: "required-bridge-13",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "A new generated table and compiler options produce B2. Can B1 test evidence silently be relabeled B2?",
    options: [
      "No; identify the changes and justify reverification scope",
      "Yes if filenames match",
      "Yes if source comments are unchanged",
      "Yes if the image has a digest",
    ],
    correct: 0,
    explanation:
      "Evidence is tied to a baseline; changed build inputs need explicit impact review.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/08",
  },
  {
    id: "required-bridge-14",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question: "What does an artifact digest establish by itself?",
    options: [
      "Identity of bytes for comparison, not correctness or approval",
      "All requirements were verified",
      "FAA certification",
      "Complete code coverage",
    ],
    correct: 0,
    explanation: "Identity, verification and approval are different evidence claims.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/08",
  },
  {
    id: "required-bridge-15",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "At image time the aligned camera origin is0.4m ahead of base. A camera point is1m ahead. What is its base x coordinate?",
    options: ["1.4m", "0.6m", "1m with a renamed frame", "0m whenever uncertain"],
    correct: 0,
    explanation:
      "For the supplied aligned-axis direction, add the camera origin expressed in base.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/07",
  },
  {
    id: "required-bridge-16",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "Only an11s transform exists for an observation stamped10s on a moving system. What should processing do?",
    options: [
      "Apply the declared unavailable-history policy, not silently substitute the later relation",
      "Always rename the frame",
      "Always return identity",
      "Ignore the observation stamp",
    ],
    correct: 0,
    explanation:
      "A later transform can answer a different question; frame and time are part of the evidence.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/07",
  },
  {
    id: "required-bridge-17",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question: "A Nav2 goal is accepted but no final result exists. Which status is justified?",
    options: [
      "Pending/running, not successful completion",
      "Successful completion",
      "A certified protective stop",
      "A completed rollback",
    ],
    correct: 0,
    explanation: "Goal acceptance and the final action result are distinct stages.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/06",
  },
  {
    id: "required-bridge-18",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "A Nav2 cancellation request has not been acknowledged after timeout. What is justified?",
    options: [
      "Record uncertain outcome and follow explicit supervision policy",
      "Assume the robot has stopped",
      "Automatically resubmit motion indefinitely",
      "Report success because cancellation was requested",
    ],
    correct: 0,
    explanation: "Requesting cancellation does not prove acknowledgement or physical stopping.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/06",
  },
  {
    id: "optional-bridge-1",
    phaseId: "2",
    moduleId: "2-2",
    type: "multiple-choice",
    question:
      "A reduced-motion preference changes while a GSAP view is mounted. What preserves the authored accessible baseline?",
    options: [
      "Use matchMedia cleanup/revert and leave baseline content visible",
      "Hide the content until the next animation completes",
      "Disable all browser preferences",
      "Create another animation on every render",
    ],
    correct: 0,
    explanation:
      "Reverting the scoped animation removes its changes; the nonanimated baseline must remain usable.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-2/13",
  },
  {
    id: "optional-bridge-2",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "A PWA is installed, but its never-visited lesson fails offline. What evidence is missing?",
    options: [
      "An explicit cached-content and offline retrieval contract",
      "A larger home-screen icon",
      "An installation badge",
      "A paid account",
    ],
    correct: 0,
    explanation:
      "Installation does not establish which lesson responses and assets are available without a network.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/11",
  },
  {
    id: "optional-bridge-3",
    phaseId: "2",
    moduleId: "2-1",
    type: "multiple-choice",
    question:
      "A private lesson should be inaccessible to unauthorized readers. Which change addresses access control?",
    options: [
      "Enforce authorization when serving the resource",
      "Add a robots.txt disallow line only",
      "Remove the page title",
      "Add a noindex meta tag only",
    ],
    correct: 0,
    explanation: "Crawling and indexing directives do not prevent unauthorized retrieval.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-1/11",
  },
  {
    id: "optional-bridge-4",
    phaseId: "4",
    moduleId: "4-2",
    type: "multiple-choice",
    question:
      "A GraphQL request is syntactically valid and authenticated. What still needs checking before returning another learner’s record?",
    options: [
      "Authorization for that requested resource",
      "Only whether the query contains braces",
      "Whether the operation uses POST",
      "Only whether the schema has a String type",
    ],
    correct: 0,
    explanation: "Schema validity and authentication do not grant access to every object.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "4/4-2/10",
  },
  {
    id: "optional-bridge-5",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "A waiting service worker would activate while another tab is editing a draft under an older schema. What should the update design establish?",
    options: [
      "Draft durability and compatibility across both versions before forced takeover",
      "Delete every cache and database immediately",
      "Assume all open tabs reload together",
      "Treat the install event as proof of successful migration",
    ],
    correct: 0,
    explanation: "Worker lifecycle and stored-data schema compatibility are separate contracts.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/12",
  },
  {
    id: "optional-bridge-6",
    phaseId: "2",
    moduleId: "2-3",
    type: "multiple-choice",
    question:
      "A EUR price is displayed using German separators. Which value should remain in calculations?",
    options: [
      "The underlying numeric amount with its currency identity",
      "The formatted display string",
      "A string after removing every comma",
      "The number of rendered characters",
    ],
    correct: 0,
    explanation:
      "Formatting is locale-specific presentation, not a safe interchange representation for arithmetic.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "2/2-3/13",
  },
  {
    id: "optional-bridge-7",
    phaseId: "5",
    moduleId: "5-4",
    type: "multiple-choice",
    question:
      "A temporary database outage makes a service unable to serve requests but does not corrupt its process. Which probe design avoids a restart storm?",
    options: [
      "Readiness can fail while liveness checks independent process health",
      "Use the database dependency as the sole liveness check",
      "Restart every Pod whenever one request is slow",
      "Remove all startup and readiness checks",
    ],
    correct: 0,
    explanation:
      "Readiness controls traffic eligibility; liveness should identify conditions that restarting can remedy.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "5/5-4/09",
  },
  {
    id: "optional-bridge-8",
    phaseId: "10",
    moduleId: "10-1",
    type: "multiple-choice",
    question:
      "A CMake project defines a test executable but ctest reports no tests. What should be checked?",
    options: [
      "Testing is enabled and the test is registered with add_test",
      "Only whether main.c has a comment",
      "Whether the executable name contains test",
      "Whether compilation used the source directory as output",
    ],
    correct: 0,
    explanation: "Building an executable does not automatically register it with CTest.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-1/07",
  },
  {
    id: "optional-bridge-9",
    phaseId: "10",
    moduleId: "10-5",
    type: "multiple-choice",
    question:
      "A synthetic UART signal is 100000 baud and sampled at 2 MHz. How many samples span one bit?",
    options: ["20", "2", "200", "0.05"],
    correct: 0,
    explanation:
      "One bit is 10 microseconds and the sample interval is 0.5 microseconds: 10/0.5 = 20.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-5/06",
  },
  {
    id: "optional-bridge-10",
    phaseId: "10",
    moduleId: "10-6",
    type: "multiple-choice",
    question:
      "A qualified compiler release is approved for target T, but the project uses another target and a library outside the documented scope. What follows?",
    options: [
      "Check the exact qualification scope and address the uncovered configuration",
      "Assume the brand name qualifies the entire product",
      "Ignore library use because compilation succeeded",
      "Treat one passing unit test as tool qualification",
    ],
    correct: 0,
    explanation:
      "Qualification evidence is bounded by documented versions, targets, use conditions and exclusions.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-6/06",
  },
  {
    id: "optional-bridge-11",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "A runtime task chain costs 2+6+1 ms with a 12 ms deadline, then gains 5 ms queue wait. What does this trace show?",
    options: [
      "14 ms response time, exceeding the deadline by 2 ms",
      "9 ms response time because waiting never counts",
      "Guaranteed worst-case schedulability",
      "A certified physical stopping time",
    ],
    correct: 0,
    explanation:
      "Response time includes waiting: 2+6+1+5 = 14 ms. One trace does not prove a worst-case bound.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/09",
  },
  {
    id: "optional-bridge-12",
    phaseId: "10",
    moduleId: "10-7",
    type: "multiple-choice",
    question:
      "An AUTOSAR VFB trace shows one runnable finishing 15 microseconds after its stated deadline. What is a justified next step?",
    options: [
      "Preserve configuration and clock evidence, then investigate the measured miss",
      "Declare every ECU timing-safe",
      "Assume VFB naming proves physical bus timing",
      "Discard the trace because the code compiled",
    ],
    correct: 0,
    explanation:
      "A logical-interface trace requires configuration and timestamp interpretation; it is evidence for investigation, not blanket timing approval.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-7/09",
  },
  {
    id: "optional-bridge-13",
    phaseId: "10",
    moduleId: "10-4",
    type: "multiple-choice",
    question:
      "A Zephyr k_msgq_put call with K_NO_WAIT fails because the queue is full. What should the producer do under an explicit drop policy?",
    options: [
      "Record the failure/drop and continue according to that policy",
      "Pretend the sample was queued",
      "Keep a pointer to a destroyed stack object",
      "Assume K_NO_WAIT guarantees delivery",
    ],
    correct: 0,
    explanation:
      "Nonblocking queue operations can fail; bounded capacity requires an explicit, observable handling policy.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-4/06",
  },
  {
    id: "optional-bridge-14",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "Gazebo is paused while a ROS node uses simulation time. What should an integration test examine?",
    options: [
      "Clock progression and stale-data handling under the paused clock",
      "Only whether a model is visible",
      "Whether wall time alone advanced",
      "Whether simulation proves physical safety",
    ],
    correct: 0,
    explanation:
      "Rendering a model does not establish correct clock, bridge and freshness contracts.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/08",
  },
  {
    id: "optional-bridge-15",
    phaseId: "13",
    moduleId: "13-6",
    type: "multiple-choice",
    question:
      "A URsim trajectory goal is accepted but no final action result has arrived. Which evidence can be recorded?",
    options: [
      "Acceptance with completion still unverified",
      "Successful completed motion",
      "Physical cell safety approval",
      "An executed protective-stop test",
    ],
    correct: 0,
    explanation:
      "Goal acceptance is a separate event from execution completion and from physical safety validation.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "13/13-6/10",
  },
  {
    id: "optional-bridge-16",
    phaseId: "10",
    moduleId: "10-4",
    type: "multiple-choice",
    question:
      "A high-priority task waits for a mutex held by a low-priority task while medium-priority work runs. What scheduling risk is present?",
    options: [
      "Priority inversion requiring a bounded resource-sharing design",
      "A guarantee of immediate high-priority execution",
      "Proof that no task shares state",
      "A reason to remove all timing requirements",
    ],
    correct: 0,
    explanation:
      "A resource dependency can delay a high-priority task; protocol and blocking bounds matter alongside task priorities.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "10/10-4/01",
  },
  {
    id: "optional-bridge-17",
    phaseId: "14",
    moduleId: "14-10",
    type: "multiple-choice",
    question:
      "A batch completion message is retried after acknowledgement is lost. What prevents duplicate production credit?",
    options: [
      "An idempotent business operation keyed by the batch/event identity",
      "Counting every transport delivery as a new batch",
      "Deleting the original batch identifier",
      "Assuming a successful TCP connection means exactly-once business processing",
    ],
    correct: 0,
    explanation:
      "Transport retries require application-level identity and reconciliation to avoid duplicate effects.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "14/14-10/01",
  },
  {
    id: "optional-bridge-18",
    phaseId: "14",
    moduleId: "14-4",
    type: "multiple-choice",
    question:
      "Using planned time 400 minutes, run time 320, ideal cycle 0.5 minutes, 600 total pieces and 570 good, what is the teaching OEE?",
    options: ["71.25%", "79.17%", "95%", "80%"],
    correct: 0,
    explanation:
      "Availability is 320/400, performance is 300/320, and quality is 570/600; their product is 0.7125.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "14/14-4/07",
  },
  {
    id: "optional-bridge-19",
    phaseId: "14",
    moduleId: "14-7",
    type: "multiple-choice",
    question:
      "An AP242 handoff imports geometry but loses semantic PMI, while a drawing and model disagree on a tolerance. What is justified?",
    options: [
      "Resolve authority and verify the required semantic transfer before acceptance",
      "Accept solely because the file opens",
      "Select whichever tolerance is easier to meet",
      "Assume the AP242 extension proves full transfer fidelity",
    ],
    correct: 0,
    explanation:
      "An exchange format does not by itself establish authoritative requirements or successful transfer of required information.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "14/14-7/01",
  },
  {
    id: "optional-bridge-20",
    phaseId: "14",
    moduleId: "14-10",
    type: "multiple-choice",
    question:
      "A B2MML message passes the pinned XML schema, but repeats an already-processed production event. What additional check is needed?",
    options: [
      "Business identity and idempotency validation",
      "Only another XML well-formedness check",
      "Changing its namespace at random",
      "Treating schema validity as authorization",
    ],
    correct: 0,
    explanation:
      "Schema validation checks structure and declared constraints, not all business semantics, authorization or duplicate effects.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "14/14-10/02",
  },
  {
    id: "semantic-bridge-1",
    phaseId: "6",
    moduleId: "6-1",
    type: "multiple-choice",
    question:
      "A causal attention row at position1 has allowed scores0 and log(3), values2 and6, and a future value1000. What is its output?",
    options: ["5", "4", "1000", "8"],
    correct: 0,
    explanation:
      "Allowed weights are1/4 and3/4;0.25*2+0.75*6=5. The future position is excluded before normalization.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "6/6-1/09",
  },
  {
    id: "semantic-bridge-2",
    phaseId: "6",
    moduleId: "6-1",
    type: "multiple-choice",
    question:
      "A multimodal retrieval score is0.60 for a caption. What can be concluded without calibration evidence?",
    options: [
      "It is a score under the model’s scoring rule, not a60% correctness probability",
      "The caption is certainly correct",
      "The caption has60% probability of being true",
      "The image cannot be missing",
    ],
    correct: 0,
    explanation:
      "Similarity scores require separate calibration before interpreting them as outcome probabilities.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "6/6-1/10",
  },
  {
    id: "semantic-bridge-3",
    phaseId: "6",
    moduleId: "6-1",
    type: "multiple-choice",
    question: "For rewards[0,0,8] and discount0.5, what is the finite return?",
    options: ["2", "8", "4", "0"],
    correct: 0,
    explanation: "The delayed reward is multiplied by0.5 squared, so the return is2.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "6/6-1/11",
  },
  {
    id: "semantic-bridge-4",
    phaseId: "6",
    moduleId: "6-1",
    type: "multiple-choice",
    question:
      "A and B both succeed on60 paired queries, only A on10, only B on20 and neither on10. What is the observed accuracy difference B minus A?",
    options: [
      "10 percentage points; significance and generalization are not established by this summary alone",
      "20 percentage points with guaranteed significance",
      "30 percentage points",
      "10% proves B generalizes to every domain",
    ],
    correct: 0,
    explanation:
      "A is correct on70 of100 and B on80; the observed difference is10 percentage points, with30 disagreements.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "6/6-1/12",
  },
  {
    id: "semantic-bridge-5",
    phaseId: "9",
    moduleId: "9-1",
    type: "multiple-choice",
    question:
      "Two migration proposals disagree: A has an untested rollback; B takes two days with tested recovery inside a three-day window. What is the best decision record?",
    options: [
      "Compare constraints, assign an owner and review trigger, and document the recovery evidence",
      "Label the cautious engineer uncooperative",
      "Choose the shortest duration without examining recovery",
      "Promise that all conflict is resolved after the meeting",
    ],
    correct: 0,
    explanation:
      "A defensible technical decision records evidence, authority and reconsideration conditions without inferring motives.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-1/09",
  },
  {
    id: "semantic-bridge-6",
    phaseId: "9",
    moduleId: "9-1",
    type: "multiple-choice",
    question:
      "A16:00 UTC call occurs at21:30 for one participant, and its decision closes before they can comment. What improves meaningful participation?",
    options: [
      "Accessible asynchronous input before closure, a clear owner and a recorded response to concerns",
      "A recording alone after the decision",
      "Ranking engineers by camera use",
      "Requiring permanent evening attendance",
    ],
    correct: 0,
    explanation:
      "Information access after closure does not provide a timely opportunity to influence the decision.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-1/10",
  },
  {
    id: "semantic-bridge-7",
    phaseId: "9",
    moduleId: "9-7",
    type: "multiple-choice",
    question:
      "Leadership wants to rank engineers by lines of code. Which alternative supports developer-experience improvement?",
    options: [
      "Combine team outcomes, flow, quality and qualitative friction evidence",
      "Rank by message count instead",
      "Reward the largest diffs",
      "Ignore quality because it is difficult to count",
    ],
    correct: 0,
    explanation:
      "Productivity and developer experience require multiple forms of evidence; activity alone is a misleading target.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-7/04",
  },
  {
    id: "semantic-bridge-8",
    phaseId: "9",
    moduleId: "9-3",
    type: "multiple-choice",
    question:
      "Four teams share one overloaded infrastructure engineer. What makes a six-week ownership change evaluable?",
    options: [
      "Baseline bottlenecks, explicit ownership and support boundaries, success and reversal criteria",
      "A new org chart without transition work",
      "Counting only meetings attended",
      "Assuming the chosen structure is permanent",
    ],
    correct: 0,
    explanation:
      "A bounded experiment connects the change to measurable conditions and protects the transition with clear responsibilities.",
    difficulty: "medium",
    tags: ["career-foundation"],
    sourceLesson: "9/9-3/07",
  },
];
