import type { AssessmentQuestion } from "@/types/assessment";

function q(
  id: string,
  moduleId: string,
  type: AssessmentQuestion["type"],
  question: string,
  options: string[],
  correct: number | number[],
  explanation: string,
  difficulty: AssessmentQuestion["difficulty"],
  tags: string[]
): AssessmentQuestion {
  return {
    id,
    phaseId: "7",
    moduleId,
    type,
    question,
    options,
    correct,
    explanation,
    difficulty,
    tags,
    standards: { bloom: "analyze" },
  };
}

export const PHASE_7_QUESTIONS: AssessmentQuestion[] = [
  // ── Module 7-1: Compilers and Interpreters ───────────────────────────────
  q(
    "7-1-q1",
    "7-1",
    "multiple-choice",
    "What is the first stage of a compiler pipeline?",
    ["Parsing", "Lexing (tokenization)", "Code generation", "Optimization"],
    1,
    "Lexing converts the raw character stream into a sequence of tokens — the first step in language processing.",
    "easy",
    ["compiler", "lexer"]
  ),
  q(
    "7-1-q2",
    "7-1",
    "multiple-choice",
    "What does a parser produce?",
    ["Machine code", "An Abstract Syntax Tree (AST)", "Bytecode", "A list of tokens"],
    1,
    "The parser takes tokens and builds a tree structure (AST) that represents the program's structure.",
    "easy",
    ["parser", "ast"]
  ),
  q(
    "7-1-q3",
    "7-1",
    "multiple-choice",
    "What is an AST?",
    [
      "A type of database",
      "A tree representing the grammatical structure of source code",
      "An encryption algorithm",
      "A networking protocol",
    ],
    1,
    "Abstract Syntax Trees represent program structure. Linters, formatters, and transpilers all operate on ASTs.",
    "easy",
    ["ast"]
  ),
  q(
    "7-1-q4",
    "7-1",
    "true-false",
    "True or false: JIT compilation compiles code at runtime rather than ahead of time.",
    ["True", "False"],
    0,
    "Just-In-Time compilation compiles frequently-executed code paths during program execution for better performance.",
    "easy",
    ["jit", "compiler"]
  ),
  q(
    "7-1-q5",
    "7-1",
    "multiple-choice",
    "What is constant folding?",
    [
      "Removing unused variables",
      "Evaluating constant expressions at compile time (e.g., 2+3 → 5)",
      "Inlining function calls",
      "Loop unrolling",
    ],
    1,
    "Constant folding replaces compile-time-computable expressions with their results, reducing runtime work.",
    "medium",
    ["optimization"]
  ),
  q(
    "7-1-q6",
    "7-1",
    "multiple-choice",
    "What does semantic analysis check that parsing cannot?",
    [
      "Syntax errors",
      "Type mismatches and undeclared variables",
      "Missing semicolons",
      "Indentation",
    ],
    1,
    "Semantic analysis catches errors like using an undeclared variable or passing the wrong type — issues that are syntactically valid but logically wrong.",
    "medium",
    ["semantic-analysis"]
  ),
  q(
    "7-1-q7",
    "7-1",
    "multiple-choice",
    "What is a recursive descent parser?",
    [
      "A parser that uses loops",
      "A parser where each grammar rule becomes a function that can call itself",
      "A parser that reads backwards",
      "A parser that uses regular expressions",
    ],
    1,
    "Recursive descent maps each grammar production to a function. Nested rules naturally become recursive calls.",
    "medium",
    ["parser", "recursive-descent"]
  ),
  q(
    "7-1-q8",
    "7-1",
    "multiple-choice",
    "What is bytecode?",
    [
      "Machine code for a specific CPU",
      "An intermediate representation executed by a virtual machine",
      "Encrypted source code",
      "Compressed binary data",
    ],
    1,
    "Bytecode is a platform-independent intermediate format. The JVM, Python VM, and V8 all use bytecode internally.",
    "medium",
    ["bytecode", "vm"]
  ),
  q(
    "7-1-q9",
    "7-1",
    "multiple-choice",
    "Why is dead code elimination useful?",
    [
      "It makes source files smaller",
      "It removes code that can never execute, reducing binary size and improving performance",
      "It formats code",
      "It catches bugs",
    ],
    1,
    "Dead code elimination removes unreachable code paths, reducing the size and improving the speed of compiled output.",
    "hard",
    ["optimization", "dead-code"]
  ),
  q(
    "7-1-q10",
    "7-1",
    "multiple-choice",
    "What is the visitor pattern used for with ASTs?",
    [
      "Parsing tokens",
      "Traversing and operating on each node type without modifying the tree structure",
      "Generating random trees",
      "Compressing trees",
    ],
    1,
    "The visitor pattern separates the operation (what to do at each node) from the traversal (how to walk the tree).",
    "hard",
    ["ast", "visitor-pattern"]
  ),
  q(
    "7-1-q11",
    "7-1",
    "multiple-choice",
    "What does the lexer (tokenizer) do, exactly?",
    [
      "Builds the abstract syntax tree.",
      "Reads the raw source text and produces a stream of tokens (keywords, identifiers, literals, punctuation), discarding whitespace and comments.",
      "Generates machine code.",
      "Performs type checking.",
    ],
    1,
    "Lexing is stage 1: text → tokens. Each token has a kind (IDENT, NUMBER, IF, LPAREN) and usually a value and source position. The parser then consumes tokens to build the AST.",
    "easy",
    ["lexer", "tokens"]
  ),
  q(
    "7-1-q12",
    "7-1",
    "multiple-choice",
    "What's the practical difference between a compiler and an interpreter?",
    [
      "Compilers produce executable files ahead of time; interpreters execute the source (or an intermediate form) directly at runtime.",
      "Compilers are faster than interpreters in every case.",
      "Interpreters don't support recursion.",
      "Compilers only work on statically typed languages.",
    ],
    0,
    "A compiler translates the whole program to a target (machine code, bytecode, JS) before execution. An interpreter walks the source or an intermediate representation and executes as it goes. Hybrid systems (JITs) blur the line.",
    "easy",
    ["compiler", "interpreter"]
  ),
  q(
    "7-1-q13",
    "7-1",
    "multiple-choice",
    "What does SSA (Static Single Assignment) form make easier in an optimizing compiler?",
    [
      "Source-level debugging.",
      "Dataflow analyses (constant propagation, dead-code elimination, common-subexpression elimination) by guaranteeing each variable is assigned exactly once.",
      "Lexing the source.",
      "Producing readable error messages.",
    ],
    1,
    "In SSA every assignment creates a fresh variable version (x1, x2, x3 ...). Reasoning about 'where did this value come from' becomes a single-edge lookup, which makes most dataflow optimizations dramatically simpler and faster.",
    "medium",
    ["ssa", "optimization"]
  ),
  q(
    "7-1-q14",
    "7-1",
    "multiple-choice",
    "Register allocation is hard primarily because:",
    [
      "Modern CPUs have unlimited registers.",
      "There are typically far fewer hardware registers than live values in the program, and choosing which values to keep in registers vs spill to memory is an NP-hard graph-coloring problem in the general case.",
      "Registers are slower than memory.",
      "Compilers can't read register names.",
    ],
    1,
    "Live ranges of variables interfere when they're alive at the same time. Mapping them to a fixed number of hardware registers is equivalent to graph coloring — NP-hard in general, solved with heuristics like linear scan or Chaitin's algorithm.",
    "medium",
    ["register-allocation", "optimization"]
  ),
  q(
    "7-1-q15",
    "7-1",
    "multiple-choice",
    "What is tail-call optimization (TCO), and why is it interesting?",
    [
      "A way to make the last function in a file run faster.",
      "When a function's last action is to call another function (often itself), the compiler can reuse the current stack frame — turning recursion into iteration and avoiding stack overflow on deep recursion.",
      "An optimization that only applies to JavaScript.",
      "A way to reduce binary size by removing the tail of each function.",
    ],
    1,
    "TCO is what lets functional languages (Scheme, OCaml, Haskell) use recursion for everything without blowing the stack. Some VMs implement it; most C compilers do for tail calls. JavaScript's spec includes it but most engines don't.",
    "hard",
    ["tco", "recursion", "optimization"]
  ),

  // ── Module 7-2: Distributed Systems ──────────────────────────────────────
  q(
    "7-2-q1",
    "7-2",
    "multiple-choice",
    "What does the CAP theorem state?",
    [
      "You can have all three: consistency, availability, partition tolerance",
      "A distributed system can provide at most two of: consistency, availability, partition tolerance",
      "CAP stands for Cache, API, Performance",
      "Distributed systems are always consistent",
    ],
    1,
    "CAP: in a network partition, you must choose between consistency (all nodes see the same data) and availability (every request gets a response).",
    "easy",
    ["cap-theorem"]
  ),
  q(
    "7-2-q2",
    "7-2",
    "multiple-choice",
    "What problem does the Raft algorithm solve?",
    [
      "Load balancing",
      "Consensus — getting distributed nodes to agree on a value",
      "Data compression",
      "DNS resolution",
    ],
    1,
    "Raft is a consensus algorithm: leader election + log replication, ensuring all nodes agree on the state.",
    "easy",
    ["raft", "consensus"]
  ),
  q(
    "7-2-q3",
    "7-2",
    "true-false",
    "True or false: eventual consistency means all nodes will eventually agree, but may temporarily return different values.",
    ["True", "False"],
    0,
    "Eventual consistency trades immediate consistency for availability — writes propagate asynchronously.",
    "easy",
    ["eventual-consistency"]
  ),
  q(
    "7-2-q4",
    "7-2",
    "multiple-choice",
    "What is consistent hashing used for?",
    [
      "Encrypting data",
      "Distributing data across nodes so that adding/removing a node only moves a fraction of keys",
      "Sorting data",
      "Compressing data",
    ],
    1,
    "Consistent hashing minimizes data movement when the cluster changes — only K/n keys move on average.",
    "easy",
    ["consistent-hashing"]
  ),
  q(
    "7-2-q5",
    "7-2",
    "multiple-choice",
    "What is 'exactly-once' delivery in message queues?",
    [
      "Messages are always delivered once",
      "A guarantee that each message is processed exactly once — achieved through idempotency and deduplication",
      "Messages are never lost",
      "Messages arrive in order",
    ],
    1,
    "True exactly-once is nearly impossible. In practice it's achieved via at-least-once delivery + idempotent consumers.",
    "medium",
    ["message-queue", "exactly-once"]
  ),
  q(
    "7-2-q6",
    "7-2",
    "multiple-choice",
    "What is a saga pattern?",
    [
      "A single distributed transaction",
      "A sequence of local transactions with compensating actions for rollback",
      "A type of database index",
      "A consensus algorithm",
    ],
    1,
    "Sagas break a distributed transaction into local steps, each with a compensating action if a later step fails.",
    "medium",
    ["saga", "distributed-transaction"]
  ),
  q(
    "7-2-q7",
    "7-2",
    "multiple-choice",
    "What do Lamport clocks provide?",
    [
      "Exact wall-clock time across nodes",
      "A logical ordering of events — if A happened before B, Clock(A) < Clock(B)",
      "GPS synchronization",
      "Network latency measurement",
    ],
    1,
    "Lamport clocks give a partial causal ordering. If A→B then L(A)<L(B), but L(A)<L(B) does not imply A→B.",
    "medium",
    ["lamport-clock", "ordering"]
  ),
  q(
    "7-2-q8",
    "7-2",
    "multiple-choice",
    "What is a CRDT?",
    [
      "A type of database",
      "A data structure that can be replicated across nodes and merged without conflicts",
      "A consensus protocol",
      "A compression algorithm",
    ],
    1,
    "Conflict-free Replicated Data Types (CRDTs) guarantee convergence — all replicas reach the same state regardless of merge order.",
    "hard",
    ["crdt"]
  ),
  q(
    "7-2-q9",
    "7-2",
    "multiple-choice",
    "Why does two-phase commit (2PC) have a blocking problem?",
    [
      "It uses too much network bandwidth",
      "If the coordinator crashes after sending 'prepare' but before 'commit', participants are stuck waiting",
      "It's too slow",
      "It doesn't support multiple nodes",
    ],
    1,
    "2PC participants that voted 'yes' cannot proceed or abort until they hear from the coordinator — a single point of failure.",
    "hard",
    ["2pc", "distributed-transaction"]
  ),
  q(
    "7-2-q10",
    "7-2",
    "multiple-choice",
    "What advantage do vector clocks have over Lamport clocks?",
    [
      "They're simpler",
      "They can detect whether two events are concurrent (neither caused the other)",
      "They're faster",
      "They use less memory",
    ],
    1,
    "Vector clocks track causality per node, allowing detection of concurrent events — Lamport clocks cannot distinguish concurrency from ordering.",
    "hard",
    ["vector-clock", "lamport-clock"]
  ),
  q(
    "7-2-q11",
    "7-2",
    "multiple-choice",
    "In a Dynamo-style replicated system with N replicas, what does a quorum read with R + W > N guarantee?",
    [
      "Linearizability under network partitions.",
      "That a successful write set and a successful read set must overlap by at least one replica — so reads always see the most recent successful write.",
      "That replicas never disagree.",
      "That reads complete in O(1) round trips.",
    ],
    1,
    "Quorums (N replicas, write to W, read from R) with R + W > N ensure overlap. Reads will hit at least one replica that saw the latest write. Trade between read and write speed by adjusting R and W.",
    "easy",
    ["quorum", "replication"]
  ),
  q(
    "7-2-q12",
    "7-2",
    "true-false",
    "True or false: making a distributed operation idempotent (safe to retry) is one of the most common ways to handle unreliable networks without coordination overhead.",
    ["True", "False"],
    0,
    "If retrying a request yields the same result as running it once (e.g., 'set balance to $100' rather than 'add $5'), clients can safely retry on timeout. Idempotency keys let servers dedupe duplicate retries.",
    "easy",
    ["idempotency", "retries"]
  ),
  q(
    "7-2-q13",
    "7-2",
    "multiple-choice",
    "What is a gossip protocol used for in distributed systems?",
    [
      "Encrypting messages between nodes.",
      "Spreading state (membership, failure detection, metrics) across a cluster by having each node periodically exchange info with a few random peers — converging in O(log N) rounds without a coordinator.",
      "Compressing data before replication.",
      "Routing queries to the nearest replica.",
    ],
    1,
    "Used by Cassandra, Consul, Serf, and many others for membership and failure detection. Probabilistic, decentralized, and resilient to node churn. The classic 'rumor-spreading' or 'epidemic' algorithm.",
    "medium",
    ["gossip", "membership"]
  ),
  q(
    "7-2-q14",
    "7-2",
    "multiple-choice",
    "Bloom filters are widely used in distributed systems. What do they let you do?",
    [
      "Verify a network packet's integrity.",
      "Check 'is X probably in this set?' with no false negatives but possible false positives, using far less memory than storing the set itself.",
      "Find the shortest path between two nodes.",
      "Encrypt small messages.",
    ],
    1,
    "A Bloom filter is a bit array + k hash functions. 'Definitely not in set' or 'maybe in set' — never 'definitely in'. Cassandra uses them to avoid disk reads for non-existent keys; CDNs use them for cache lookup; Chrome used them for malicious URL checks.",
    "medium",
    ["bloom-filter", "probabilistic"]
  ),
  q(
    "7-2-q15",
    "7-2",
    "multiple-choice",
    "PACELC extends CAP with a 'normal operations' axis. What does it actually say?",
    [
      "PACELC is a different name for CAP with no extra meaning.",
      "If there is a Partition (P), choose Availability or Consistency; Else (during normal operation), choose Latency or Consistency. Real systems make BOTH tradeoffs, not just CAP's partition one.",
      "PACELC is for relational DBs only; CAP is for NoSQL only.",
      "PACELC stands for 'Parallel Asynchronous Consensus, Eventually Linearizable Consistency'.",
    ],
    1,
    "CAP only describes behavior during partitions. PACELC (Abadi) points out that even with no partition, you trade Latency for Consistency on every operation. A DB is 'PA/EL' (partition-available, else-latency-priority) like Dynamo, or 'PC/EC' like a single-leader RDBMS.",
    "hard",
    ["pacelc", "cap", "consistency"]
  ),

  // ── Module 7-3: Rust Fundamentals ────────────────────────────────────────
  q(
    "7-3-q1",
    "7-3",
    "multiple-choice",
    "What is Rust's primary innovation over C/C++?",
    [
      "Garbage collection",
      "Memory safety guaranteed at compile time without a garbage collector",
      "Dynamic typing",
      "Interpreted execution",
    ],
    1,
    "Rust's ownership system prevents use-after-free, double-free, and data races at compile time — no GC overhead.",
    "easy",
    ["rust", "ownership"]
  ),
  q(
    "7-3-q2",
    "7-3",
    "multiple-choice",
    "What happens when you assign a value to a new variable in Rust (non-Copy type)?",
    [
      "The value is copied",
      "The value is moved — the original variable is invalidated",
      "Both variables share the value",
      "A reference is created",
    ],
    1,
    "Move semantics: ownership transfers. The original binding becomes invalid, preventing double-free.",
    "easy",
    ["ownership", "move"]
  ),
  q(
    "7-3-q3",
    "7-3",
    "true-false",
    "True or false: in Rust, you can have one mutable reference OR many immutable references to a value, but never both simultaneously.",
    ["True", "False"],
    0,
    "This rule prevents data races at compile time. The borrow checker enforces it.",
    "easy",
    ["borrowing", "borrow-checker"]
  ),
  q(
    "7-3-q4",
    "7-3",
    "multiple-choice",
    "What does Option<T> represent in Rust?",
    [
      "An optional function parameter",
      "A value that might be present (Some(T)) or absent (None) — replacing null",
      "A configuration option",
      "An optimization hint",
    ],
    1,
    "Option<T> eliminates null pointer errors. You must explicitly handle the None case — the compiler enforces it.",
    "easy",
    ["option", "rust"]
  ),
  q(
    "7-3-q5",
    "7-3",
    "multiple-choice",
    "What does the ? operator do in Rust?",
    [
      "Checks if a value is null",
      "Propagates errors — returns early with the Err if the Result is Err, unwraps the Ok otherwise",
      "Creates a new variable",
      "Converts types",
    ],
    1,
    "The ? operator is syntactic sugar for match { Ok(v) => v, Err(e) => return Err(e) }.",
    "medium",
    ["error-handling", "result"]
  ),
  q(
    "7-3-q6",
    "7-3",
    "multiple-choice",
    "What is a lifetime annotation in Rust?",
    [
      "How long a program runs",
      "A label that tells the compiler how long a reference is valid relative to other references",
      "A performance metric",
      "A type of loop",
    ],
    1,
    "Lifetimes prevent dangling references. 'a means 'this reference is valid for at least lifetime a.'",
    "medium",
    ["lifetime", "rust"]
  ),
  q(
    "7-3-q7",
    "7-3",
    "multiple-choice",
    "What is a trait in Rust?",
    [
      "A class",
      "A shared set of method signatures that types can implement — like an interface",
      "A module",
      "A macro",
    ],
    1,
    "Traits define shared behavior. impl Display for MyType lets MyType be printed. Generic bounds use traits: fn foo<T: Display>(x: T).",
    "medium",
    ["trait", "rust"]
  ),
  q(
    "7-3-q8",
    "7-3",
    "multiple-choice",
    "What is 'zero-cost abstraction' in Rust?",
    [
      "Rust is free to use",
      "High-level abstractions compile to the same machine code as hand-written low-level code",
      "Abstractions have no runtime cost because they're removed",
      "Rust doesn't support abstractions",
    ],
    1,
    "Iterators, generics, and traits in Rust compile to code as efficient as manual loops — no overhead for the abstraction.",
    "hard",
    ["zero-cost", "rust"]
  ),
  q(
    "7-3-q9",
    "7-3",
    "multiple-choice",
    "Why does Rust distinguish between panic! and Result<T, E>?",
    [
      "They are the same thing",
      "panic! is for unrecoverable errors (bugs); Result is for expected, recoverable errors",
      "Result is faster",
      "panic! is deprecated",
    ],
    1,
    "Recoverable errors (file not found, network timeout) use Result. Unrecoverable errors (index out of bounds in a bug) use panic!.",
    "hard",
    ["error-handling", "panic", "result"]
  ),
  q(
    "7-3-q10",
    "7-3",
    "multiple-choice",
    "What is the 'static lifetime?",
    [
      "A lifetime that lasts one function call",
      "A lifetime that lasts for the entire program — string literals and owned data moved into threads have 'static",
      "A compile-time constant",
      "A static method",
    ],
    1,
    "'static means the data is valid for the entire program duration. String literals are &'static str.",
    "hard",
    ["lifetime", "static"]
  ),
  q(
    "7-3-q11",
    "7-3",
    "multiple-choice",
    "What is Cargo in the Rust ecosystem?",
    [
      "A linter for Rust code.",
      "The build tool and package manager — runs builds, tests, docs, and pulls dependencies from crates.io.",
      "An IDE.",
      "A profiler.",
    ],
    1,
    "cargo new, cargo build, cargo test, cargo run, cargo doc, cargo publish. Single tool for the full project lifecycle; reads Cargo.toml for project metadata and dependencies.",
    "easy",
    ["cargo", "tooling"]
  ),
  q(
    "7-3-q12",
    "7-3",
    "multiple-choice",
    "When would you use `cargo check` instead of `cargo build`?",
    [
      "When you don't have a network connection.",
      "When you want fast feedback that the code compiles (type-checks and borrow-checks) without producing executables — useful during iterative editing.",
      "When you only want to run the tests.",
      "When you're publishing the crate.",
    ],
    1,
    "cargo check skips codegen and linking, so it's much faster than a full build. Editor integrations (rust-analyzer) run check on save for live diagnostics. Use build when you actually need the artifact.",
    "easy",
    ["cargo", "tooling"]
  ),
  q(
    "7-3-q13",
    "7-3",
    "multiple-choice",
    "What does `Box<T>` give you that a plain `T` does not?",
    [
      "Garbage collection.",
      "Heap allocation with a stable address — useful for recursive data structures, trait objects (Box<dyn Trait>), and large values you don't want on the stack.",
      "Reference counting.",
      "Thread safety.",
    ],
    1,
    "Box owns a single heap allocation. Recursive types like enum Node { Branch(Box<Node>) } need Box because their size is otherwise undefined. Trait objects need Box because their size depends on the concrete type. For shared ownership, use Rc or Arc.",
    "medium",
    ["box", "heap", "smart-pointer"]
  ),
  q(
    "7-3-q14",
    "7-3",
    "multiple-choice",
    "What do the marker traits `Send` and `Sync` indicate?",
    [
      "Send means the type can be encrypted; Sync means it can be cached.",
      "Send means the type can be safely transferred to another thread; Sync means it can be safely shared between threads via &T. Rc<T> is neither; Arc<T> is both.",
      "Send means the type is a network message; Sync means it's synchronous.",
      "They're identical traits with different names.",
    ],
    1,
    "Auto-derived by the compiler when components allow. Send + Sync drive the compiler's data-race-freedom guarantee: passing a !Send value across thread boundaries is a compile-time error.",
    "medium",
    ["send", "sync", "concurrency"]
  ),
  q(
    "7-3-q15",
    "7-3",
    "multiple-choice",
    "What problem does `Pin<T>` solve?",
    [
      "Lets you pin a tab in the terminal.",
      "Prevents a value from being moved in memory — necessary for self-referential structures (where one field holds a pointer into another field of the same value), which async generators rely on.",
      "Pins a dependency version in Cargo.toml.",
      "Marks a function as inlined.",
    ],
    1,
    "Async/await desugars into state machines whose generated structs may hold pointers into themselves (e.g., across an .await across local data). If such a struct is moved, those pointers become dangling. Pin<T> tells the compiler 'this value's memory address must not change'.",
    "hard",
    ["pin", "async", "self-referential"]
  ),

  // ── Module 7-4: Performance Engineering ──────────────────────────────────
  q(
    "7-4-q1",
    "7-4",
    "multiple-choice",
    "What does a flame graph show?",
    [
      "Memory usage over time",
      "CPU time spent in each function — width = time, stack depth = call chain",
      "Network traffic",
      "Disk I/O",
    ],
    1,
    "Flame graphs visualize profiling data: the wider a bar, the more time spent in that function (or its children).",
    "easy",
    ["profiling", "flame-graph"]
  ),
  q(
    "7-4-q2",
    "7-4",
    "multiple-choice",
    "Why do microbenchmarks often lie?",
    [
      "They're too fast to measure",
      "JIT warmup, GC pauses, branch prediction, and CPU caching make isolated measurements unrepresentative of real workloads",
      "They use too much memory",
      "They only work on Linux",
    ],
    1,
    "Microbenchmarks measure in isolation. Real performance depends on the surrounding system — cache state, GC pressure, concurrent load.",
    "easy",
    ["benchmarking"]
  ),
  q(
    "7-4-q3",
    "7-4",
    "true-false",
    "True or false: cache invalidation is considered one of the hardest problems in computer science.",
    ["True", "False"],
    0,
    "The two hard problems: naming things, cache invalidation, and off-by-one errors. Knowing when cached data is stale is genuinely hard.",
    "easy",
    ["cache-invalidation"]
  ),
  q(
    "7-4-q4",
    "7-4",
    "multiple-choice",
    "What is back-pressure in a concurrent system?",
    [
      "A compression technique",
      "A mechanism where a slow consumer signals the fast producer to slow down, preventing memory overflow",
      "A type of load balancer",
      "A network protocol",
    ],
    1,
    "Without back-pressure, a fast producer overwhelms a slow consumer, filling queues until memory runs out.",
    "easy",
    ["back-pressure", "concurrency"]
  ),
  q(
    "7-4-q5",
    "7-4",
    "multiple-choice",
    "What is the most common cause of memory leaks in JavaScript?",
    [
      "Too many variables",
      "Forgotten references: closures capturing objects, detached DOM nodes, growing arrays that are never trimmed",
      "Using const",
      "Too many function calls",
    ],
    1,
    "The GC can't collect objects that are still reachable. Closures and global references are the usual culprits.",
    "medium",
    ["memory-leak", "profiling"]
  ),
  q(
    "7-4-q6",
    "7-4",
    "multiple-choice",
    "Why does CPU cache locality matter for performance?",
    [
      "It doesn't — CPUs are fast enough",
      "Accessing data already in L1 cache is ~100x faster than fetching from main memory",
      "Cache only affects GPU code",
      "Only matters for embedded systems",
    ],
    1,
    "L1 cache: ~1ns. Main memory: ~100ns. Sequential array access is fast because the CPU prefetches contiguous memory into cache.",
    "medium",
    ["cache", "performance"]
  ),
  q(
    "7-4-q7",
    "7-4",
    "multiple-choice",
    "What is sampling-based profiling?",
    [
      "Running code once and measuring",
      "Periodically recording which function is executing, then building a statistical picture of where time is spent",
      "Measuring memory allocation",
      "Counting function calls",
    ],
    1,
    "Sampling interrupts at intervals (e.g., 1ms) and records the call stack. Low overhead, statistical accuracy.",
    "medium",
    ["profiling", "sampling"]
  ),
  q(
    "7-4-q8",
    "7-4",
    "multiple-choice",
    "What is the correct order for the performance optimization loop?",
    [
      "Optimize → measure → guess",
      "Measure (profile) → identify bottleneck → fix → measure again",
      "Rewrite everything → hope it's faster",
      "Add more servers → measure",
    ],
    1,
    "Never optimize without profiling first. Measure, find the actual bottleneck, fix it, then verify with measurement.",
    "medium",
    ["optimization", "workflow"]
  ),
  q(
    "7-4-q9",
    "7-4",
    "multiple-choice",
    "What is work stealing in a thread pool?",
    [
      "Threads delete each other's work",
      "Idle threads take tasks from busy threads' queues to balance load dynamically",
      "A security vulnerability",
      "A scheduling algorithm for disk I/O",
    ],
    1,
    "Work stealing balances load without central coordination — idle threads 'steal' from the back of other threads' deques.",
    "hard",
    ["concurrency", "work-stealing"]
  ),
  q(
    "7-4-q10",
    "7-4",
    "multiple-choice",
    "When should you reach for Web Workers in a browser application?",
    [
      "For every function call",
      "For CPU-intensive work that would block the main thread (parsing, encryption, image processing)",
      "For network requests",
      "For DOM manipulation",
    ],
    1,
    "Web Workers run on separate threads. Use them for heavy computation; DOM access must stay on the main thread.",
    "hard",
    ["web-workers", "concurrency"]
  ),
  q(
    "7-4-q11",
    "7-4",
    "multiple-choice",
    "What's the broadest performance lesson behind 'algorithm beats constant factor'?",
    [
      "Constants don't matter — only choose the algorithm.",
      "A better-complexity algorithm (O(n log n) over O(n^2)) usually beats microoptimizations on the wrong algorithm. Pick the right shape first, then tune constants if you still need to.",
      "Algorithms are only theoretical; in practice, constants always dominate.",
      "Constant factors and algorithmic complexity are unrelated.",
    ],
    1,
    "Replacing O(n^2) with O(n log n) is a structural win that scales. Replacing one O(n) with a 2x faster O(n) helps a fixed amount. The first principle of performance work: don't tune what should be replaced.",
    "easy",
    ["algorithm", "complexity"]
  ),
  q(
    "7-4-q12",
    "7-4",
    "multiple-choice",
    "What does the Linux `perf` tool primarily do?",
    [
      "Compiles code with optimization flags.",
      "Samples performance counters (CPU cycles, cache misses, branch mispredicts, function call counts) on running processes — letting you see where time is actually going at hardware granularity.",
      "Runs unit tests.",
      "Profiles network throughput.",
    ],
    1,
    "perf hooks into Linux's hardware performance counters and kernel tracepoints. Outputs include flame graphs, hot-function reports, and per-instruction sampling. Pair with debug symbols for actionable results.",
    "easy",
    ["perf", "profiling"]
  ),
  q(
    "7-4-q13",
    "7-4",
    "multiple-choice",
    "Two threads write to different elements of the same struct, on different CPU cores. Why might this be far slower than expected?",
    [
      "Compiler bug.",
      "False sharing: even though the threads touch different bytes, those bytes share a cache line, so each write invalidates the other core's copy of the entire line. Solution: pad fields to separate cache lines.",
      "Cosmic-ray bit flips.",
      "The kernel pre-empts both threads simultaneously.",
    ],
    1,
    "Cache coherence operates at cache-line granularity (usually 64 bytes). Independent variables that happen to live in the same line ping-pong between cores. Diagnose with perf c2c; fix with padding or layout changes.",
    "medium",
    ["false-sharing", "cache"]
  ),
  q(
    "7-4-q14",
    "7-4",
    "multiple-choice",
    "Pushing to a dynamic array (Vec, ArrayList) is described as 'amortized O(1)' even though occasional resizes copy every element. What does that mean?",
    [
      "Every push is exactly the same cost.",
      "The total cost of N pushes is O(N), so the per-push cost averaged over the sequence is O(1) — even though individual resize pushes are O(n).",
      "Push is always free in practice.",
      "Amortized just means 'usually fast'.",
    ],
    1,
    "When you double capacity on overflow, the geometric series of copy costs sums to O(N) over N pushes. So the AVERAGE cost is constant, even though individual operations vary. Don't confuse amortized cost with average-case cost.",
    "medium",
    ["amortized", "complexity"]
  ),
  q(
    "7-4-q15",
    "7-4",
    "multiple-choice",
    "Why can a branch misprediction be more expensive than a memory access on a modern CPU?",
    [
      "Branches don't actually cost anything.",
      "Modern CPUs speculatively execute the predicted branch path; a misprediction flushes the entire pipeline (often 15-20 stages of partially-executed work), which costs more than a single L1 or L2 cache access.",
      "Branches require kernel mode switches.",
      "Memory access is free on modern CPUs.",
    ],
    1,
    "The pipeline-flush penalty on a misprediction can be ~15-20 cycles of wasted work. Compare to an L1 hit at ~4 cycles. This is why branchless code (cmov, predication, sorted data) can be dramatically faster on hot paths — even if it does more total work.",
    "hard",
    ["branch-prediction", "pipeline"]
  ),
];
