import type { AssessmentQuestion } from "@/types/assessment";

// Applied public practice items. These assess the stated scenario, not a
// professional certification, machine approval, or secret examination.
type Item = [
  question: string,
  answer: string,
  distractorA: string,
  distractorB: string,
  distractorC: string,
  explanation: string,
];
const ITEMS: Record<string, Item[]> = {
  "13-3": [
    [
      "A robot safety function is described only as 'stop safely.' What must be specified before evaluating its integrity?",
      "Trigger conditions, safe state, response time, operating modes and validation criteria",
      "Only the controller brand",
      "Only a PL or SIL label",
      "The robot's maximum payload alone",
      "An integrity target applies to a defined safety function. Its behavior, boundary and timing must be specified before evidence can be evaluated.",
    ],
    [
      "A component has a published SIL capability. Does that alone establish the achieved PL of an assembled machine function?",
      "No; the complete function and the selected assessment method require their own evidence",
      "Yes; PL and SIL are interchangeable labels on components",
      "Yes; the highest component rating determines every function",
      "Only the component's price matters",
      "Component capability is an input to a system-level argument, not a substitute for architecture, integration and validation of the function.",
    ],
    [
      "A safety function's sensor and logic each meet their individual requirements, but total response exceeds the hazard analysis budget. What is the result?",
      "The complete function fails its specified timing requirement",
      "Individual component passes automatically override the total",
      "Average response time is enough regardless of the requirement",
      "The timing budget can be omitted after installation",
      "System response includes the full chain. Validate it against the task-specific requirement, including defined worst-case contributions.",
    ],
  ],
  "13-4": [
    [
      "A robot model is marketed as collaborative. What determines whether a particular shared-workspace application is acceptably controlled?",
      "The task, tooling, workpiece, hazards, protective functions and validated application risk assessment",
      "The marketing label alone",
      "Only robot color",
      "A simulation video without the actual task",
      "Collaboration is an application property. The end effector, workpiece and operating conditions can introduce hazards absent from the bare arm.",
    ],
    [
      "A speed-and-separation strategy loses a reliable human-position signal. What should the specified response address?",
      "A defined protective response to loss of the information needed to maintain separation",
      "Continue indefinitely with the last position",
      "Assume the workspace is empty",
      "Disable diagnostic reporting",
      "A protective strategy must define its behavior when required sensing is invalid. Stale position is not proof of safe separation.",
    ],
    [
      "Hand-guiding is enabled, but an unexpected automatic restart can occur after release. Which requirement needs attention?",
      "Mode transitions and restart authorization must prevent unintended motion",
      "Only the handle's paint color",
      "A faster automatic cycle",
      "Removing all mode indicators",
      "Transitions between manual guidance and automatic motion are part of the hazard analysis and control design, not just steady-state motion.",
    ],
    [
      "Why can a sharp workpiece invalidate an otherwise plausible power-and-force-limiting concept?",
      "Contact geometry and the task's hazards can make force limits alone an insufficient risk reduction",
      "Robot speed is the only relevant factor",
      "A collaborative label removes tooling hazards",
      "A smaller workpiece always eliminates risk",
      "Contact outcome depends on geometry and exposure as well as force. The complete application requires task-specific assessment.",
    ],
  ],
  "13-5": [
    [
      "Two contact tests report the same force but different contact areas. Which additional quantity can differ substantially?",
      "Contact pressure",
      "The identity of the robot manufacturer",
      "The force unit itself",
      "The measured force must be different by definition",
      "Pressure depends on force and contact area. A force value alone cannot characterize every contact condition.",
    ],
    [
      "A force-measurement instrument has no current calibration evidence. What should the test report state?",
      "The measurement evidence is not yet adequate for the intended validation decision",
      "Calibration is unnecessary if the number looks reasonable",
      "Average more untraceable readings and declare approval",
      "Replace calibration with a screenshot",
      "Traceability, uncertainty and the instrument's suitability are part of measurement evidence. Repetition does not repair an unknown calibration state.",
    ],
    [
      "A report tests one approach direction but the task allows several contact geometries. What is missing?",
      "A justified coverage of relevant task/contact scenarios, including credible adverse cases",
      "Only a larger font for the passing value",
      "A universal approval for all directions",
      "A claim that all contacts are identical",
      "Validation coverage must follow the actual application conditions. One favorable contact is not representative of every geometry.",
    ],
    [
      "A measured value is close to an acceptance boundary. What must the decision consider?",
      "The applicable criterion, measurement uncertainty and documented decision rule",
      "Only the rounded display value",
      "The desired pass result",
      "An unrelated standard's threshold",
      "Acceptance is not just comparing rounded numbers. The criterion's scope, uncertainty and decision rule determine what the evidence supports.",
    ],
  ],
  "13-6": [
    [
      "A ROS 2 subscriber receives no messages despite matching topic names. What should be checked before changing robot motion code?",
      "Message types, discovery/network conditions and offered/requested QoS compatibility",
      "Only the topic label",
      "Whether both source files have equal length",
      "Assume every publisher/subscriber QoS pair is compatible",
      "Matching names are not sufficient for communication. Type, discovery and QoS policies are part of the communication contract.",
    ],
    [
      "A motion goal was planned in a sensor frame that has since moved. What must be checked before executing the plan?",
      "Transform timestamps, frame consistency and whether replanning is required",
      "Only whether the goal has three coordinates",
      "Treat every frame as the world frame",
      "Delete frame identifiers from messages",
      "Coordinates have meaning relative to frames and time. A stale transform can invalidate an otherwise numerically valid goal.",
    ],
    [
      "A ROS 2 simulation completes a pick-and-place cycle. What has it not established by itself?",
      "Safety and performance of the corresponding physical cell",
      "That the simulated control sequence ran",
      "That the tested model reached the simulated goal",
      "That the recorded simulation log exists",
      "Simulation evidence is bounded by its models and tested conditions. Physical validation and application safety require separate evidence.",
    ],
    [
      "A lifecycle-managed node is not active but receives a motion request. What should its contract specify?",
      "Reject or defer the request without unintended actuation and report the state",
      "Execute regardless of lifecycle state",
      "Silently claim completion",
      "Change the request into a different goal",
      "Lifecycle state is part of the node's operational contract. State transitions and invalid-state requests need explicit behavior.",
    ],
  ],
  "13-7": [
    [
      "An engineering laptop can write robot programs from an office network. What review is needed?",
      "Required communication paths, authentication/authorization, segmentation and controlled change procedures",
      "Only whether the laptop can ping the robot",
      "Open every port to avoid support problems",
      "Share one permanent administrator password",
      "Connectivity should be justified by purpose and constrained by access and change controls. Reachability alone is not an acceptable trust model.",
    ],
    [
      "A robot program update is authentic but unreviewed for the current cell tooling. What remains necessary?",
      "Application change review and relevant safety/function validation",
      "Nothing: cryptographic authenticity proves task safety",
      "Only renaming the file",
      "Running at maximum speed to test quickly",
      "Authenticity identifies authorized bytes; it does not establish suitability for the changed physical application.",
    ],
    [
      "An OT security test might interrupt robot communications. How should it be arranged?",
      "Within an authorized plan and safe test environment with operational impact controls",
      "Run an unannounced scan during production motion",
      "Assume availability is irrelevant",
      "Disable safety functions to simplify the test",
      "Security testing must respect the operational and safety constraints of the environment. Use approved scope and controlled conditions.",
    ],
    [
      "What should a robot-cell recovery exercise verify beyond restoring a network connection?",
      "Trusted program/configuration state, access controls and a controlled return to operation",
      "Only a green Ethernet link light",
      "Automatic restart before state checks",
      "Restoring any available unverified backup",
      "Recovery must reestablish a known authorized state and appropriate operational checks, not merely connectivity.",
    ],
  ],
  "13-8": [
    [
      "A risk-assessment worksheet lists hazards but no tasks or operating modes. Why is it incomplete?",
      "Exposure and controls depend on the actual task, mode and people involved",
      "Hazard words alone fully specify every scenario",
      "Modes matter only to marketing",
      "The number of rows proves completeness",
      "A traceable assessment connects a hazard to a concrete use, exposure, control and validation case.",
    ],
    [
      "Which entry makes a residual-risk decision reviewable?",
      "The remaining scenario, supporting evidence, limitations and responsible review decision",
      "Only the word safe",
      "An unexplained green cell",
      "The total number of simulated cycles",
      "Residual-risk decisions need an explicit rationale and scope. Neither a label nor a simulation count replaces that record.",
    ],
    [
      "A safety case references a test file whose version differs from the installed program. What should happen?",
      "Reconcile configuration identity and determine which evidence must be repeated",
      "Assume filenames prove byte identity",
      "Delete the version information",
      "Reuse the result regardless of changes",
      "Evidence must be traceable to the evaluated configuration. Changes can invalidate assumptions and require targeted revalidation.",
    ],
    [
      "Which statement correctly describes a Dura educational risk-assessment package?",
      "A learning artifact that requires qualified application-specific review before any physical use",
      "A universal machine safety approval",
      "A replacement for commissioning tests",
      "Permission to bypass a cell's protective controls",
      "Educational artifacts demonstrate a learning process within their stated scope. They do not authorize physical operation or replace professional validation.",
    ],
  ],
  "13-9": [
    [
      "For a planar two-link arm, why can the same reachable tool position have multiple joint solutions?",
      "Different joint configurations can place the endpoint at the same coordinates",
      "Forward kinematics is random",
      "Joint angles have no effect on position",
      "Every reachable point has exactly one solution",
      "Inverse kinematics can have multiple branches, such as elbow-up and elbow-down. Limits, collisions and task constraints help select a solution.",
    ],
    [
      "A Jacobian is near singular at the selected configuration. What practical issue should planning consider?",
      "Small Cartesian requests may demand large or poorly conditioned joint changes",
      "Every requested velocity becomes easier",
      "Singularities remove joint limits",
      "The transform matrix can be ignored",
      "Near-singular kinematics can amplify joint-rate requirements and sensitivity. A planner must respect conditioning and motion constraints.",
    ],
    [
      "A planner outputs a collision-free geometric path. What additional checks are needed for a usable trajectory?",
      "Timing plus velocity, acceleration and other applicable execution constraints",
      "Only the path's color",
      "None: geometry determines every dynamic property",
      "Delete timestamps to make it faster",
      "A path is geometry; a trajectory includes time. Execution feasibility requires the relevant dynamic and controller limits.",
    ],
  ],
  "14-5": [
    [
      "A team changes three process settings before collecting baseline data. Which DMAIC problem does this create?",
      "The original performance and the effect of individual changes cannot be cleanly distinguished",
      "More changes automatically improve causal evidence",
      "Baseline measurements are never needed",
      "The control phase has already been completed",
      "Baseline and measurement planning make improvement claims interpretable. Simultaneous uncontrolled changes confound attribution.",
    ],
    [
      "A process is statistically stable but routinely outside customer tolerances. What follows?",
      "Stability alone does not establish capability to meet requirements",
      "Stable always means capable",
      "Customer limits must equal control limits",
      "Remove all out-of-tolerance measurements",
      "Control limits describe process behavior; specification limits express requirements. A stable process can still be incapable.",
    ],
    [
      "An improvement reduces defects during a pilot. What belongs in the Control phase?",
      "A monitored control plan, ownership and response when performance drifts",
      "Stop measuring after the first good result",
      "Keep only the best pilot samples",
      "Replace requirements with the pilot average",
      "Sustaining an improvement requires operating controls and a response plan, not just a one-time pilot success.",
    ],
  ],
  "14-6": [
    [
      "A drawing defines a datum reference frame. What should a measurement plan preserve?",
      "The specified datum establishment and feature evaluation sequence",
      "Any convenient fixture orientation without justification",
      "Only the drawing's page size",
      "The CAD screen's current camera angle",
      "Datum references define how geometric requirements are interpreted. Measurement setup must implement the specified reference, not a convenient visual orientation.",
    ],
    [
      "Why must a positional tolerance be interpreted together with its modifiers and datum references?",
      "They affect the allowed variation and the conditions under which it is evaluated",
      "The diameter symbol alone contains every requirement",
      "Modifiers are decorative",
      "Datums never affect acceptance",
      "The feature-control frame is a combined requirement. Reading one number in isolation can produce an incorrect decision.",
    ],
    [
      "A worst-case stack has three independent dimensions each allowed ±0.1 mm. What is the worst-case signed sum tolerance?",
      "±0.3 mm",
      "±0.1 mm",
      "Exactly zero",
      "±0.01 mm",
      "For the stated worst-case additive stack, extremes can align, so absolute tolerances add. Statistical methods require additional justified assumptions.",
    ],
    [
      "A team uses root-sum-square stack-up without examining process distributions or dependence. What is missing?",
      "Evidence supporting the statistical assumptions and the chosen risk criterion",
      "Only a prettier chart",
      "Nothing: RSS is always the worst case",
      "A larger nominal dimension",
      "Statistical stack-up is conditional on assumptions about variation and dependence; it is not interchangeable with guaranteed worst-case bounds.",
    ],
    [
      "A CMM program samples only a few surface points. What should its validation address?",
      "Whether sampling, fitting, datum construction and uncertainty support the specified feature decision",
      "Only that the probe touched the part",
      "A successful program launch proves the measurement",
      "More decimal places guarantee accuracy",
      "The measurement strategy and uncertainty determine what the sampled data establish about the feature.",
    ],
    [
      "The drawing and an uncontrolled spreadsheet disagree about a tolerance. What should the operator do?",
      "Resolve the discrepancy through the controlled product-definition/change process before acceptance",
      "Choose whichever tolerance passes the part",
      "Average the two tolerances",
      "Assume the newer file timestamp establishes authority",
      "Product-definition authority follows the applicable controlled documentation and contract, not an arbitrary preference or file timestamp.",
    ],
  ],
  "14-7": [
    [
      "A model and drawing are delivered together with a defined precedence rule. Which artifact is authoritative?",
      "Whichever source the controlled delivery/contract assigns for the disputed information",
      "The 3D model automatically overrides every drawing",
      "The drawing always overrides every model",
      "The largest file",
      "Model-based definition does not establish universal contractual precedence. The controlled package must define its authoritative information.",
    ],
    [
      "A shop-floor view is derived from an authoritative model. Does creating that view inherently defeat model-based definition?",
      "No; derived views can be used under controlled identity, revision and precedence rules",
      "Yes; every 2D view is forbidden",
      "Yes; viewing geometry changes its authority",
      "Only if the view is printed in color",
      "Derived representations can support manufacturing while the authoritative definition and change control remain explicit.",
    ],
    [
      "A neutral-format export looks correct on screen. What additional check is needed before relying on its PMI?",
      "Verify required semantic information, associations, units and revision identity survived exchange",
      "Only compare file sizes",
      "Assume all visible text is machine-readable PMI",
      "Delete the native source",
      "Visual similarity does not prove semantic fidelity. Validate the information needed by the receiving process.",
    ],
    [
      "A supplier receives a model with missing units and revision metadata. What is the appropriate response?",
      "Request a controlled complete package before manufacturing decisions",
      "Infer units from how large the part looks",
      "Use the supplier's default CAD units silently",
      "Treat any emailed file as released",
      "Units and configuration identity are part of usable product definition. Guessing them can change the manufactured result.",
    ],
    [
      "What should a model-based change review compare?",
      "Changed geometry/PMI, downstream implications and the released package's revision linkage",
      "Only the thumbnail image",
      "Only the designer's name",
      "Only whether the file opens",
      "A change can affect inspection, tooling and process plans even when a viewer opens the file successfully.",
    ],
  ],
  "14-8": [
    [
      "An inspector remembers a solder-fill percentage from another product. What determines the applicable criterion?",
      "The invoked revision, product class, connection type and contractual acceptance requirements",
      "Any remembered percentage",
      "The newest social-media summary",
      "The operator's preferred class",
      "Acceptance criteria have scope. Do not transplant a numeric rule between revisions, connection types or contracts.",
    ],
    [
      "A product's class is not defined in the work package. What should inspection do?",
      "Resolve the applicable product classification and requirements through the authorized process",
      "Choose the easiest class",
      "Assume Class 3 for every assembly without checking",
      "Infer class from board color",
      "The classification and invoked criteria must be established, not chosen to achieve a convenient result.",
    ],
    [
      "Magnification reveals an ambiguous condition near a criterion boundary. What should be recorded?",
      "The observed condition, measurement/inspection setup, applicable criterion and escalation decision",
      "Only pass because the board powers on",
      "An unrelated example photo",
      "A rounded value chosen to pass",
      "Functional operation is not a substitute for the invoked workmanship criterion. Ambiguity needs traceable evidence and the defined escalation path.",
    ],
    [
      "A visual acceptance guide is being used as the sole solder-process specification. What distinction is missing?",
      "Acceptance criteria and process/material requirements serve different purposes",
      "Visual inspection automatically defines every manufacturing parameter",
      "All manufacturing standards are interchangeable",
      "Process controls matter only after shipment",
      "A product can require both workmanship acceptance and separately invoked process/material controls. One document should not be assumed to replace the other.",
    ],
    [
      "A photo library lacks the cited standard revision and connection category. What limits its use?",
      "It cannot reliably establish the applicable acceptance decision without that context",
      "Photographs always override the written criterion",
      "Any similar-looking joint has the same rule",
      "A high-resolution image establishes contractual scope",
      "Images can support inspection training, but applicability depends on the controlled criterion and the actual assembly context.",
    ],
  ],
  "14-9": [
    [
      "A damaged assembly needs a modification beyond restoring the original requirement. What must be distinguished?",
      "Rework, repair and modification under the applicable authorization and procedures",
      "All changes are automatically authorized rework",
      "Only the soldering iron temperature matters",
      "The technician can silently redefine acceptance",
      "The purpose and effect of the intervention determine its procedure and approval requirements. Restoring compliance and accepting a changed condition are not identical.",
    ],
    [
      "A rework procedure changes heating equipment from its validated setup. What is required before relying on the old qualification?",
      "Review and validate the changed thermal/process conditions as applicable",
      "Assume identical knob numbers mean identical thermal exposure",
      "Skip monitoring because the operator is experienced",
      "Increase heat until the task is faster",
      "Equipment changes can alter the thermal profile. Qualification evidence must match the process actually used.",
    ],
    [
      "A board survives one rework cycle. Does that prove unlimited repeated cycles are acceptable?",
      "No; cumulative exposure and the applicable process limits require evaluation",
      "Yes; the first successful cycle proves all future cycles",
      "Yes; temperature has no cumulative effect",
      "Only the board's color determines cycle limits",
      "Repeated thermal and mechanical exposure can affect reliability. Use the applicable limits and traceable process history.",
    ],
    [
      "What should a controlled rework record identify?",
      "Assembly identity, condition, authorized procedure, operator/process evidence and post-work inspection",
      "Only a verbal statement that it was fixed",
      "Only the replacement part's color",
      "A generic photo of a different board",
      "Traceability connects the actual assembly and intervention to the evidence supporting its release.",
    ],
    [
      "A repair passes a visual check but its required electrical test was not run. What can the release decision claim?",
      "Only the completed checks; release must await all applicable required evidence",
      "Complete validation because one check passed",
      "Electrical tests can always be inferred from appearance",
      "The missing test is automatically waived",
      "Different checks establish different properties. An unperformed required test cannot be replaced by an unrelated passing result.",
    ],
  ],
  "14-10": [
    [
      "A manufacturing architecture labels activities with ISA-95 levels. Does that alone define secure network zones?",
      "No; security zones and conduits require their own risk-based design",
      "Yes; every level is automatically one approved firewall zone",
      "Yes; labels enforce packet filtering",
      "Network security is irrelevant to manufacturing integration",
      "Functional integration models and security segmentation solve different problems. They must be related deliberately, not treated as interchangeable.",
    ],
    [
      "A batch recipe is hard-coded to one valve address throughout its logic. Which separation could improve reuse?",
      "Separate procedural recipe intent from equipment-specific control mappings",
      "Copy the address into more recipes",
      "Remove equipment state feedback",
      "Treat recipe and equipment models as identical",
      "Separating procedure from equipment implementation supports reuse and clearer capability/constraint checks.",
    ],
    [
      "An MES asks a machine to start an operation. What must remain authoritative for immediate equipment interlocks?",
      "The specified equipment/control safety architecture, with command validation and state checks",
      "An office dashboard refresh",
      "An ERP spreadsheet alone",
      "The last successful network ping",
      "Enterprise integration does not replace equipment-level operational and protective controls. Commands must be evaluated in the actual control state.",
    ],
    [
      "Two systems exchange a production count without defining reset behavior or units. What is the integration risk?",
      "They can interpret the same number differently across batches or restarts",
      "Numeric fields are self-describing",
      "Every count is necessarily lifetime cumulative",
      "An XML wrapper resolves all semantics",
      "Interoperability requires definitions for identity, units, scope and lifecycle, not just a transport format.",
    ],
    [
      "A batch is paused and resumed. What should the state model make explicit?",
      "Permitted transitions, retained state and the conditions for safely resuming the procedure",
      "Every pause can restart from any arbitrary step",
      "Pause always means delete all history",
      "Resume needs no equipment-state checks",
      "State and procedural context determine valid recovery. A pause/resume label alone does not define behavior.",
    ],
  ],
  "14-11": [
    [
      "An MTConnect observation says UNAVAILABLE. How should a bridge represent it in a downstream quality-aware model?",
      "As unavailable/bad-quality data, preserving that distinction from numeric zero",
      "Convert it to zero and mark good",
      "Reuse the last value indefinitely without a stale flag",
      "Drop every metadata field",
      "Missing or invalid data is not a measured zero. Preserve quality and freshness so consumers can make appropriate decisions.",
    ],
    [
      "A bridge maps machine observations into OPC UA nodes. What should be stable across reconnects?",
      "Source identity to node identity mapping, with explicit timestamps and quality",
      "A new random node identifier for each sample",
      "Only the UI row order",
      "The count of log lines",
      "Stable identity allows consumers to recognize the same signal while timestamps and quality describe each observation.",
    ],
    [
      "A sequence gap occurs in a sampled machine-data stream. What should the bridge do?",
      "Mark the discontinuity and use the source's recovery/resynchronization policy",
      "Pretend every intermediate sample was received",
      "Interpolate all missing alarms as normal",
      "Reset the sequence counter silently",
      "A gap is a data-quality event. Recovery and any interpolation policy must be explicit and appropriate to the signal.",
    ],
    [
      "A TSN-capable switch is installed. What still must be established for an end-to-end timing claim?",
      "The complete path's configuration, traffic schedule, synchronization and measured bounds",
      "Nothing; one component guarantees every application's deadline",
      "Only the switch's product label",
      "An average ping time on another network",
      "Deterministic behavior is a system property. Component support alone does not establish configured end-to-end guarantees.",
    ],
    [
      "A telemetry bridge successfully reads a machine observation. What should it not imply?",
      "That the same interface authorizes arbitrary machine control",
      "That a particular observation was received",
      "That the parser handled the tested payload",
      "That timestamps can be logged",
      "Observation and control have different permissions and operational implications. Do not infer write/control authority from read access.",
    ],
  ],
  "14-12": [
    [
      "A proposed conduit allows all traffic between two OT zones. What should the design justify instead?",
      "The necessary communications, directions, identities and enforcement/monitoring controls",
      "A permanent any-any rule for convenience",
      "Only assigning zone names",
      "Assuming segmentation labels block traffic",
      "A conduit is a controlled communication relationship. Its permitted flows and protections must follow the system's requirements.",
    ],
    [
      "A vendor security capability is certified for a component. What still requires system-level evaluation?",
      "Its configured use, integration, operational controls and the target system's requirements",
      "Nothing; one component certificate covers the entire plant",
      "Only the vendor logo",
      "The invoice total",
      "Component capabilities contribute to a system argument; they do not establish the deployed system's achieved security by themselves.",
    ],
    [
      "An architecture diagram combines RAMI 4.0 layers and lifecycle axes. What is a useful purpose of that model?",
      "Locate concerns and relationships so responsibilities and interfaces can be reviewed",
      "Automatically generate a compliant firewall configuration",
      "Prove every implementation requirement is met",
      "Replace all operational testing",
      "Reference architectures organize concerns. They do not themselves implement or validate the system.",
    ],
    [
      "A remote-maintenance account remains enabled permanently with shared credentials. Which control improvement is most directly relevant?",
      "Named least-privilege access with controlled activation, authentication and auditability",
      "Publish the password in a shift log",
      "Remove access logs",
      "Grant every vendor plant-wide administration",
      "Remote access should be attributable and limited to its justified purpose and duration, with a reviewed operational process.",
    ],
    [
      "What makes an OT asset inventory useful for patch/recovery planning?",
      "Current identity, versions, dependencies, criticality and responsible ownership",
      "Only a device count",
      "Only physical paint colors",
      "An old unmaintained spreadsheet with no versions",
      "Planning depends on what is deployed and how it supports operations. An inventory must remain actionable and maintained.",
    ],
  ],
  "14-13": [
    [
      "A CAM toolpath is collision-free in simulation but uses the wrong work offset on the machine. What has simulation not established?",
      "Correct setup correspondence between the simulated and actual coordinate systems",
      "That the simulated path existed",
      "That the file has coordinates",
      "That the software displayed a preview",
      "Toolpath validation depends on matching stock, tooling, fixtures and offsets to the actual setup. Simulation assumptions must be checked.",
    ],
    [
      "A program changes units without converting coordinate values. What is the likely defect?",
      "The commanded dimensions change meaning",
      "Only comments are affected",
      "Machine controllers always infer intended units",
      "Units matter only in drawings",
      "Coordinates and feeds are interpreted under active units and modes. Unit changes require consistent values and validation.",
    ],
    [
      "A postprocessor targets a different controller dialect. What must be checked before execution?",
      "Controller-specific cycles, modes, limits and output semantics against the intended machine",
      "Only the output filename extension",
      "Assume all G-code dialects are identical",
      "Delete unsupported codes and run immediately",
      "A toolpath's postprocessed representation is machine/controller-specific. Unsupported or differently interpreted commands require a controlled resolution.",
    ],
    [
      "A tool-length offset is wrong even though nominal part geometry is correct. What can be affected?",
      "The physical tool position relative to the workpiece and fixture",
      "Only the CAD thumbnail",
      "Nothing outside the tool library description",
      "Only the program's title",
      "Geometry is executed through machine setup and offsets. Offset errors can change actual motion and require setup verification.",
    ],
    [
      "Why include fixture and stock geometry in a machining simulation?",
      "To test interactions beyond the finished part surface, including non-cutting moves",
      "Finished-part geometry proves every move safe",
      "Fixtures never affect tool motion",
      "Only cutting endpoints matter",
      "Travel and approach/retract moves can interact with stock and fixtures. A finished surface alone is an incomplete simulation scene.",
    ],
    [
      "A feed calculation uses tooth count and spindle speed. Which additional value is required for the simple feed-per-tooth model?",
      "Specified feed per tooth",
      "Only the program line number",
      "The machine's paint color",
      "The file creation date",
      "For the stated model, feed rate is spindle speed × tooth count × feed per tooth. Appropriate cutting values still depend on the validated tool/material/process context.",
    ],
    [
      "A change to tool diameter invalidates a previous simulation. What should the change process do?",
      "Regenerate or revalidate affected paths, clearances and compensation assumptions",
      "Reuse the old result solely because the part file is unchanged",
      "Remove tool information from the report",
      "Assume compensation always fixes every geometry change",
      "Tool geometry is an input to cutting and clearance behavior. A changed input can invalidate the earlier evidence.",
    ],
    [
      "A machining program relies on modal state inherited from a previous program. What improves reproducibility?",
      "Establish and verify the required initial modes and setup explicitly",
      "Assume the machine always starts in the desired state",
      "Document only the final line",
      "Avoid all setup records",
      "Modal state affects command interpretation. A controlled initial state makes the intended execution reproducible.",
    ],
    [
      "An educational G-code preview succeeds. Which claim is still unsupported?",
      "Approval to run that program on an unspecified physical machine",
      "The preview processed the tested fixture",
      "The displayed path followed the modeled commands",
      "The simulation generated a log",
      "A preview is bounded by its model and inputs. Physical operation requires the machine's authorized setup, verification and operating procedures.",
    ],
    [
      "A first-article measurement shows a systematic offset from nominal. What should the team investigate before changing the drawing?",
      "Setup, offsets, tool/process effects and measurement method against the controlled requirements",
      "Relax the tolerance to match the first part",
      "Delete nonconforming measurements",
      "Assume the nominal definition must be wrong",
      "A discrepancy needs a traceable cause analysis. Requirements should not be silently changed to fit observed output.",
    ],
  ],
  "14-14": [
    [
      "A gauge displays micrometre resolution. Does that establish micrometre measurement uncertainty?",
      "No; resolution is one contributor and does not establish the complete uncertainty",
      "Yes; displayed digits prove accuracy",
      "Yes; calibration is then unnecessary",
      "Only screen brightness matters",
      "Resolution, accuracy, repeatability and uncertainty are distinct. The measurement process needs its own uncertainty evaluation.",
    ],
    [
      "Repeated measurements are tightly grouped but shifted from a reference value. Which distinction does this illustrate?",
      "Good repeatability does not eliminate bias",
      "Repeatability and bias are the same quantity",
      "More repetition necessarily removes every bias",
      "The reference value must be discarded",
      "A process can be precise while systematically offset. Repetition characterizes spread, not all systematic effects.",
    ],
    [
      "A part measures near the specification limit. Which rule should govern acceptance?",
      "The agreed decision rule using the applicable requirement and measurement uncertainty",
      "Always accept values after rounding toward nominal",
      "Choose whichever rule gives a pass",
      "Ignore uncertainty because a number is displayed",
      "A documented decision rule connects measurement evidence to conformity decisions, including uncertainty where applicable.",
    ],
    [
      "Two lots of the same part number use different material heats. What must traceability preserve?",
      "Which delivered/processed items came from each relevant lot or heat",
      "Only the common part number",
      "Only the supplier's logo",
      "A single average manufacturing date",
      "Traceability supports containment and investigation by linking actual items to relevant production/material histories.",
    ],
    [
      "A supplier certificate references a different revision than the purchase requirement. What should receiving inspection do?",
      "Resolve applicability and obtain the required evidence before claiming conformance",
      "Accept because any certificate is sufficient",
      "Edit the certificate revision locally",
      "Ignore the purchase requirement",
      "Evidence must correspond to the invoked requirements and actual supplied product. A certificate title alone is insufficient.",
    ],
    [
      "A measurement system study uses one operator on one part repeatedly. What limitation should be acknowledged?",
      "It does not establish variation across operators and the relevant part range",
      "It proves all reproducibility conditions",
      "It measures every supplier process",
      "It eliminates the need for a study plan",
      "The sampled design determines which variation sources can be estimated. A narrow repeatability sample cannot establish broader reproducibility.",
    ],
    [
      "Temperature changes a dimensional measurement. What belongs in the measurement plan?",
      "Applicable reference/environment conditions, stabilization and compensation/uncertainty treatment",
      "Ignore temperature for every material",
      "Change the tolerance after each reading",
      "Use the warmest reading automatically",
      "Environment can affect both part and instrument. The method must control or account for relevant influences.",
    ],
    [
      "A suspected bad lot has already been split among several shipments. What makes targeted containment possible?",
      "Maintained genealogy linking lots, transformations and shipments",
      "Only the total annual production count",
      "A photograph of one carton",
      "Deleting historical lot identifiers",
      "Containment depends on knowing which affected material went where, including transformations and splits.",
    ],
    [
      "A supply-chain dashboard reports zero late shipments but excludes missing delivery timestamps. What is wrong with the metric?",
      "Missing data can hide lateness; completeness and denominator rules must be reported",
      "Missing timestamps prove on-time delivery",
      "Excluding all uncertain rows always gives a complete result",
      "Only chart color matters",
      "A metric must disclose how missing records affect its population. Unknown delivery time is not evidence of on-time delivery.",
    ],
    [
      "A calibration result is valid for a gauge, but the production fixture applies it differently. What needs evaluation?",
      "The complete in-use measurement method, including fixture effects and uncertainty",
      "Nothing beyond the gauge serial number",
      "Only whether the fixture is new",
      "The invoice price of the gauge",
      "Calibration of an instrument does not characterize every application. The measurement system includes its setup and use.",
    ],
  ],
  "10-9": [
    [
      "A sensor draws 20 mA for 10 ms and 0.02 mA for the remaining 990 ms of each second. Ignoring transitions, what is its average current?",
      "0.2198 mA",
      "20 mA",
      "0.02 mA",
      "10.01 mA",
      "Weight each current by its time fraction: 20 × 0.01 + 0.02 × 0.99 = 0.2198 mA. Include transition energy before predicting battery life.",
    ],
    [
      "An interrupt can arrive between checking a work flag and entering sleep. What must the idle design establish?",
      "An atomic check-and-sleep protocol appropriate to the MCU, so pending work cannot be missed",
      "A longer sleep interval",
      "A volatile flag alone makes the whole sequence atomic",
      "Disable every wake source permanently",
      "A shared flag does not remove the race between the check and sleep. Use the target's documented interrupt and sleep protocol and test the arrival boundary.",
    ],
    [
      "A lower-power mode saves 5 mW while sleeping but each entry/exit costs 1 mJ. What sleep duration breaks even against staying awake?",
      "0.2 seconds",
      "5 seconds",
      "0.005 seconds",
      "Any positive duration",
      "Energy saved is power difference multiplied by time: 0.001 J / 0.005 W = 0.2 s. Latency and wake constraints must also be satisfied.",
    ],
  ],
  "10-10": [
    [
      "A signed firmware image has a valid signature but an older security version than the installed image. What should a rollback-protected updater do?",
      "Reject it unless an explicitly authorized recovery policy permits that version",
      "Install it because signatures prove freshness",
      "Ignore its version if the download used TLS",
      "Erase the version counter before validation",
      "A signature establishes authorization of particular bytes, not that they are the newest permitted version. Rollback policy is a separate check.",
    ],
    [
      "Power fails while writing the inactive slot of an A/B update. Which property preserves bootability?",
      "The confirmed slot remains intact and boot selection changes only after the new slot is verified",
      "Write the boot-selection flag before copying the image",
      "Overwrite the running slot first",
      "Assume flash writes cannot be interrupted",
      "An inactive-slot update must not destroy the confirmed image. Boot metadata and image validation need explicit power-loss behavior.",
    ],
    [
      "A trial firmware starts but repeatedly resets before confirming healthy startup. What should the boot policy do after its bounded trial budget?",
      "Return to the last confirmed compatible image and record the failure",
      "Mark the trial image healthy after any reset",
      "Retry the bad image forever",
      "Trust the transport checksum as a health check",
      "Installation integrity and successful operation are different. A bounded trial and health confirmation make recovery possible.",
    ],
    [
      "Which fault-injection test most directly checks OTA metadata recovery?",
      "Interrupt power at each erase/write/commit boundary and verify a permitted image still boots",
      "Only test a complete download on stable power",
      "Change the release-note title",
      "Benchmark a single successful reboot",
      "Recovery depends on interrupted intermediate states. Test the boundaries of both image programming and metadata commitment.",
    ],
  ],
  "11-7": [
    [
      "A powered-down producer drives a live consumer. What should a power-aware test check before shutting the producer off?",
      "Isolation clamps the crossing to the specified safe value in the specified sequence",
      "The consumer samples an arbitrary retained value",
      "Clock gating alone guarantees output isolation",
      "All X values are globally suppressed",
      "Isolation behavior and its sequencing are explicit power-intent requirements; clock gating does not replace isolation.",
    ],
    [
      "A retained register restores correctly, but a non-retained register keeps its old simulation value after power cycling. What is the likely verification gap?",
      "The test has not checked corruption/reset behavior for non-retained state",
      "Retention should apply to every register automatically",
      "A passing retained register proves all power states",
      "The test should disable power-aware simulation",
      "A power-cycle test must distinguish retained state from state that must be reinitialized. Ordinary simulation values can mask missing power-aware behavior.",
    ],
    [
      "Two voltage domains exchange signals. Which evidence is needed beyond merely instantiating a level shifter?",
      "Checks that each required crossing uses the correct conversion and that power-state combinations are legal",
      "A screenshot of the cell name",
      "A longer clock period guarantees voltage compatibility",
      "Removing the crossing from coverage",
      "Topology, direction, power states and implementation intent all matter; a cell instance alone is not coverage evidence.",
    ],
    [
      "A power-state transition test passes only when control signals change simultaneously. What should be added?",
      "Tests of the specified ordering, delays and prohibited intermediate combinations",
      "Assume physical control signals switch simultaneously",
      "Ignore all intermediate states",
      "Increase random seeds without defining sequencing checks",
      "Real control transitions have ordering and latency. Assertions should evaluate the intended legal sequence and reject unsafe intermediate states.",
    ],
    [
      "What makes a low-power coverage exclusion reviewable?",
      "A specific unreachable state or transition, its design justification, and reviewer approval",
      "An exclusion for every failing bin",
      "An unexplained global waiver",
      "A high overall percentage",
      "Coverage exclusions change the model of what was tested. Their scope and rationale must be explicit, rather than hiding untested behavior.",
    ],
  ],
  "11-8": [
    [
      "A UART receiver scoreboard compares only the number of received bytes. Which error can it miss?",
      "Correct byte count with incorrect byte values or order",
      "Any dropped byte",
      "Every extra byte",
      "A completely empty stream",
      "Counts alone do not establish payload correctness. Compare expected values, ordering and status against an independent reference.",
    ],
    [
      "Which UART reset test exercises behavior that a startup-only reset misses?",
      "Assert reset during a frame, then verify recovery on a subsequent complete frame",
      "Reset only before clocks start",
      "Read the reset signal name",
      "Remove all traffic during the entire test",
      "Mid-frame reset exposes state-machine recovery and stale partial-byte behavior. The post-reset expected behavior must be specified.",
    ],
    [
      "A test reuses the DUT's sampling algorithm verbatim as its reference model. What risk does that create?",
      "The same conceptual error can exist in both DUT and checker",
      "It guarantees independence",
      "It eliminates the need for assertions",
      "It proves all baud rates",
      "A useful reference is independently derived from the protocol contract. Duplicating the same algorithm can reproduce the same bug.",
    ],
    [
      "A UART test has 100% of its defined coverage bins. What may it legitimately conclude?",
      "All bins in that particular reviewed model were hit",
      "The UART is correct for every possible input",
      "No implementation bugs remain",
      "Physical timing is validated",
      "Coverage describes a model and sampled executions. It does not prove exhaustive correctness or physical implementation properties.",
    ],
    [
      "The UART stop bit is low at the expected sampling point. What should the test compare?",
      "The specified framing-error behavior and whether invalid payload is accepted or rejected",
      "Only whether the clock is running",
      "The next valid frame while ignoring the bad one",
      "An assumed universal behavior for every UART IP",
      "UART IPs can differ in reporting and recovery behavior. The checker must enforce the selected DUT contract for framing errors.",
    ],
    [
      "A driver waits forever for ready. What belongs in the verification environment?",
      "A bounded timeout that reports protocol state and fails the test",
      "An infinite wait with no diagnostics",
      "A larger simulation seed",
      "An unconditional success after the wait starts",
      "A hung handshake is a meaningful failure. A deadline prevents silent stalled simulations and preserves useful debugging evidence.",
    ],
    [
      "Which change tests the sensitivity of a UART scoreboard?",
      "Deliberately corrupt one expected or driven bit and require a failing verdict",
      "Delete all scoreboard comparisons",
      "Run only with an empty expected queue",
      "Count the number of log messages",
      "A negative control checks that the test can detect a known defect. A checker that never fails is not useful evidence.",
    ],
    [
      "What is a defensible way to close an uncovered FIFO-overrun scenario?",
      "Drive traffic that exceeds the specified service capacity and check the documented overrun behavior",
      "Rename the uncovered bin",
      "Lower the coverage target until it passes",
      "Treat normal traffic as overrun evidence",
      "Exercise the condition and compare the specified status/data-loss behavior. If unreachable, document and review that justification.",
    ],
    [
      "A waveform differs only on runs with a different random seed. What should a failure report preserve?",
      "Seed, tool/configuration versions, stimulus, expected/actual results and relevant waveform",
      "Only a screenshot of the final score",
      "The source filename alone",
      "A statement that randomness caused it",
      "Reproduction requires enough information to reconstruct the failing execution and the contract it violated.",
    ],
  ],
  "11-9": [
    [
      "A one-source-clock pulse crosses into a much slower clock domain. Why can a two-flop level synchronizer still lose the event?",
      "The pulse may end before any destination sampling edge observes it",
      "Two flops guarantee every pulse is observed",
      "Metastability makes the pulse permanently high",
      "The destination must run at exactly the same frequency",
      "A level synchronizer reduces metastability propagation; it does not guarantee event capture. Use an appropriate handshake, toggle or stretched pulse protocol.",
    ],
    [
      "Eight related status bits cross separately through two-flop synchronizers. What property is not guaranteed?",
      "The destination observes a coherent snapshot of all eight bits",
      "Each wire exists in the netlist",
      "The source can change a bit",
      "The destination has a clock",
      "Independent bits may settle on different cycles. A coherent multi-bit transfer needs a protocol or encoding designed for that purpose.",
    ],
    [
      "Why is reset deassertion often synchronized separately in each clock domain?",
      "Release must meet each domain's recovery/removal and sequencing requirements",
      "Reset assertion and release have no timing requirements",
      "A single synchronizer automatically covers unrelated clocks",
      "Reset permanently removes all CDC risks",
      "Reset-domain crossing has its own timing and ordering concerns. Verify the chosen asynchronous assertion/synchronous release scheme per domain.",
    ],
    [
      "A CDC waiver refers to a signal that was later changed from Gray-coded to arbitrary binary. What should happen?",
      "Invalidate or re-review the waiver because its safety argument changed",
      "Keep the waiver because the signal name is unchanged",
      "Suppress the entire CDC report",
      "Assume any multi-bit counter crosses safely",
      "A waiver rests on design assumptions, not a permanent signal-name exemption. Changing the encoding changes the crossing argument.",
    ],
  ],
  "11-10": [
    [
      "A test spends most of its time making fine-grained host calls to an emulator. Which change addresses the likely bottleneck?",
      "Batch transactions and move appropriate time-critical work into synthesizable transactors",
      "Add more host logging per cycle",
      "Assume hardware acceleration eliminates communication overhead",
      "Disable result checking",
      "Host/emulator round trips can dominate runtime. Coarse transactions and hardware-side transactors reduce that overhead without removing checks.",
    ],
    [
      "An emulation result differs from simulation. What should be compared first?",
      "Stimulus, timing abstractions, reset and unsupported/non-synthesizable behavior",
      "Only the machine's hostname",
      "The final score without inputs",
      "Assume the faster platform is always right",
      "Platforms can model timing and language features differently. Establish equivalent contracts and inputs before attributing the discrepancy.",
    ],
    [
      "Why must a verification component be reviewed before moving it into emulated hardware?",
      "Its constructs and timing model must be synthesizable and supported by the platform",
      "Every SystemVerilog class is directly synthesizable",
      "Assertions can always be deleted without losing verification value",
      "The file extension guarantees synthesis",
      "Verification languages contain host-oriented constructs. Hardware acceleration requires an explicit supported partition.",
    ],
    [
      "A software workload boots on an emulator. Which conclusion still requires separate evidence?",
      "Meeting final silicon frequency, power and physical timing requirements",
      "The observed workload reached that boot state",
      "The test produced an execution log",
      "The emulated reset sequence was exercised",
      "Emulation validates modeled functional behavior. Its clock/power characteristics do not substitute for physical implementation sign-off.",
    ],
  ],
  "12-2": [
    [
      "Prices are quoted in fixed tick units. Which representation avoids binary-floating rounding in exact price-level keys?",
      "A checked integer number of ticks",
      "An arbitrary epsilon added to every key",
      "A floating-point string rounded differently at each call",
      "NaN as a missing-price key",
      "Integer ticks encode the declared discrete price domain exactly, provided range and conversion rules are validated.",
    ],
    [
      "A comparator is used to order prices, but input validation permits NaN. What is the problem?",
      "Ordinary comparisons with NaN can violate the intended ordering contract",
      "NaN always sorts between zero and one",
      "NaN equals every other NaN",
      "NaN is automatically rejected by every container",
      "Validate domain values before ordered operations; unordered floating values cannot be treated as normal prices.",
    ],
    [
      "A numerical test compares two computed values near zero. Which comparison policy is most defensible?",
      "A documented absolute and relative tolerance derived from the computation's error budget",
      "Relative error alone with division by zero",
      "Exact equality for every approximate algorithm",
      "A tolerance chosen only after observing a failed test",
      "Near zero an absolute tolerance matters; at scale a relative term may be useful. The tolerance should follow the intended numerical accuracy.",
    ],
  ],
  "12-3": [
    [
      "Two threads update different counters that share a cache line. What experiment tests a false-sharing hypothesis?",
      "Separate the counters into independently aligned storage and compare contention metrics under the same workload",
      "Change both thread counts and data sizes simultaneously",
      "Remove synchronization required for correctness",
      "Assume different variables cannot share cache traffic",
      "Control the workload and change the suspected shared cache-line placement, then measure. Alignment and actual allocation layout both matter.",
    ],
    [
      "An optimization improves a microbenchmark with a tiny data set but slows the representative workload. Which result should guide deployment?",
      "The representative workload with correctness and distribution measurements",
      "Only the fastest single microbenchmark sample",
      "The smaller source file",
      "The compiler flag name",
      "Cache behavior depends on access patterns and working-set size. A useful benchmark represents the intended workload and reports variability.",
    ],
  ],
  "12-4": [
    [
      "A pointer changes A→B→A while a thread is delayed. Why can pointer-only compare-and-swap miss an intervening change?",
      "The final address matches even though the object's history or lifetime changed",
      "CAS compares every historical value",
      "CAS always fails after any other thread runs",
      "Atomic pointers automatically preserve object lifetime",
      "This is the ABA problem: equality of the current pointer does not establish unchanged history. Versioning and safe reclamation address distinct parts of the design.",
    ],
    [
      "A reader loads a node pointer atomically while another thread removes and frees it. What is still required?",
      "A safe memory-reclamation protocol protecting the reader's use",
      "Only an atomic pointer load",
      "A volatile qualifier on the node",
      "A faster allocator",
      "Atomicity of the pointer does not keep the pointee alive. Hazard pointers, epochs or another valid lifetime protocol must cover readers.",
    ],
    [
      "A queue producer initializes payload then publishes availability. Which relationship must the consumer establish before reading that payload?",
      "The intended release/acquire synchronization or another valid happens-before relation",
      "A delay loop of arbitrary duration",
      "A relaxed availability load is always sufficient on every architecture",
      "Printing a debug message makes the data visible",
      "Publication needs a memory-ordering argument. Timing coincidences and logging do not establish the C++ happens-before contract.",
    ],
    [
      "A queue operation retries CAS indefinitely while other threads complete operations. Which progress property might hold without wait-freedom?",
      "Lock-freedom: system-wide progress without a per-thread step bound",
      "Every thread finishes within a fixed number of steps",
      "Starvation is impossible",
      "The operation uses no shared state",
      "Lock-free and wait-free are different guarantees. A lock-free algorithm may allow one thread to retry repeatedly.",
    ],
    [
      "A ring buffer's index wraps. What should a capacity test establish?",
      "Full and empty remain distinguishable and occupied slots are never overwritten",
      "Every wrapped index means empty",
      "Unsigned overflow proves queue correctness",
      "Capacity can be ignored after the first wrap",
      "Wraparound is part of the state space. Exercise boundary transitions and verify the chosen full/empty representation.",
    ],
    [
      "A concurrent data structure passes a race detector. What still needs testing or proof?",
      "Linearizability, lifetime safety, progress and the algorithm's memory-ordering argument",
      "Nothing: a race-detector pass proves every concurrent property",
      "Only comment formatting",
      "Whether all operations use the same variable names",
      "Race detectors cover particular executed violations. They do not prove higher-level semantics or all possible schedules.",
    ],
    [
      "An SPSC queue is reused by two producers without design changes. What is the appropriate conclusion?",
      "Its original single-producer correctness argument no longer applies",
      "SPSC is automatically MPMC when indexes are atomic",
      "Producer count changes only performance",
      "More producers eliminate contention",
      "Algorithms rely on stated concurrency assumptions. Supporting another producer requires a design and proof appropriate to that model.",
    ],
  ],
  "12-5": [
    [
      "A receive API reports fewer bytes than a complete application message. What should a stream parser do?",
      "Buffer the partial message and continue framing when more bytes arrive",
      "Treat every receive call as exactly one full message",
      "Discard all following bytes",
      "Read beyond the returned byte count",
      "A byte stream does not preserve application message boundaries. Framing must handle both partial and coalesced messages.",
    ],
    [
      "An asynchronous I/O request references a buffer. When can the application safely reuse it?",
      "After the API's completion/lifetime contract says the operation no longer references it",
      "Immediately after submission in every case",
      "After a fixed sleep unrelated to completion",
      "When another unrelated request completes",
      "Submission is not completion. Buffer lifetime must cover the operation's actual use and any documented zero-copy notifications.",
    ],
    [
      "A completion queue returns an error result for one operation. What is required?",
      "Associate it with the correct request and handle that operation's error without assuming success",
      "Interpret every completion as a successful full transfer",
      "Ignore the operation identifier",
      "Retry the whole application without accounting for completed work",
      "Completion means an operation reached a result, not necessarily a successful one. Partial results and failures need per-request handling.",
    ],
    [
      "A polling network loop consumes a full CPU even without traffic. What tradeoff should the deployment evaluate?",
      "Latency objectives against dedicated-core use, power, workload isolation and idle behavior",
      "Polling has no resource cost",
      "CPU utilization alone proves useful throughput",
      "Disable all capacity measurements",
      "Polling can trade resources for predictable responsiveness. It needs an explicit operating budget and representative measurements.",
    ],
    [
      "A receive burst exceeds downstream processing capacity. What must a bounded design specify?",
      "Backpressure or drop/recovery policy with observable counters",
      "An unbounded queue that grows forever",
      "Assume producers will slow down automatically",
      "Silently overwrite arbitrary messages",
      "Capacity limits require an intentional overload policy. Observability and recovery determine whether a loss is detectable and manageable.",
    ],
    [
      "A NIC and its processing thread are on different NUMA nodes. What should be measured before optimization?",
      "Memory/device locality, cross-node traffic and end-to-end latency under controlled placement",
      "Only the size of the executable",
      "Assume kernel bypass guarantees local memory",
      "Disable packet validation to reduce time",
      "Bypass does not remove hardware topology. Controlled affinity and allocation experiments expose locality costs.",
    ],
    [
      "A networking benchmark reports only mean latency. What evidence is missing for a tail-latency objective?",
      "A latency distribution including relevant percentiles, sample count and load conditions",
      "A shorter benchmark title",
      "The first successful packet only",
      "A claim that averages bound every request",
      "The mean does not bound the tail. Report distributions under specified load and account for warm-up, errors and measurement overhead.",
    ],
  ],
  "12-6": [
    [
      "A feed jumps from sequence 100 to 103. What should a stateful consumer do before treating its book as current?",
      "Detect the gap and follow the feed's defined recovery/snapshot procedure",
      "Pretend 101 and 102 contained no changes",
      "Renumber 103 as 101",
      "Publish the incomplete state as authoritative",
      "Missing state-changing events can invalidate the reconstructed book. Recovery must follow the particular feed's sequencing contract.",
    ],
    [
      "A replayed add-order event carries an order ID that is already active. What should the parser/state machine do?",
      "Apply its documented duplicate/replay policy and flag an inconsistent duplicate rather than silently inventing a second order",
      "Always double the quantity",
      "Replace any unrelated order",
      "Ignore order identity entirely",
      "Order identity is part of the state contract. Duplicate handling must be explicit and consistent with replay and recovery semantics.",
    ],
    [
      "An execution asks to remove quantity 12 from an order with quantity 10. What is the safe validation result in a strict fixture?",
      "Reject the inconsistent event without underflowing or partially mutating the book",
      "Wrap an unsigned quantity to a huge value",
      "Clamp silently and claim valid input",
      "Delete another order to make totals match",
      "Validate invariants before mutation. Silent clamping can conceal a feed gap or parser error and corrupt subsequent state.",
    ],
    [
      "A wire protocol specifies big-endian integers. What must a portable decoder avoid?",
      "Assuming host byte order and casting arbitrary byte addresses directly to native integers",
      "Reading only within the declared message length",
      "Explicit endian conversion",
      "Checking a message type before decoding",
      "Wire representation is independent of host alignment and endianness. Decode bytes with explicit bounds and conversion.",
    ],
    [
      "A log contains both local receipt time and exchange event time. Why keep their meanings separate?",
      "They measure different events and may use different clocks and synchronization assumptions",
      "They are guaranteed numerically equal",
      "Local time always proves exchange ordering",
      "One timestamp can silently replace the other",
      "Timestamp semantics and clock domains determine which latency or ordering claims are justified.",
    ],
    [
      "A reconnect produces events already represented in a snapshot. What must the recovery design define?",
      "A sequence boundary and rules for which events to discard or apply after the snapshot",
      "Apply every event twice to be safe",
      "Ignore snapshot sequence metadata",
      "Merge snapshots by averaging prices",
      "A consistent snapshot-plus-log reconstruction requires a known boundary. Otherwise duplicate or missing changes can corrupt the state.",
    ],
    [
      "Why should an educational ITCH/OUCH parser fixture name the exact supported message subset?",
      "Message layouts and session semantics are feed/version-specific; unsupported input must be rejected or explicitly handled",
      "All market protocols have identical fields",
      "A protocol name alone specifies every byte layout",
      "Unknown messages should be cast to the nearest known structure",
      "Scope the parser to documented layouts and versions. Educational subsets must not imply full exchange compatibility.",
    ],
  ],
  "12-7": [
    [
      "A FIX byte stream ends halfway through a message. What should the decoder do?",
      "Keep the incomplete frame and await more bytes, subject to bounds and timeout policy",
      "Dispatch the half-message as a valid business event",
      "Treat each TCP read as a complete FIX message",
      "Guess the missing tag values",
      "Transport reads do not define FIX framing. Length, delimiter and checksum rules must be checked on complete bounded frames.",
    ],
    [
      "A received FIX sequence number is ahead of the next expected sequence. What must the session layer do?",
      "Apply the configured FIX session gap/recovery rules before normal ordered processing",
      "Ignore sequence numbers whenever TCP is used",
      "Rewrite the sender's sequence without logging",
      "Treat it as an application-level fill automatically",
      "TCP ordering does not replace session recovery across reconnects and persisted sequences. The session contract governs gaps.",
    ],
    [
      "Why is a transport send returning success not sufficient evidence that an order was accepted?",
      "Business acceptance requires the appropriate application acknowledgement and correlation",
      "Every socket write is an exchange acceptance",
      "The client timestamp is an acceptance report",
      "Encryption guarantees business acceptance",
      "Transport delivery, session processing and business acceptance are different stages. Correlate the defined response to the submitted request.",
    ],
    [
      "A retransmitted business message may already have been processed. What should the receiver use?",
      "The protocol's duplicate indicators plus an application idempotency policy and stable identifiers",
      "A new random identity on every retry",
      "Arrival time as the only duplicate test",
      "Assume every retransmission creates a new business action",
      "Session replay and business idempotency must work together to avoid repeated actions while preserving valid recovery.",
    ],
    [
      "A FIX message's BodyLength disagrees with the available bounded frame. What should happen?",
      "Reject or wait for completion according to framing state; never read outside the buffer",
      "Trust the claimed length and read arbitrary memory",
      "Ignore BodyLength and dispatch immediately",
      "Replace it with the number of parsed tags",
      "Validate length at the framing boundary. A partial frame and a malformed complete frame need distinct handling.",
    ],
    [
      "What belongs in a FIX replay test beyond successful logon?",
      "Gaps, duplicates, reconnects, sequence persistence and correlated application outcomes",
      "Only one heartbeat",
      "Only a successful TCP connection",
      "Only pretty-printed tag names",
      "Session correctness must survive interruption and replay, and application outcomes must remain consistent across those conditions.",
    ],
    [
      "A message satisfies FIX syntax but requests an invalid business operation. Which layer must still reject it?",
      "Application validation for that operation",
      "No layer: syntax proves authorization and validity",
      "The TCP checksum alone",
      "The text formatter",
      "Syntactic validity does not establish business permissions, instrument validity or state-transition correctness.",
    ],
  ],
  "12-8": [
    [
      "Which baseline best supports differential testing of an optimized order book?",
      "A simple independently implemented reference with the same declared event contract",
      "The optimized implementation called twice",
      "A random final price with no event history",
      "Only an expected runtime threshold",
      "Compare independently derived state after each event, not just performance or two executions of the same algorithm.",
    ],
    [
      "A benchmark excludes all rejected inputs from both count and report. What should the results disclose?",
      "Successful and rejected operation counts and the latency population being measured",
      "Only the fastest successful operation",
      "That excluded errors cannot matter",
      "A success rate of 100% by definition",
      "Benchmark denominators must be explicit. Hidden failures can make throughput and latency claims misleading.",
    ],
    [
      "An event parser mutates half an order before noticing a malformed field. What invariant should a repair enforce?",
      "Validate first, then commit the complete transition or leave state unchanged",
      "Keep the partial mutation because parsing began",
      "Reset unrelated orders",
      "Ignore the malformed field silently",
      "Atomic state transitions prevent invalid input from leaving the book in a state no valid event produced.",
    ],
    [
      "A price level contains two order IDs. Cancelling one ID should do what?",
      "Remove only that order's remaining quantity and retain the other order",
      "Delete the whole price level unconditionally",
      "Cancel whichever order arrived last",
      "Subtract the original quantity of every order",
      "Order identity and per-order remaining quantity are necessary to update aggregate price levels correctly.",
    ],
    [
      "What should a benchmark report to make a microsecond result reproducible?",
      "Hardware, compiler/options, workload, sample distribution, warm-up and measurement method",
      "Only the word microsecond",
      "A certificate hash without the run data",
      "The source-code line count",
      "A performance number is conditional on its environment and methodology. A signature cannot replace those measurements.",
    ],
    [
      "Why test an optimized book under address/undefined-behavior sanitizers separately from its timing run?",
      "Sanitizers help detect defects but change execution cost, so their timings are not production latency measurements",
      "Sanitizers prove every memory operation in every schedule",
      "A timing run should disable all correctness tests permanently",
      "Sanitizers improve all benchmark times",
      "Use instrumented runs for defect detection and separately specified release builds for timing. Preserve correctness checks in both workflows.",
    ],
    [
      "A sequence gap is detected during a replay benchmark. What should its report do?",
      "Mark the state invalid until recovery and report the gap/recovery outcome",
      "Keep claiming uninterrupted valid book state",
      "Hide the event from the input manifest",
      "Replace the missing updates with zeros",
      "Correctness status must accompany performance measurements. Throughput over invalid reconstructed state is not a successful replay.",
    ],
    [
      "Dura signs a multiple-choice assessment score. Does that signature establish the latency of an uploaded order-book program?",
      "No; executable correctness and latency require their own reproducible artifact evidence",
      "Yes; any signed score proves every claimed project property",
      "Yes; the program name determines performance",
      "Only if the displayed learner name is nonempty",
      "The signature's claims are bounded by what was scored. It is not evidence that a program was built, run or benchmarked.",
    ],
  ],
};

/** Rotate answer position while keeping each authored answer/explanation paired. */
export const SPECIALTY_EXPANSION_QUESTIONS: AssessmentQuestion[] = Object.entries(ITEMS).flatMap(
  ([moduleId, items]): AssessmentQuestion[] =>
    items.map((item, index): AssessmentQuestion => {
      const [question, answer, a, b, c, explanation] = item;
      const correct = index % 4;
      const options = [a, b, c];
      options.splice(correct, 0, answer);
      return {
        id: `specialty-applied-${moduleId}-${index + 1}`,
        phaseId: moduleId.split("-")[0],
        moduleId,
        type: "multiple-choice",
        question,
        options,
        correct,
        explanation,
        difficulty: "medium",
        tags: ["applied-practice", moduleId],
        standards: { bloom: "apply" },
      };
    })
);
