/**
 * Human-readable Markdown summary for the learner export ZIP.
 *
 * Lives next to the JSON + xAPI files inside the export bundle so that a
 * learner who downloads their data can read it directly without tooling.
 * Intentionally narrative — not a report, not a dashboard, not a CSV.
 */

import type { FlashCard, ReviewLog } from "@/types/flashcard";
import type { LessonProgress, ModuleProgress } from "@/types/curriculum";

export interface SummaryInput {
  exportedAt: string;
  learnerId: string;
  cards: FlashCard[];
  reviewLog: ReviewLog[];
  progress: LessonProgress[];
  moduleProgress: ModuleProgress[];
}

const RATING_LABELS: Record<ReviewLog["rating"], string> = {
  again: "Again",
  hard: "Hard",
  good: "Good",
  easy: "Easy",
};

export function generateMarkdownSummary(input: SummaryInput): string {
  const { exportedAt, learnerId, cards, reviewLog, progress, moduleProgress } = input;

  const completedLessons = progress.filter((p) => p.completedAt !== null).length;
  const totalTimeMs = progress.reduce((sum, p) => sum + p.timeSpentMs, 0);
  const totalTimeHours = (totalTimeMs / 3_600_000).toFixed(1);
  const totalXP = progress.reduce((sum, p) => sum + p.xpEarned, 0);

  const ratingCounts: Record<ReviewLog["rating"], number> = {
    again: 0,
    hard: 0,
    good: 0,
    easy: 0,
  };
  for (const entry of reviewLog) ratingCounts[entry.rating]++;
  const totalReviews = reviewLog.length;
  const ratingLines = (Object.keys(ratingCounts) as Array<ReviewLog["rating"]>)
    .map((rating) => {
      const count = ratingCounts[rating];
      const pct = totalReviews > 0 ? ((count / totalReviews) * 100).toFixed(1) : "0.0";
      return `- ${RATING_LABELS[rating]}: ${count} (${pct}%)`;
    })
    .join("\n");

  const masteryUnlocked = moduleProgress.filter((m) => m.masteryGatePassed).length;
  const cardStateCounts = countCardsByState(cards);

  return [
    "# DURA Learner Record",
    "",
    `**Exported:** ${exportedAt}`,
    `**Learner ID:** \`${learnerId}\` (local anonymous UUID — not linked to your name or email)`,
    "",
    "---",
    "",
    "## Overview",
    "",
    `- Lessons completed: **${completedLessons}** of ${progress.length} started`,
    `- Total study time: **${totalTimeHours} hours**`,
    `- XP earned: **${totalXP.toLocaleString()}**`,
    `- Modules with mastery gate passed: **${masteryUnlocked}** of ${moduleProgress.length}`,
    "",
    "## Flashcards",
    "",
    `- Total cards: **${cards.length}**`,
    `- New: ${cardStateCounts.new}`,
    `- Learning: ${cardStateCounts.learning}`,
    `- Review: ${cardStateCounts.review}`,
    `- Relearning: ${cardStateCounts.relearning}`,
    "",
    "## Review history",
    "",
    `- Total reviews: **${totalReviews}**`,
    ratingLines,
    "",
    "## What's in this archive",
    "",
    "- `learner-record.json` — your complete local study state (FSRS cards, review log, mastery records, progress).",
    "- `xapi-statements.json` — your learning history in xAPI 1.0.3 format. Importable into any conforming Learning Record Store.",
    "- `summary.md` — this file.",
    "",
    "## Your rights",
    "",
    "This export satisfies your right to data portability under GDPR Article 20 and equivalent laws. You may keep, share, transfer, or import this data wherever you choose. DURA retains no copy beyond what your local browser storage and (if you signed in) your synced Supabase account contain.",
    "",
    "Generated by DURA. https://dura.app",
    "",
  ].join("\n");
}

function countCardsByState(cards: FlashCard[]): Record<FlashCard["state"], number> {
  const counts: Record<FlashCard["state"], number> = {
    new: 0,
    learning: 0,
    review: 0,
    relearning: 0,
  };
  for (const card of cards) counts[card.state]++;
  return counts;
}
