import type { Role } from "@/types/career-track";

export const ROLES: Role[] = [
  // ─── 1. Frontend Engineer ───────────────────────────────────────────
  {
    id: "frontend",
    slug: "frontend-engineer",
    title: "Frontend Engineer",
    tagline: "Craft interfaces people love to use.",
    description:
      "Frontend engineers build the visual and interactive layer of web applications. You translate designs into performant, accessible code that works across browsers and devices. The role demands deep knowledge of HTML, CSS, JavaScript, and modern frameworks.",
    icon: "Monitor",
    color: "#3B82F6",
    levels: {
      junior: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "dom-manipulation",
          "responsive-design",
          "git-basics",
          "react-components",
          "debugging",
          "accessibility-basics",
          "npm-basics",
        ],
        valuable: ["typescript-basics", "css-animations", "browser-devtools", "testing-basics"],
      },
      mid: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "dom-manipulation",
          "responsive-design",
          "git-basics",
          "react-components",
          "debugging",
          "accessibility-basics",
          "npm-basics",
          "typescript-basics",
          "state-management",
          "api-integration",
          "performance-optimization",
          "testing-fundamentals",
          "css-architecture",
        ],
        valuable: [
          "design-systems",
          "ci-cd-basics",
          "webpack-bundlers",
          "animation-libraries",
          "pwa-basics",
          "seo-fundamentals",
        ],
      },
      senior: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "dom-manipulation",
          "responsive-design",
          "git-basics",
          "react-components",
          "debugging",
          "accessibility-basics",
          "npm-basics",
          "typescript-basics",
          "state-management",
          "api-integration",
          "performance-optimization",
          "testing-fundamentals",
          "css-architecture",
          "design-systems",
          "ci-cd-basics",
          "webpack-bundlers",
          "micro-frontends",
          "monitoring-observability",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "graphql",
          "web-security",
          "architecture-patterns",
          "server-side-rendering",
          "pwa-advanced",
          "internationalization",
          "technical-writing",
          "team-leadership",
          "system-design",
        ],
      },
    },
    portfolio: [
      { title: "Portfolio Site", tutorialSlug: "portfolio-site", skill: "React + Tailwind" },
      { title: "React Dashboard", tutorialSlug: "react-dashboard", skill: "Data Visualization" },
      {
        title: "Accessible Component Library",
        tutorialSlug: "accessible-components",
        skill: "Accessibility + ARIA",
      },
      { title: "Design System", tutorialSlug: "design-system", skill: "Design Tokens" },
      {
        title: "Algorithm Visualizer",
        tutorialSlug: "algorithm-visualizer",
        skill: "Canvas + Animation",
      },
      { title: "PWA with Push Notifications", tutorialSlug: "pwa-push", skill: "Service Workers" },
      { title: "Live Markdown Editor", tutorialSlug: "markdown-editor", skill: "Split-Pane UI" },
    ],
    standards: [
      {
        name: "WCAG 2.2",
        body: "W3C",
        url: "https://www.w3.org/TR/WCAG22/",
        description:
          "Web Content Accessibility Guidelines — the legal standard for accessible web content.",
      },
      {
        name: "ECMAScript 2024",
        body: "TC39 / Ecma International",
        url: "https://tc39.es/ecma262/",
        description: "The language specification that defines JavaScript.",
      },
      {
        name: "HTML Living Standard",
        body: "WHATWG",
        url: "https://html.spec.whatwg.org/",
        description: "The canonical specification for HTML elements, APIs, and browser behavior.",
      },
    ],
    certifications: [
      {
        name: "Meta Front-End Developer Professional Certificate",
        issuer: "Meta / Coursera",
        level: "entry",
        url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
      },
      {
        name: "AWS Certified Cloud Practitioner",
        issuer: "Amazon Web Services",
        level: "entry",
        url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
      },
      {
        name: "Google UX Design Professional Certificate",
        issuer: "Google / Coursera",
        level: "entry",
        url: "https://www.coursera.org/professional-certificates/google-ux-design",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "HTML & Semantic Markup", skillId: "html-fundamentals" },
          { skill: "CSS & Layout Systems", skillId: "css-fundamentals" },
          { skill: "JavaScript / TypeScript", skillId: "javascript-basics" },
          { skill: "React", skillId: "react-components" },
          { skill: "Accessibility (a11y)", skillId: "accessibility-basics" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Performance Optimization", skillId: "performance-optimization" },
          { skill: "State Management", skillId: "state-management" },
          { skill: "Server-Side Rendering", skillId: "server-side-rendering" },
          { skill: "Design Systems", skillId: "design-systems" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Bundlers (Webpack, Vite)", skillId: "webpack-bundlers" },
          { skill: "Testing (Vitest, Playwright)", skillId: "testing-fundamentals" },
          { skill: "Browser DevTools", skillId: "browser-devtools" },
        ],
      },
    ],
    dayInTheLife:
      "You start the day reviewing pull requests and checking how a feature looks on mobile. Most of your time is spent building UI components, debugging CSS edge cases, and working with designers to refine interactions. You attend a weekly accessibility audit and occasionally profile rendering performance to keep page loads under budget.",
    salaryRange: { low: 85000, high: 195000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["first-tech-job", "career-switch", "build-startup"],
    prerequisites: [],
    leadsTo: ["full-stack", "engineering-manager"],
  },

  // ─── 2. Backend Engineer ────────────────────────────────────────────
  {
    id: "backend",
    slug: "backend-engineer",
    title: "Backend Engineer",
    tagline: "Build the systems behind the screen.",
    description:
      "Backend engineers design APIs, manage databases, and build the server-side logic that powers applications. You ensure data integrity, handle scale, and integrate with third-party services. Reliability and security are your daily concerns.",
    icon: "Server",
    color: "#10B981",
    levels: {
      junior: {
        required: [
          "javascript-basics",
          "node-js-fundamentals",
          "http-protocol",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "json-data",
          "error-handling",
          "npm-basics",
        ],
        valuable: [
          "typescript-basics",
          "database-indexing",
          "authentication-basics",
          "testing-basics",
        ],
      },
      mid: {
        required: [
          "javascript-basics",
          "node-js-fundamentals",
          "http-protocol",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "json-data",
          "error-handling",
          "npm-basics",
          "typescript-basics",
          "database-indexing",
          "authentication-basics",
          "testing-fundamentals",
          "caching-strategies",
          "message-queues",
        ],
        valuable: [
          "docker-basics",
          "ci-cd-basics",
          "graphql",
          "database-design",
          "monitoring-observability",
          "rate-limiting",
        ],
      },
      senior: {
        required: [
          "javascript-basics",
          "node-js-fundamentals",
          "http-protocol",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "json-data",
          "error-handling",
          "npm-basics",
          "typescript-basics",
          "database-indexing",
          "authentication-basics",
          "testing-fundamentals",
          "caching-strategies",
          "message-queues",
          "docker-basics",
          "ci-cd-basics",
          "database-design",
          "monitoring-observability",
          "system-design",
          "security-fundamentals",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "graphql",
          "event-driven-architecture",
          "distributed-systems",
          "kubernetes-basics",
          "infrastructure-as-code",
          "performance-profiling",
          "technical-writing",
          "team-leadership",
          "architecture-patterns",
        ],
      },
    },
    portfolio: [
      { title: "REST API", tutorialSlug: "rest-api", skill: "API Design + Validation" },
      { title: "Authentication System", tutorialSlug: "auth-system", skill: "JWT + Sessions" },
      { title: "URL Shortener", tutorialSlug: "url-shortener", skill: "System Design" },
      { title: "Task Queue with Workers", tutorialSlug: "task-queue", skill: "Async Processing" },
      {
        title: "Rate Limiter Service",
        tutorialSlug: "rate-limiter",
        skill: "Algorithms + Middleware",
      },
      {
        title: "Database Migration Tool",
        tutorialSlug: "migration-tool",
        skill: "Schema Management",
      },
      { title: "Key-Value Store", tutorialSlug: "key-value-store", skill: "Low-Level Systems" },
    ],
    standards: [
      {
        name: "OpenAPI Specification 3.1",
        body: "OpenAPI Initiative",
        url: "https://spec.openapis.org/oas/v3.1.0",
        description: "The standard for describing RESTful APIs in a machine-readable format.",
      },
      {
        name: "OWASP Top 10",
        body: "OWASP Foundation",
        url: "https://owasp.org/www-project-top-ten/",
        description:
          "The industry-standard list of the most critical web application security risks.",
      },
      {
        name: "RFC 7231 — HTTP/1.1 Semantics",
        body: "IETF",
        url: "https://datatracker.ietf.org/doc/html/rfc7231",
        description: "Defines HTTP methods, status codes, and header field semantics.",
      },
    ],
    certifications: [
      {
        name: "AWS Certified Developer – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-developer-associate/",
      },
      {
        name: "Meta Back-End Developer Professional Certificate",
        issuer: "Meta / Coursera",
        level: "entry",
        url: "https://www.coursera.org/professional-certificates/meta-back-end-developer",
      },
      {
        name: "PostgreSQL Certified Associate",
        issuer: "EDB / PostgreSQL",
        level: "professional",
        url: "https://www.enterprisedb.com/course/postgresql-certified-associate-certification",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Node.js / Server-Side JS", skillId: "node-js-fundamentals" },
          { skill: "REST API Design", skillId: "rest-api-design" },
          { skill: "SQL & Relational Databases", skillId: "sql-queries" },
          { skill: "Authentication & Authorization", skillId: "authentication-basics" },
          { skill: "Error Handling & Logging", skillId: "error-handling" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "System Design", skillId: "system-design" },
          { skill: "Caching Strategies", skillId: "caching-strategies" },
          { skill: "Message Queues", skillId: "message-queues" },
          { skill: "Database Optimization", skillId: "database-indexing" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Docker", skillId: "docker-basics" },
          { skill: "CI/CD", skillId: "ci-cd-basics" },
          { skill: "Monitoring (Grafana, Datadog)", skillId: "monitoring-observability" },
        ],
      },
    ],
    dayInTheLife:
      "You spend mornings investigating a slow database query and adding an index. After standup, you design a new API endpoint, write the migration, implement the handler, and add integration tests. Afternoons involve code review, debugging a race condition in the queue processor, and updating runbooks for on-call.",
    salaryRange: { low: 90000, high: 210000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["first-tech-job", "career-switch"],
    prerequisites: [],
    leadsTo: ["full-stack", "sre", "solutions-architect"],
  },

  // ─── 3. Full-Stack Engineer ─────────────────────────────────────────
  {
    id: "full-stack",
    slug: "full-stack-engineer",
    title: "Full-Stack Engineer",
    tagline: "Own the feature from database to deploy button.",
    description:
      "Full-stack engineers work across the entire application — frontend, backend, database, and deployment. You build features end-to-end, which makes you especially valuable at startups and small teams. The trade-off is breadth over extreme depth.",
    icon: "Layers",
    color: "#8B5CF6",
    levels: {
      junior: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "react-components",
          "node-js-fundamentals",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "responsive-design",
          "npm-basics",
        ],
        valuable: ["typescript-basics", "authentication-basics", "testing-basics", "docker-basics"],
      },
      mid: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "react-components",
          "node-js-fundamentals",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "responsive-design",
          "npm-basics",
          "typescript-basics",
          "authentication-basics",
          "state-management",
          "database-design",
          "testing-fundamentals",
          "docker-basics",
          "ci-cd-basics",
        ],
        valuable: [
          "caching-strategies",
          "performance-optimization",
          "accessibility-basics",
          "graphql",
          "monitoring-observability",
          "server-side-rendering",
        ],
      },
      senior: {
        required: [
          "html-fundamentals",
          "css-fundamentals",
          "javascript-basics",
          "react-components",
          "node-js-fundamentals",
          "rest-api-design",
          "sql-queries",
          "git-basics",
          "debugging",
          "responsive-design",
          "npm-basics",
          "typescript-basics",
          "authentication-basics",
          "state-management",
          "database-design",
          "testing-fundamentals",
          "docker-basics",
          "ci-cd-basics",
          "system-design",
          "performance-optimization",
          "monitoring-observability",
          "security-fundamentals",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "graphql",
          "kubernetes-basics",
          "event-driven-architecture",
          "micro-frontends",
          "infrastructure-as-code",
          "architecture-patterns",
          "technical-writing",
          "team-leadership",
          "distributed-systems",
          "accessibility-basics",
        ],
      },
    },
    portfolio: [
      { title: "Full-Stack Task Board", tutorialSlug: "task-board", skill: "End-to-End CRUD" },
      {
        title: "Authentication System",
        tutorialSlug: "auth-system",
        skill: "JWT + Protected Routes",
      },
      {
        title: "E-Commerce Checkout",
        tutorialSlug: "ecommerce-checkout",
        skill: "Payments + Cart",
      },
      { title: "Dockerized Deployment", tutorialSlug: "docker-deploy", skill: "Containers + CI" },
      { title: "Real-Time Chat App", tutorialSlug: "chat-app", skill: "WebSockets" },
      { title: "Blog Engine", tutorialSlug: "blog-engine", skill: "MDX + Dynamic Routes" },
    ],
    standards: [
      {
        name: "Twelve-Factor App",
        body: "Heroku / Industry Standard",
        url: "https://12factor.net/",
        description: "Methodology for building modern, portable, scalable web applications.",
      },
      {
        name: "OWASP Top 10",
        body: "OWASP Foundation",
        url: "https://owasp.org/www-project-top-ten/",
        description:
          "The industry-standard list of the most critical web application security risks.",
      },
    ],
    certifications: [
      {
        name: "AWS Certified Developer – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-developer-associate/",
      },
      {
        name: "Meta Full-Stack Software Engineer Professional Certificate",
        issuer: "Meta / Coursera",
        level: "entry",
        url: "https://www.coursera.org/professional-certificates/meta-back-end-developer",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "React / Next.js", skillId: "react-components" },
          { skill: "Node.js + REST APIs", skillId: "rest-api-design" },
          { skill: "SQL & Database Design", skillId: "sql-queries" },
          { skill: "TypeScript", skillId: "typescript-basics" },
          { skill: "Authentication", skillId: "authentication-basics" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "System Design", skillId: "system-design" },
          { skill: "Performance Optimization", skillId: "performance-optimization" },
          { skill: "DevOps & CI/CD", skillId: "ci-cd-basics" },
          { skill: "Security Best Practices", skillId: "security-fundamentals" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Docker", skillId: "docker-basics" },
          { skill: "Testing Frameworks", skillId: "testing-fundamentals" },
          { skill: "Monitoring & Logging", skillId: "monitoring-observability" },
        ],
      },
    ],
    dayInTheLife:
      "You pick up a feature ticket that spans the full stack: create a database table, build the API endpoint, wire up the React form, and deploy it behind a feature flag. After lunch, you fix a CSS bug on mobile, review a teammate's backend PR, and troubleshoot a deployment that failed in staging.",
    salaryRange: { low: 90000, high: 220000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "very-high",
    goals: ["first-tech-job", "career-switch", "build-startup"],
    prerequisites: [],
    leadsTo: ["engineering-manager", "solutions-architect"],
  },

  // ─── 4. DevOps / Platform Engineer ──────────────────────────────────
  {
    id: "devops",
    slug: "devops-platform-engineer",
    title: "DevOps / Platform Engineer",
    tagline: "Make shipping code boring and reliable.",
    description:
      "DevOps engineers build the infrastructure, CI/CD pipelines, and tooling that let product teams deploy safely and frequently. You automate everything — builds, tests, deploys, monitoring, and incident response. The goal is zero-friction, zero-downtime releases.",
    icon: "Cloud",
    color: "#F59E0B",
    levels: {
      junior: {
        required: [
          "linux-fundamentals",
          "shell-scripting",
          "git-basics",
          "docker-basics",
          "ci-cd-basics",
          "networking-basics",
          "cloud-fundamentals",
          "debugging",
        ],
        valuable: [
          "kubernetes-basics",
          "infrastructure-as-code",
          "monitoring-observability",
          "python-basics",
        ],
      },
      mid: {
        required: [
          "linux-fundamentals",
          "shell-scripting",
          "git-basics",
          "docker-basics",
          "ci-cd-basics",
          "networking-basics",
          "cloud-fundamentals",
          "debugging",
          "kubernetes-basics",
          "infrastructure-as-code",
          "monitoring-observability",
          "python-basics",
          "security-fundamentals",
          "database-administration",
        ],
        valuable: [
          "service-mesh",
          "chaos-engineering",
          "cost-optimization",
          "secrets-management",
          "load-balancing",
          "gitops",
        ],
      },
      senior: {
        required: [
          "linux-fundamentals",
          "shell-scripting",
          "git-basics",
          "docker-basics",
          "ci-cd-basics",
          "networking-basics",
          "cloud-fundamentals",
          "debugging",
          "kubernetes-basics",
          "infrastructure-as-code",
          "monitoring-observability",
          "python-basics",
          "security-fundamentals",
          "database-administration",
          "service-mesh",
          "chaos-engineering",
          "system-design",
          "distributed-systems",
          "incident-management",
          "cost-optimization",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "machine-learning-ops",
          "compliance-frameworks",
          "team-leadership",
          "technical-writing",
          "architecture-patterns",
          "performance-profiling",
          "multi-cloud",
          "edge-computing",
          "gitops",
        ],
      },
    },
    portfolio: [
      { title: "CI/CD Pipeline", tutorialSlug: "ci-cd-pipeline", skill: "GitHub Actions" },
      { title: "Dockerized Deployment", tutorialSlug: "docker-deploy", skill: "Docker Compose" },
      {
        title: "Monitoring Dashboard",
        tutorialSlug: "monitoring-dashboard",
        skill: "Metrics + Alerts",
      },
      { title: "Load Balancer", tutorialSlug: "load-balancer", skill: "Traffic Distribution" },
      {
        title: "Secrets Manager",
        tutorialSlug: "secrets-manager",
        skill: "Encryption + Access Control",
      },
      { title: "Log Aggregator", tutorialSlug: "log-aggregator", skill: "Structured Logging" },
      { title: "Cron Job Scheduler", tutorialSlug: "cron-scheduler", skill: "Job Orchestration" },
    ],
    standards: [
      {
        name: "DORA Metrics",
        body: "Google Cloud / DORA",
        url: "https://dora.dev/",
        description: "Industry-standard metrics for measuring software delivery performance.",
      },
      {
        name: "CIS Benchmarks",
        body: "Center for Internet Security",
        url: "https://www.cisecurity.org/cis-benchmarks",
        description: "Consensus-driven security configuration guides for hardening systems.",
      },
      {
        name: "NIST SP 800-190 Container Security",
        body: "NIST",
        url: "https://csrc.nist.gov/publications/detail/sp/800-190/final",
        description: "Security guidelines for application container technologies.",
      },
    ],
    certifications: [
      {
        name: "AWS Certified Solutions Architect – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
      },
      {
        name: "Certified Kubernetes Administrator (CKA)",
        issuer: "Cloud Native Computing Foundation",
        level: "professional",
        url: "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/",
      },
      {
        name: "HashiCorp Terraform Associate",
        issuer: "HashiCorp",
        level: "entry",
        url: "https://www.hashicorp.com/certifications/terraform-associate",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Linux & Shell Scripting", skillId: "linux-fundamentals" },
          { skill: "Docker & Containers", skillId: "docker-basics" },
          { skill: "CI/CD Pipelines", skillId: "ci-cd-basics" },
          { skill: "Cloud Platforms (AWS/GCP/Azure)", skillId: "cloud-fundamentals" },
          { skill: "Infrastructure as Code", skillId: "infrastructure-as-code" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Kubernetes", skillId: "kubernetes-basics" },
          { skill: "Monitoring & Observability", skillId: "monitoring-observability" },
          { skill: "Chaos Engineering", skillId: "chaos-engineering" },
          { skill: "Service Mesh", skillId: "service-mesh" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Terraform / Pulumi", skillId: "infrastructure-as-code" },
          { skill: "Prometheus / Grafana", skillId: "monitoring-observability" },
          { skill: "Git", skillId: "git-basics" },
          { skill: "Python / Bash Scripting", skillId: "shell-scripting" },
        ],
      },
    ],
    dayInTheLife:
      "You start by checking the overnight alert dashboard and resolving any flaky deployments. Mid-morning, you write Terraform to provision a new staging environment. After lunch, you optimize a CI pipeline that's taking too long, review a Dockerfile PR, and run a chaos experiment to test failover behavior.",
    salaryRange: { low: 95000, high: 225000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "very-high",
    goals: ["reliable-systems"],
    prerequisites: ["backend"],
    leadsTo: ["sre", "solutions-architect"],
  },

  // ─── 5. AI/ML Engineer ─────────────────────────────────────────────
  {
    id: "ai-ml",
    slug: "ai-ml-engineer",
    title: "AI/ML Engineer",
    tagline: "Turn data into intelligence.",
    description:
      "AI/ML engineers build systems that learn from data — from training and fine-tuning models to deploying them in production. You work at the intersection of software engineering and machine learning, building RAG pipelines, embedding systems, and AI-powered features.",
    icon: "Brain",
    color: "#06B6D4",
    levels: {
      junior: {
        required: [
          "python-basics",
          "javascript-basics",
          "api-integration",
          "json-data",
          "git-basics",
          "debugging",
          "prompt-engineering",
          "embeddings-basics",
          "vector-databases",
          "statistics-basics",
        ],
        valuable: ["sql-queries", "docker-basics", "testing-basics", "data-preprocessing"],
      },
      mid: {
        required: [
          "python-basics",
          "javascript-basics",
          "api-integration",
          "json-data",
          "git-basics",
          "debugging",
          "prompt-engineering",
          "embeddings-basics",
          "vector-databases",
          "statistics-basics",
          "sql-queries",
          "model-evaluation",
          "rag-patterns",
          "fine-tuning-basics",
          "data-preprocessing",
          "mlops-basics",
        ],
        valuable: [
          "docker-basics",
          "distributed-computing",
          "feature-engineering",
          "transformer-architecture",
          "ci-cd-basics",
          "monitoring-observability",
          "ethical-ai",
        ],
      },
      senior: {
        required: [
          "python-basics",
          "javascript-basics",
          "api-integration",
          "json-data",
          "git-basics",
          "debugging",
          "prompt-engineering",
          "embeddings-basics",
          "vector-databases",
          "statistics-basics",
          "sql-queries",
          "model-evaluation",
          "rag-patterns",
          "fine-tuning-basics",
          "data-preprocessing",
          "mlops-basics",
          "transformer-architecture",
          "distributed-computing",
          "system-design",
          "feature-engineering",
          "ethical-ai",
          "code-review",
          "mentoring",
          "technical-writing",
        ],
        valuable: [
          "reinforcement-learning",
          "multi-modal-models",
          "kubernetes-basics",
          "cost-optimization",
          "team-leadership",
          "architecture-patterns",
          "research-methodology",
          "compliance-frameworks",
          "performance-profiling",
        ],
      },
    },
    portfolio: [
      {
        title: "RAG Chatbot",
        tutorialSlug: "rag-chatbot",
        skill: "Retrieval-Augmented Generation",
      },
      {
        title: "AI Agent with Tool Use",
        tutorialSlug: "ai-agent",
        skill: "Planning + Tool Calling",
      },
      {
        title: "Embeddings Search Engine",
        tutorialSlug: "embeddings-search",
        skill: "Vector Search",
      },
      { title: "Fine-Tuning Pipeline", tutorialSlug: "fine-tuning", skill: "LoRA + Evaluation" },
      { title: "AI Code Reviewer", tutorialSlug: "ai-code-reviewer", skill: "LLM + Code Analysis" },
      { title: "MCP Server", tutorialSlug: "mcp-server-tutorial", skill: "Model Context Protocol" },
    ],
    standards: [
      {
        name: "NIST AI Risk Management Framework",
        body: "NIST",
        url: "https://www.nist.gov/artificial-intelligence/executive-order-safe-secure-and-trustworthy-artificial-intelligence",
        description:
          "Framework for managing risks in AI system design, development, and deployment.",
      },
      {
        name: "EU AI Act",
        body: "European Commission",
        url: "https://artificialintelligenceact.eu/",
        description:
          "The first comprehensive legal framework for AI, classifying systems by risk level.",
      },
      {
        name: "Model Card Reporting",
        body: "Google / Industry Practice",
        url: "https://modelcards.withgoogle.com/about",
        description:
          "Documentation framework for trained ML models covering performance, bias, and intended use.",
      },
    ],
    certifications: [
      {
        name: "AWS Certified Machine Learning – Specialty",
        issuer: "Amazon Web Services",
        level: "expert",
        url: "https://aws.amazon.com/certification/certified-machine-learning-specialty/",
      },
      {
        name: "Google Professional Machine Learning Engineer",
        issuer: "Google Cloud",
        level: "professional",
        url: "https://cloud.google.com/learn/certification/machine-learning-engineer",
      },
      {
        name: "DeepLearning.AI TensorFlow Developer Certificate",
        issuer: "DeepLearning.AI",
        level: "entry",
        url: "https://www.deeplearning.ai/courses/tensorflow-developer-professional-certificate/",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Python", skillId: "python-basics" },
          { skill: "Prompt Engineering", skillId: "prompt-engineering" },
          { skill: "RAG & Embeddings", skillId: "rag-patterns" },
          { skill: "Model Evaluation", skillId: "model-evaluation" },
          { skill: "Data Preprocessing", skillId: "data-preprocessing" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Fine-Tuning (LoRA, QLoRA)", skillId: "fine-tuning-basics" },
          { skill: "Transformer Architecture", skillId: "transformer-architecture" },
          { skill: "MLOps & Model Serving", skillId: "mlops-basics" },
          { skill: "Distributed Training", skillId: "distributed-computing" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Docker", skillId: "docker-basics" },
          { skill: "Jupyter / Notebooks", skillId: "python-basics" },
          { skill: "Vector Databases (Pinecone, pgvector)", skillId: "vector-databases" },
        ],
      },
    ],
    dayInTheLife:
      "You start by evaluating a new embedding model against your test suite. Mid-morning, you optimize a RAG pipeline's chunk size and retrieval strategy. After lunch, you debug why an AI agent is hallucinating on a specific edge case, write evaluation harnesses, and review a teammate's prompt engineering changes.",
    salaryRange: { low: 110000, high: 280000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "extreme",
    goals: ["specialize-ai", "build-startup"],
    prerequisites: ["backend"],
    leadsTo: ["solutions-architect", "engineering-manager"],
  },

  // ─── 6. Security Engineer ──────────────────────────────────────────
  {
    id: "security",
    slug: "security-engineer",
    title: "Security Engineer",
    tagline: "Defend systems before attackers find the cracks.",
    description:
      "Security engineers protect applications, infrastructure, and data from threats. You perform threat modeling, implement security controls, conduct penetration testing, and build secure-by-default tooling. Every company with users needs you.",
    icon: "Shield",
    color: "#EF4444",
    levels: {
      junior: {
        required: [
          "networking-basics",
          "linux-fundamentals",
          "http-protocol",
          "authentication-basics",
          "encryption-basics",
          "git-basics",
          "web-security",
          "shell-scripting",
          "debugging",
          "sql-queries",
        ],
        valuable: ["python-basics", "docker-basics", "owasp-top-ten", "logging-basics"],
      },
      mid: {
        required: [
          "networking-basics",
          "linux-fundamentals",
          "http-protocol",
          "authentication-basics",
          "encryption-basics",
          "git-basics",
          "web-security",
          "shell-scripting",
          "debugging",
          "sql-queries",
          "python-basics",
          "owasp-top-ten",
          "threat-modeling",
          "penetration-testing",
          "security-fundamentals",
          "cloud-security",
        ],
        valuable: [
          "docker-basics",
          "incident-response",
          "compliance-frameworks",
          "secrets-management",
          "ci-cd-basics",
          "reverse-engineering",
        ],
      },
      senior: {
        required: [
          "networking-basics",
          "linux-fundamentals",
          "http-protocol",
          "authentication-basics",
          "encryption-basics",
          "git-basics",
          "web-security",
          "shell-scripting",
          "debugging",
          "sql-queries",
          "python-basics",
          "owasp-top-ten",
          "threat-modeling",
          "penetration-testing",
          "security-fundamentals",
          "cloud-security",
          "incident-response",
          "compliance-frameworks",
          "secrets-management",
          "security-architecture",
          "code-review",
          "mentoring",
          "forensics-basics",
        ],
        valuable: [
          "reverse-engineering",
          "zero-trust-architecture",
          "devsecops",
          "team-leadership",
          "technical-writing",
          "architecture-patterns",
          "kubernetes-security",
          "supply-chain-security",
          "bug-bounty-programs",
        ],
      },
    },
    portfolio: [
      { title: "Authentication System", tutorialSlug: "auth-system", skill: "Secure Auth Flows" },
      {
        title: "RBAC Authorization System",
        tutorialSlug: "rbac-system",
        skill: "Roles + Permissions",
      },
      {
        title: "Secrets Manager",
        tutorialSlug: "secrets-manager",
        skill: "Encryption + Key Rotation",
      },
      {
        title: "OAuth 2.0 Provider",
        tutorialSlug: "oauth-provider",
        skill: "PKCE + Token Management",
      },
      { title: "Rate Limiter Service", tutorialSlug: "rate-limiter", skill: "DDoS Mitigation" },
      { title: "API Gateway", tutorialSlug: "api-gateway", skill: "Auth + Rate Limiting" },
    ],
    standards: [
      {
        name: "OWASP Top 10",
        body: "OWASP Foundation",
        url: "https://owasp.org/www-project-top-ten/",
        description:
          "The industry-standard list of the most critical web application security risks.",
      },
      {
        name: "NIST Cybersecurity Framework 2.0",
        body: "NIST",
        url: "https://www.nist.gov/cyberframework",
        description:
          "Comprehensive framework for managing cybersecurity risk across organizations.",
      },
      {
        name: "SOC 2 Type II",
        body: "AICPA",
        url: "https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
        description:
          "Trust service criteria for security, availability, and confidentiality of customer data.",
      },
      {
        name: "ISO 27001",
        body: "ISO / IEC",
        url: "https://www.iso.org/standard/27001",
        description: "International standard for information security management systems.",
      },
    ],
    certifications: [
      {
        name: "CompTIA Security+",
        issuer: "CompTIA",
        level: "entry",
        url: "https://www.comptia.org/certifications/security",
      },
      {
        name: "Certified Ethical Hacker (CEH)",
        issuer: "EC-Council",
        level: "professional",
        url: "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
      },
      {
        name: "OSCP (Offensive Security Certified Professional)",
        issuer: "Offensive Security",
        level: "expert",
        url: "https://www.offsec.com/courses/pen-200/",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Web Application Security", skillId: "web-security" },
          { skill: "Network Security", skillId: "networking-basics" },
          { skill: "Cryptography & Encryption", skillId: "encryption-basics" },
          { skill: "Authentication & Authorization", skillId: "authentication-basics" },
          { skill: "Threat Modeling", skillId: "threat-modeling" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Penetration Testing", skillId: "penetration-testing" },
          { skill: "Incident Response", skillId: "incident-response" },
          { skill: "Cloud Security", skillId: "cloud-security" },
          { skill: "Security Architecture", skillId: "security-architecture" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Burp Suite / ZAP", skillId: "penetration-testing" },
          { skill: "Linux & Shell", skillId: "linux-fundamentals" },
          { skill: "Python Scripting", skillId: "python-basics" },
          { skill: "SIEM & Log Analysis", skillId: "logging-basics" },
        ],
      },
    ],
    dayInTheLife:
      "You start by reviewing yesterday's vulnerability scan results and triaging new findings. Mid-morning, you conduct a threat model review for a new feature. After lunch, you write a security automation tool, review PRs for auth bypass risks, and update the team's security runbook based on a recent incident.",
    salaryRange: { low: 100000, high: 240000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "very-high",
    goals: ["cybersecurity"],
    prerequisites: ["backend"],
    leadsTo: ["solutions-architect", "engineering-manager"],
  },

  // ─── 7. Data Engineer ──────────────────────────────────────────────
  {
    id: "data",
    slug: "data-engineer",
    title: "Data Engineer",
    tagline: "Build the pipelines that make data usable.",
    description:
      "Data engineers design and maintain the infrastructure for collecting, storing, and transforming data. You build ETL pipelines, data warehouses, and real-time streaming systems. Your work enables data scientists, analysts, and AI engineers to do theirs.",
    icon: "Database",
    color: "#14B8A6",
    levels: {
      junior: {
        required: [
          "sql-queries",
          "python-basics",
          "database-design",
          "git-basics",
          "data-modeling",
          "etl-basics",
          "json-data",
          "debugging",
          "shell-scripting",
          "csv-data-handling",
        ],
        valuable: ["docker-basics", "cloud-fundamentals", "data-warehousing", "statistics-basics"],
      },
      mid: {
        required: [
          "sql-queries",
          "python-basics",
          "database-design",
          "git-basics",
          "data-modeling",
          "etl-basics",
          "json-data",
          "debugging",
          "shell-scripting",
          "csv-data-handling",
          "docker-basics",
          "cloud-fundamentals",
          "data-warehousing",
          "streaming-data",
          "data-quality",
          "database-indexing",
        ],
        valuable: [
          "spark-basics",
          "orchestration-tools",
          "ci-cd-basics",
          "data-governance",
          "monitoring-observability",
          "statistics-basics",
        ],
      },
      senior: {
        required: [
          "sql-queries",
          "python-basics",
          "database-design",
          "git-basics",
          "data-modeling",
          "etl-basics",
          "json-data",
          "debugging",
          "shell-scripting",
          "csv-data-handling",
          "docker-basics",
          "cloud-fundamentals",
          "data-warehousing",
          "streaming-data",
          "data-quality",
          "database-indexing",
          "spark-basics",
          "orchestration-tools",
          "system-design",
          "data-governance",
          "distributed-systems",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "machine-learning-ops",
          "real-time-analytics",
          "data-lake-architecture",
          "team-leadership",
          "technical-writing",
          "cost-optimization",
          "compliance-frameworks",
          "architecture-patterns",
          "kubernetes-basics",
        ],
      },
    },
    portfolio: [
      { title: "ETL Pipeline", tutorialSlug: "etl-pipeline", skill: "Extract + Transform + Load" },
      {
        title: "Data Dashboard with SQL",
        tutorialSlug: "data-dashboard",
        skill: "SQL + Visualization",
      },
      {
        title: "Streaming Data Processor",
        tutorialSlug: "streaming-processor",
        skill: "Event Streams",
      },
      {
        title: "Database Migration Tool",
        tutorialSlug: "migration-tool",
        skill: "Schema Versioning",
      },
      { title: "Log Aggregator", tutorialSlug: "log-aggregator", skill: "Structured Ingestion" },
      { title: "Key-Value Store", tutorialSlug: "key-value-store", skill: "Storage Internals" },
    ],
    standards: [
      {
        name: "Data Management Body of Knowledge (DMBOK)",
        body: "DAMA International",
        url: "https://www.dama.org/cpages/body-of-knowledge",
        description:
          "The comprehensive guide to enterprise data management practices and principles.",
      },
      {
        name: "Apache Parquet Format",
        body: "Apache Software Foundation",
        url: "https://parquet.apache.org/",
        description: "Columnar storage format that is the de facto standard for analytical data.",
      },
    ],
    certifications: [
      {
        name: "Google Professional Data Engineer",
        issuer: "Google Cloud",
        level: "professional",
        url: "https://cloud.google.com/learn/certification/data-engineer",
      },
      {
        name: "AWS Certified Data Engineer – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-data-engineer-associate/",
      },
      {
        name: "Databricks Certified Data Engineer Associate",
        issuer: "Databricks",
        level: "entry",
        url: "https://www.databricks.com/learn/certification/data-engineer-associate",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "SQL & Database Design", skillId: "sql-queries" },
          { skill: "Python", skillId: "python-basics" },
          { skill: "ETL / ELT Pipelines", skillId: "etl-basics" },
          { skill: "Data Modeling", skillId: "data-modeling" },
          { skill: "Data Warehousing", skillId: "data-warehousing" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Streaming (Kafka, Flink)", skillId: "streaming-data" },
          { skill: "Distributed Computing (Spark)", skillId: "spark-basics" },
          { skill: "Data Quality & Governance", skillId: "data-quality" },
          { skill: "Data Lake Architecture", skillId: "data-lake-architecture" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Docker", skillId: "docker-basics" },
          { skill: "Airflow / Dagster", skillId: "orchestration-tools" },
          { skill: "Cloud Data Services", skillId: "cloud-fundamentals" },
        ],
      },
    ],
    dayInTheLife:
      "You start by checking pipeline health — did last night's ETL jobs succeed? After fixing a schema drift issue, you optimize a slow Spark job and review a PR that adds a new data source. Afternoon is spent designing a real-time event streaming pipeline and documenting the data lineage for a new table.",
    salaryRange: { low: 95000, high: 230000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "very-high",
    goals: ["work-with-data"],
    prerequisites: ["backend"],
    leadsTo: ["ai-ml", "solutions-architect"],
  },

  // ─── 8. QA / Test Engineer ─────────────────────────────────────────
  {
    id: "qa-testing",
    slug: "qa-test-engineer",
    title: "QA / Test Engineer",
    tagline: "Ship confidence, not just code.",
    description:
      "QA engineers design test strategies, write automated test suites, and ensure software quality before it reaches users. You catch bugs early, build testing infrastructure, and define quality gates. The best QA engineers make the entire team faster.",
    icon: "TestTube",
    color: "#F97316",
    levels: {
      junior: {
        required: [
          "javascript-basics",
          "testing-basics",
          "git-basics",
          "debugging",
          "html-fundamentals",
          "http-protocol",
          "test-case-design",
          "manual-testing",
        ],
        valuable: ["typescript-basics", "api-testing", "accessibility-basics", "sql-queries"],
      },
      mid: {
        required: [
          "javascript-basics",
          "testing-basics",
          "git-basics",
          "debugging",
          "html-fundamentals",
          "http-protocol",
          "test-case-design",
          "manual-testing",
          "typescript-basics",
          "testing-fundamentals",
          "api-testing",
          "accessibility-basics",
          "ci-cd-basics",
          "performance-testing",
        ],
        valuable: [
          "docker-basics",
          "sql-queries",
          "load-testing",
          "security-testing",
          "mobile-testing",
          "test-architecture",
        ],
      },
      senior: {
        required: [
          "javascript-basics",
          "testing-basics",
          "git-basics",
          "debugging",
          "html-fundamentals",
          "http-protocol",
          "test-case-design",
          "manual-testing",
          "typescript-basics",
          "testing-fundamentals",
          "api-testing",
          "accessibility-basics",
          "ci-cd-basics",
          "performance-testing",
          "test-architecture",
          "load-testing",
          "security-testing",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "chaos-engineering",
          "docker-basics",
          "monitoring-observability",
          "team-leadership",
          "technical-writing",
          "architecture-patterns",
          "contract-testing",
          "visual-regression",
          "mobile-testing",
          "ai-testing",
        ],
      },
    },
    portfolio: [
      { title: "Test Suite", tutorialSlug: "test-suite", skill: "Unit + Integration + E2E" },
      {
        title: "API Testing Framework",
        tutorialSlug: "api-testing-framework",
        skill: "HTTP Assertions",
      },
      { title: "CI/CD Pipeline", tutorialSlug: "ci-cd-pipeline", skill: "Automated Quality Gates" },
      {
        title: "Accessible Components",
        tutorialSlug: "accessible-components",
        skill: "a11y Testing",
      },
      {
        title: "A/B Testing Platform",
        tutorialSlug: "a-b-testing",
        skill: "Experiment Frameworks",
      },
      {
        title: "Feature Flag Service",
        tutorialSlug: "feature-flags",
        skill: "Controlled Rollouts",
      },
    ],
    standards: [
      {
        name: "ISTQB Foundation Level Syllabus",
        body: "International Software Testing Qualifications Board",
        url: "https://www.istqb.org/certifications/certified-tester-foundation-level",
        description: "The global standard for software testing knowledge and certification.",
      },
      {
        name: "WCAG 2.2",
        body: "W3C",
        url: "https://www.w3.org/TR/WCAG22/",
        description:
          "Accessibility standards that define testable success criteria for web content.",
      },
    ],
    certifications: [
      {
        name: "ISTQB Certified Tester Foundation Level",
        issuer: "ISTQB",
        level: "entry",
        url: "https://www.istqb.org/certifications/certified-tester-foundation-level",
      },
      {
        name: "AWS Certified Developer – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-developer-associate/",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Test Strategy & Case Design", skillId: "test-case-design" },
          { skill: "Automated Testing (Vitest, Playwright)", skillId: "testing-fundamentals" },
          { skill: "API Testing", skillId: "api-testing" },
          { skill: "Debugging & Root Cause Analysis", skillId: "debugging" },
          { skill: "CI/CD Integration", skillId: "ci-cd-basics" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Performance & Load Testing", skillId: "performance-testing" },
          { skill: "Security Testing", skillId: "security-testing" },
          { skill: "Test Architecture", skillId: "test-architecture" },
          { skill: "Accessibility Testing", skillId: "accessibility-basics" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Playwright / Cypress", skillId: "testing-fundamentals" },
          { skill: "Postman / Bruno", skillId: "api-testing" },
          { skill: "Docker (test environments)", skillId: "docker-basics" },
        ],
      },
    ],
    dayInTheLife:
      "You start the day reviewing test results from last night's CI run and triaging any new failures. Mid-morning, you write end-to-end tests for a new feature, then pair with a developer to debug a flaky test. After lunch, you update the test strategy document, review PRs for test coverage, and set up a load test for an upcoming launch.",
    salaryRange: { low: 80000, high: 185000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["first-tech-job", "career-switch"],
    prerequisites: [],
    leadsTo: ["sre", "engineering-manager"],
  },

  // ─── 9. Site Reliability Engineer ──────────────────────────────────
  {
    id: "sre",
    slug: "site-reliability-engineer",
    title: "Site Reliability Engineer",
    tagline: "Keep the lights on at internet scale.",
    description:
      "SREs apply software engineering to operations problems. You define SLOs, build automation to maintain reliability, manage incident response, and eliminate toil. When systems go down at 3 AM, you are the one people call — and you build tools so it happens less.",
    icon: "Activity",
    color: "#EC4899",
    levels: {
      junior: {
        required: [
          "linux-fundamentals",
          "networking-basics",
          "shell-scripting",
          "docker-basics",
          "monitoring-observability",
          "git-basics",
          "debugging",
          "http-protocol",
          "cloud-fundamentals",
          "incident-management",
        ],
        valuable: ["python-basics", "ci-cd-basics", "database-administration", "kubernetes-basics"],
      },
      mid: {
        required: [
          "linux-fundamentals",
          "networking-basics",
          "shell-scripting",
          "docker-basics",
          "monitoring-observability",
          "git-basics",
          "debugging",
          "http-protocol",
          "cloud-fundamentals",
          "incident-management",
          "python-basics",
          "ci-cd-basics",
          "kubernetes-basics",
          "slo-sli-design",
          "infrastructure-as-code",
          "load-balancing",
        ],
        valuable: [
          "chaos-engineering",
          "distributed-systems",
          "database-administration",
          "capacity-planning",
          "security-fundamentals",
          "cost-optimization",
        ],
      },
      senior: {
        required: [
          "linux-fundamentals",
          "networking-basics",
          "shell-scripting",
          "docker-basics",
          "monitoring-observability",
          "git-basics",
          "debugging",
          "http-protocol",
          "cloud-fundamentals",
          "incident-management",
          "python-basics",
          "ci-cd-basics",
          "kubernetes-basics",
          "slo-sli-design",
          "infrastructure-as-code",
          "load-balancing",
          "chaos-engineering",
          "distributed-systems",
          "system-design",
          "capacity-planning",
          "security-fundamentals",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "machine-learning-ops",
          "team-leadership",
          "technical-writing",
          "architecture-patterns",
          "cost-optimization",
          "compliance-frameworks",
          "service-mesh",
          "multi-cloud",
          "performance-profiling",
        ],
      },
    },
    portfolio: [
      {
        title: "Monitoring Dashboard",
        tutorialSlug: "monitoring-dashboard",
        skill: "Metrics + Alerts",
      },
      { title: "Load Balancer", tutorialSlug: "load-balancer", skill: "Traffic Distribution" },
      {
        title: "Incident Timeline Tool",
        tutorialSlug: "incident-timeline",
        skill: "Incident Response",
      },
      { title: "Chaos Engineering", tutorialSlug: "chaos-engineering", skill: "Failure Injection" },
      { title: "Log Aggregator", tutorialSlug: "log-aggregator", skill: "Observability" },
      {
        title: "URL Health Checker",
        tutorialSlug: "url-health-checker",
        skill: "Uptime Monitoring",
      },
      { title: "CI/CD Pipeline", tutorialSlug: "ci-cd-pipeline", skill: "Deployment Automation" },
    ],
    standards: [
      {
        name: "Google SRE Book",
        body: "Google",
        url: "https://sre.google/sre-book/table-of-contents/",
        description:
          "The foundational text on Site Reliability Engineering practices and principles.",
      },
      {
        name: "DORA Metrics",
        body: "Google Cloud / DORA",
        url: "https://dora.dev/",
        description:
          "Industry-standard metrics for measuring software delivery and operational performance.",
      },
      {
        name: "OpenTelemetry Specification",
        body: "CNCF",
        url: "https://opentelemetry.io/docs/specs/otel/",
        description: "Vendor-neutral standard for distributed tracing, metrics, and logs.",
      },
    ],
    certifications: [
      {
        name: "Google Professional Cloud DevOps Engineer",
        issuer: "Google Cloud",
        level: "professional",
        url: "https://cloud.google.com/learn/certification/cloud-devops-engineer",
      },
      {
        name: "Certified Kubernetes Administrator (CKA)",
        issuer: "Cloud Native Computing Foundation",
        level: "professional",
        url: "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/",
      },
      {
        name: "AWS Certified SysOps Administrator – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-sysops-admin-associate/",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "Linux & Networking", skillId: "linux-fundamentals" },
          { skill: "Monitoring & Observability", skillId: "monitoring-observability" },
          { skill: "Incident Management", skillId: "incident-management" },
          { skill: "SLOs / SLIs / Error Budgets", skillId: "slo-sli-design" },
          { skill: "Infrastructure as Code", skillId: "infrastructure-as-code" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Distributed Systems", skillId: "distributed-systems" },
          { skill: "Chaos Engineering", skillId: "chaos-engineering" },
          { skill: "Capacity Planning", skillId: "capacity-planning" },
          { skill: "System Design", skillId: "system-design" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Kubernetes", skillId: "kubernetes-basics" },
          { skill: "Prometheus / Grafana / PagerDuty", skillId: "monitoring-observability" },
          { skill: "Terraform", skillId: "infrastructure-as-code" },
          { skill: "Python / Shell Scripting", skillId: "python-basics" },
        ],
      },
    ],
    dayInTheLife:
      "You start by checking the SLO dashboard and reviewing last night's incidents. Mid-morning, you write a postmortem for yesterday's outage and implement automation to prevent recurrence. After lunch, you run a chaos engineering experiment, tune alert thresholds to reduce noise, and mentor a junior engineer on on-call best practices.",
    salaryRange: { low: 110000, high: 260000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "very-high",
    goals: ["reliable-systems"],
    prerequisites: ["backend", "devops"],
    leadsTo: ["solutions-architect", "engineering-manager"],
  },

  // ─── 10. Mobile Engineer ───────────────────────────────────────────
  {
    id: "mobile",
    slug: "mobile-engineer",
    title: "Mobile Engineer",
    tagline: "Build apps people carry in their pockets.",
    description:
      "Mobile engineers create native and cross-platform applications for iOS and Android. You handle gesture interactions, offline storage, push notifications, and platform-specific APIs. Performance and battery efficiency matter more than anywhere else.",
    icon: "Smartphone",
    color: "#6366F1",
    levels: {
      junior: {
        required: [
          "javascript-basics",
          "react-components",
          "responsive-design",
          "git-basics",
          "debugging",
          "state-management",
          "api-integration",
          "mobile-fundamentals",
          "npm-basics",
        ],
        valuable: [
          "typescript-basics",
          "testing-basics",
          "accessibility-basics",
          "offline-storage",
          "push-notifications",
        ],
      },
      mid: {
        required: [
          "javascript-basics",
          "react-components",
          "responsive-design",
          "git-basics",
          "debugging",
          "state-management",
          "api-integration",
          "mobile-fundamentals",
          "npm-basics",
          "typescript-basics",
          "testing-fundamentals",
          "offline-storage",
          "push-notifications",
          "mobile-performance",
          "native-apis",
        ],
        valuable: [
          "ci-cd-basics",
          "accessibility-basics",
          "animation-libraries",
          "app-store-deployment",
          "analytics-integration",
          "deep-linking",
        ],
      },
      senior: {
        required: [
          "javascript-basics",
          "react-components",
          "responsive-design",
          "git-basics",
          "debugging",
          "state-management",
          "api-integration",
          "mobile-fundamentals",
          "npm-basics",
          "typescript-basics",
          "testing-fundamentals",
          "offline-storage",
          "push-notifications",
          "mobile-performance",
          "native-apis",
          "ci-cd-basics",
          "app-store-deployment",
          "system-design",
          "code-review",
          "mentoring",
        ],
        valuable: [
          "accessibility-basics",
          "architecture-patterns",
          "team-leadership",
          "technical-writing",
          "security-fundamentals",
          "analytics-integration",
          "performance-profiling",
          "deep-linking",
          "monetization-patterns",
          "cross-platform-native",
        ],
      },
    },
    portfolio: [
      {
        title: "PWA with Push Notifications",
        tutorialSlug: "pwa-push",
        skill: "Service Workers + Push",
      },
      { title: "Kanban Mobile App", tutorialSlug: "kanban-mobile", skill: "Gesture + Offline" },
      { title: "Finance Tracker", tutorialSlug: "finance-tracker", skill: "IndexedDB + Charts" },
      {
        title: "Job Application Tracker",
        tutorialSlug: "job-tracker",
        skill: "Drag-and-Drop + Persistence",
      },
      { title: "Chat Application", tutorialSlug: "chat-app", skill: "Real-Time + Presence" },
      { title: "Browser Game", tutorialSlug: "browser-game", skill: "Canvas + Touch Events" },
    ],
    standards: [
      {
        name: "Apple Human Interface Guidelines",
        body: "Apple",
        url: "https://developer.apple.com/design/human-interface-guidelines/",
        description: "Design principles and patterns for building apps on Apple platforms.",
      },
      {
        name: "Material Design 3",
        body: "Google",
        url: "https://m3.material.io/",
        description:
          "Google's design system for building high-quality Android and cross-platform apps.",
      },
      {
        name: "WCAG 2.2 (Mobile)",
        body: "W3C",
        url: "https://www.w3.org/TR/mobile-accessibility-mapping/",
        description: "Accessibility guidance applied to mobile web and native applications.",
      },
    ],
    certifications: [
      {
        name: "Google Associate Android Developer",
        issuer: "Google",
        level: "entry",
        url: "https://developers.google.com/certification/associate-android-developer",
      },
      {
        name: "Meta React Native Specialization",
        issuer: "Meta / Coursera",
        level: "entry",
        url: "https://www.coursera.org/specializations/meta-react-native",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "React Native / Expo", skillId: "react-components" },
          { skill: "Mobile UI Patterns", skillId: "mobile-fundamentals" },
          { skill: "State Management", skillId: "state-management" },
          { skill: "Offline Storage", skillId: "offline-storage" },
          { skill: "API Integration", skillId: "api-integration" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Native Module Bridging", skillId: "native-apis" },
          { skill: "Mobile Performance", skillId: "mobile-performance" },
          { skill: "Push Notifications", skillId: "push-notifications" },
          { skill: "App Store Deployment", skillId: "app-store-deployment" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Git", skillId: "git-basics" },
          { skill: "Xcode / Android Studio", skillId: "mobile-fundamentals" },
          { skill: "Testing (Detox, Maestro)", skillId: "testing-fundamentals" },
          { skill: "CI/CD (Fastlane, EAS)", skillId: "ci-cd-basics" },
        ],
      },
    ],
    dayInTheLife:
      "You start by fixing a gesture recognition bug reported on Android. Mid-morning, you implement a new offline-first feature with optimistic UI updates. After lunch, you profile the app to find a memory leak, test push notifications across both platforms, and submit a beta build to TestFlight.",
    salaryRange: { low: 90000, high: 210000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["first-tech-job", "build-startup"],
    prerequisites: ["frontend"],
    leadsTo: ["full-stack", "engineering-manager"],
  },

  // ─── 11. Engineering Manager ───────────────────────────────────────
  {
    id: "engineering-manager",
    slug: "engineering-manager",
    title: "Engineering Manager",
    tagline: "Multiply the impact of your team.",
    description:
      "Engineering managers lead teams of engineers — setting technical direction, unblocking people, and translating between business and engineering. You still need to understand the code, but your primary output is a high-performing team that ships reliably.",
    icon: "Users",
    color: "#84CC16",
    levels: {
      junior: {
        required: [
          "code-review",
          "mentoring",
          "agile-practices",
          "technical-communication",
          "git-basics",
          "system-design",
          "debugging",
          "project-planning",
          "one-on-ones",
          "hiring-basics",
        ],
        valuable: [
          "testing-fundamentals",
          "ci-cd-basics",
          "architecture-patterns",
          "conflict-resolution",
        ],
      },
      mid: {
        required: [
          "code-review",
          "mentoring",
          "agile-practices",
          "technical-communication",
          "git-basics",
          "system-design",
          "debugging",
          "project-planning",
          "one-on-ones",
          "hiring-basics",
          "performance-management",
          "stakeholder-management",
          "technical-strategy",
          "team-building",
          "incident-management",
          "architecture-patterns",
        ],
        valuable: [
          "budgeting",
          "okr-planning",
          "cross-team-collaboration",
          "developer-experience",
          "compliance-frameworks",
          "remote-leadership",
          "diversity-inclusion",
        ],
      },
      senior: {
        required: [
          "code-review",
          "mentoring",
          "agile-practices",
          "technical-communication",
          "git-basics",
          "system-design",
          "debugging",
          "project-planning",
          "one-on-ones",
          "hiring-basics",
          "performance-management",
          "stakeholder-management",
          "technical-strategy",
          "team-building",
          "incident-management",
          "architecture-patterns",
          "budgeting",
          "okr-planning",
          "cross-team-collaboration",
          "organizational-design",
          "executive-communication",
          "change-management",
          "tech-debt-management",
        ],
        valuable: [
          "m-and-a-technical-diligence",
          "vendor-management",
          "compliance-frameworks",
          "developer-experience",
          "remote-leadership",
          "succession-planning",
          "public-speaking",
          "board-communication",
          "diversity-inclusion",
          "cost-optimization",
        ],
      },
    },
    portfolio: [
      { title: "Sprint Tracker", tutorialSlug: "sprint-tracker", skill: "Agile + Velocity" },
      {
        title: "Feature Flag Service",
        tutorialSlug: "feature-flags",
        skill: "Controlled Rollouts",
      },
      { title: "CI/CD Pipeline", tutorialSlug: "ci-cd-pipeline", skill: "Team Workflow" },
      { title: "Test Suite", tutorialSlug: "test-suite", skill: "Quality Standards" },
      { title: "Incident Timeline", tutorialSlug: "incident-timeline", skill: "Postmortems" },
      {
        title: "Documentation Site",
        tutorialSlug: "documentation-site",
        skill: "Knowledge Sharing",
      },
    ],
    standards: [
      {
        name: "DORA Metrics",
        body: "Google Cloud / DORA",
        url: "https://dora.dev/",
        description:
          "Measuring team delivery performance: deploy frequency, lead time, failure rate, recovery.",
      },
      {
        name: "SPACE Framework",
        body: "Microsoft Research",
        url: "https://queue.acm.org/detail.cfm?id=3454124",
        description:
          "Framework for understanding and measuring developer productivity across five dimensions.",
      },
    ],
    certifications: [
      {
        name: "Certified ScrumMaster (CSM)",
        issuer: "Scrum Alliance",
        level: "entry",
        url: "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster",
      },
      {
        name: "PMI Agile Certified Practitioner (PMI-ACP)",
        issuer: "Project Management Institute",
        level: "professional",
        url: "https://www.pmi.org/certifications/agile-acp",
      },
      {
        name: "AWS Certified Solutions Architect – Associate",
        issuer: "Amazon Web Services",
        level: "professional",
        url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "People Management", skillId: "one-on-ones" },
          { skill: "Technical Strategy", skillId: "technical-strategy" },
          { skill: "Project Planning", skillId: "project-planning" },
          { skill: "Hiring & Team Building", skillId: "hiring-basics" },
          { skill: "Stakeholder Communication", skillId: "stakeholder-management" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Organizational Design", skillId: "organizational-design" },
          { skill: "Executive Communication", skillId: "executive-communication" },
          { skill: "Change Management", skillId: "change-management" },
          { skill: "Tech Debt Strategy", skillId: "tech-debt-management" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Jira / Linear / GitHub Projects", skillId: "project-planning" },
          { skill: "Git (for code review)", skillId: "git-basics" },
          { skill: "DORA Dashboard", skillId: "monitoring-observability" },
          { skill: "1:1 / Feedback Tools", skillId: "one-on-ones" },
        ],
      },
    ],
    dayInTheLife:
      "Your morning starts with a 1:1 with a direct report discussing their career growth. Then you join a planning meeting to scope the next sprint. After lunch, you review an architecture proposal, align with product on priorities, and unblock a team that's stuck on a cross-team dependency. Most of your calendar is conversations, not code.",
    salaryRange: { low: 130000, high: 280000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["lead-teams", "mid-to-senior"],
    prerequisites: ["full-stack"],
    leadsTo: ["solutions-architect"],
  },

  // ─── 12. Solutions Architect ───────────────────────────────────────
  {
    id: "solutions-architect",
    slug: "solutions-architect",
    title: "Solutions Architect",
    tagline: "Design systems that outlast the team that builds them.",
    description:
      "Solutions architects design the high-level structure of complex software systems. You evaluate trade-offs, choose technologies, define integration patterns, and ensure the architecture supports business goals. You bridge the gap between engineering depth and business strategy.",
    icon: "Compass",
    color: "#A855F7",
    levels: {
      junior: {
        required: [
          "system-design",
          "rest-api-design",
          "database-design",
          "cloud-fundamentals",
          "git-basics",
          "networking-basics",
          "architecture-patterns",
          "technical-communication",
          "debugging",
          "security-fundamentals",
        ],
        valuable: [
          "docker-basics",
          "ci-cd-basics",
          "monitoring-observability",
          "cost-optimization",
        ],
      },
      mid: {
        required: [
          "system-design",
          "rest-api-design",
          "database-design",
          "cloud-fundamentals",
          "git-basics",
          "networking-basics",
          "architecture-patterns",
          "technical-communication",
          "debugging",
          "security-fundamentals",
          "distributed-systems",
          "event-driven-architecture",
          "infrastructure-as-code",
          "microservices",
          "stakeholder-management",
          "cost-optimization",
        ],
        valuable: [
          "kubernetes-basics",
          "data-modeling",
          "compliance-frameworks",
          "machine-learning-ops",
          "technical-writing",
          "vendor-evaluation",
          "migration-strategy",
        ],
      },
      senior: {
        required: [
          "system-design",
          "rest-api-design",
          "database-design",
          "cloud-fundamentals",
          "git-basics",
          "networking-basics",
          "architecture-patterns",
          "technical-communication",
          "debugging",
          "security-fundamentals",
          "distributed-systems",
          "event-driven-architecture",
          "infrastructure-as-code",
          "microservices",
          "stakeholder-management",
          "cost-optimization",
          "multi-cloud",
          "domain-driven-design",
          "technical-strategy",
          "executive-communication",
          "vendor-evaluation",
          "migration-strategy",
          "compliance-frameworks",
          "mentoring",
        ],
        valuable: [
          "team-leadership",
          "organizational-design",
          "machine-learning-ops",
          "data-lake-architecture",
          "edge-computing",
          "real-time-analytics",
          "public-speaking",
          "board-communication",
          "change-management",
        ],
      },
    },
    portfolio: [
      {
        title: "URL Shortener (System Design)",
        tutorialSlug: "url-shortener",
        skill: "Scalable Architecture",
      },
      { title: "API Gateway", tutorialSlug: "api-gateway", skill: "Routing + Middleware" },
      {
        title: "Event Sourcing System",
        tutorialSlug: "event-sourcing",
        skill: "Event-Driven Design",
      },
      {
        title: "Microservices SaaS Starter",
        tutorialSlug: "saas-starter",
        skill: "Multi-Service Architecture",
      },
      {
        title: "Capstone Platform",
        tutorialSlug: "capstone-platform",
        skill: "Full System Design",
      },
      { title: "Key-Value Store", tutorialSlug: "key-value-store", skill: "Storage Engine Design" },
    ],
    standards: [
      {
        name: "AWS Well-Architected Framework",
        body: "Amazon Web Services",
        url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
        description:
          "Best practices for designing reliable, secure, efficient cloud architectures.",
      },
      {
        name: "TOGAF",
        body: "The Open Group",
        url: "https://www.opengroup.org/togaf",
        description:
          "Enterprise architecture framework used globally for designing IT architectures.",
      },
      {
        name: "ISO/IEC 25010 Software Quality",
        body: "ISO",
        url: "https://www.iso.org/standard/35733.html",
        description:
          "Defines software quality characteristics: reliability, security, maintainability, etc.",
      },
    ],
    certifications: [
      {
        name: "AWS Certified Solutions Architect – Professional",
        issuer: "Amazon Web Services",
        level: "expert",
        url: "https://aws.amazon.com/certification/certified-solutions-architect-professional/",
      },
      {
        name: "Google Professional Cloud Architect",
        issuer: "Google Cloud",
        level: "professional",
        url: "https://cloud.google.com/learn/certification/cloud-architect",
      },
      {
        name: "TOGAF 10 Certified",
        issuer: "The Open Group",
        level: "professional",
        url: "https://www.opengroup.org/certifications/togaf",
      },
    ],
    skills: [
      {
        category: "Core",
        items: [
          { skill: "System Design", skillId: "system-design" },
          { skill: "Architecture Patterns", skillId: "architecture-patterns" },
          { skill: "Cloud Architecture", skillId: "cloud-fundamentals" },
          { skill: "API Design", skillId: "rest-api-design" },
          { skill: "Security Architecture", skillId: "security-fundamentals" },
        ],
      },
      {
        category: "Advanced",
        items: [
          { skill: "Distributed Systems", skillId: "distributed-systems" },
          { skill: "Domain-Driven Design", skillId: "domain-driven-design" },
          { skill: "Event-Driven Architecture", skillId: "event-driven-architecture" },
          { skill: "Migration Strategy", skillId: "migration-strategy" },
        ],
      },
      {
        category: "Tooling",
        items: [
          { skill: "Diagramming (Mermaid, Excalidraw)", skillId: "technical-communication" },
          { skill: "Infrastructure as Code", skillId: "infrastructure-as-code" },
          { skill: "Cost Calculators (AWS/GCP)", skillId: "cost-optimization" },
          { skill: "ADR Templates", skillId: "technical-writing" },
        ],
      },
    ],
    dayInTheLife:
      "Your morning starts with a design review for a new service boundary. You draw architecture diagrams, evaluate whether to use an event bus or direct API calls, and document the decision in an ADR. After lunch, you meet with stakeholders to explain trade-offs, review a vendor proposal, and mentor a senior engineer on system design thinking.",
    salaryRange: { low: 140000, high: 300000, currency: "USD", source: "levels.fyi", year: 2026 },
    demandLevel: "high",
    goals: ["mid-to-senior", "deep-understanding"],
    prerequisites: ["full-stack", "backend"],
    leadsTo: [],
  },
];

/** Look up a role by its unique ID. */
export function getRole(id: string): Role | undefined {
  return ROLES.find((r) => r.id === id);
}

/** Look up a role by its URL-friendly slug. */
export function getRoleBySlug(slug: string): Role | undefined {
  return ROLES.find((r) => r.slug === slug);
}

/** Return all roles that map to a given goal ID. */
export function getRolesForGoal(goalId: string): Role[] {
  return ROLES.filter((r) => r.goals.includes(goalId));
}
