import type { Skill } from "@/types/career-track";

export const SKILLS: Skill[] = [
  // ─── Phase 0-1 Foundations (15 skills) ─────────────────────────────
  {
    id: "file-system-nav",
    name: "File System Navigation",
    description:
      "Navigate directories, manage files, and understand file system structure from the terminal.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["cli-tool"],
    prerequisites: [],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SF/Operating Systems" }],
    bloomLevel: "apply",
  },
  {
    id: "command-line",
    name: "Command Line Proficiency",
    description: "Use shell commands, pipes, redirects, and scripting to automate tasks.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["cli-tool", "cli-dashboard"],
    prerequisites: ["file-system-nav"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SF/Operating Systems" }],
    bloomLevel: "apply",
  },
  {
    id: "git-version-control",
    name: "Git & Version Control",
    description: "Track changes, branch, merge, and collaborate using Git workflows.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["git-visualizer", "git-hooks-toolkit"],
    prerequisites: ["command-line"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "devops", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SE/Software Configuration Management" }],
    bloomLevel: "apply",
  },
  {
    id: "variables-types",
    name: "Variables & Types",
    description:
      "Declare variables, understand primitive and reference types, and use type annotations.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["cli-tool"],
    prerequisites: [],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "PL/Type Systems" }],
    bloomLevel: "understand",
  },
  {
    id: "control-flow",
    name: "Control Flow",
    description: "Use conditionals, loops, and pattern matching to direct program execution.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["variables-types"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SDF/Algorithms and Design" }],
    bloomLevel: "apply",
  },
  {
    id: "functions-scope",
    name: "Functions & Scope",
    description: "Define functions, understand closures, and manage variable scope and hoisting.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["cli-tool", "algorithm-visualizer"],
    prerequisites: ["variables-types", "control-flow"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "PL/Functional Programming" }],
    bloomLevel: "apply",
  },
  {
    id: "data-structures-basic",
    name: "Basic Data Structures",
    description: "Work with arrays, objects, maps, and sets to organize and access data.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "finance-tracker"],
    prerequisites: ["variables-types", "control-flow"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "debugging-errors",
    name: "Debugging & Error Handling",
    description:
      "Read error messages, use debuggers, and write code that handles failures gracefully.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["cli-tool"],
    prerequisites: ["variables-types", "functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "qa-testing", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SE/Software Verification and Validation" }],
    bloomLevel: "analyze",
  },
  {
    id: "async-programming",
    name: "Asynchronous Programming",
    description: "Handle promises, async/await, and callbacks to manage non-blocking operations.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["chat-app", "rest-api"],
    prerequisites: ["functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "PL/Event-Driven and Reactive Programming" }],
    bloomLevel: "apply",
  },
  {
    id: "dom-basics",
    name: "DOM Basics",
    description:
      "Access and modify HTML elements programmatically using the Document Object Model.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["first-website", "browser-game"],
    prerequisites: ["variables-types", "html-css-fundamentals"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "html-css-fundamentals",
    name: "HTML & CSS Fundamentals",
    description: "Structure web pages with semantic HTML and style them with CSS.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["first-website", "portfolio-site"],
    prerequisites: [],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "mobile", importance: "valuable" },
    ],
    standards: [{ body: "W3C", reference: "HTML Living Standard" }],
    bloomLevel: "apply",
  },
  {
    id: "testing-basics",
    name: "Testing Basics",
    description: "Write unit tests, understand test runners, and practice test-driven development.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["test-suite", "api-testing-framework"],
    prerequisites: ["functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "qa-testing", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "frontend", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SE/Software Verification and Validation" }],
    bloomLevel: "apply",
  },
  {
    id: "package-management",
    name: "Package Management",
    description: "Install, update, and manage project dependencies using npm or similar tools.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["npm-package", "cli-tool"],
    prerequisites: ["command-line"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "code-reading",
    name: "Code Reading",
    description:
      "Read and comprehend unfamiliar codebases to understand logic, intent, and patterns.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["diff-tool"],
    prerequisites: ["variables-types", "functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "problem-solving",
    name: "Problem Solving",
    description:
      "Break down complex problems, design solutions, and translate requirements into code.",
    category: "foundations",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["control-flow", "functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SDF/Algorithms and Design" }],
    bloomLevel: "analyze",
  },

  // ─── Phase 2 Web (20 skills) ───────────────────────────────────────
  {
    id: "semantic-html",
    name: "Semantic HTML",
    description: "Use meaningful HTML elements to improve accessibility, SEO, and code clarity.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["first-website", "accessible-components"],
    prerequisites: ["html-css-fundamentals"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [{ body: "W3C", reference: "WCAG 2.2" }],
    bloomLevel: "apply",
  },
  {
    id: "css-layout-flexbox",
    name: "CSS Layout: Flexbox",
    description:
      "Use flexbox to create one-dimensional layouts that adapt to content and screen size.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["portfolio-site", "design-system"],
    prerequisites: ["html-css-fundamentals"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "css-layout-grid",
    name: "CSS Layout: Grid",
    description:
      "Use CSS Grid for two-dimensional layouts with precise control over rows and columns.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["portfolio-site", "data-dashboard"],
    prerequisites: ["html-css-fundamentals"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "responsive-design",
    name: "Responsive Design",
    description:
      "Build layouts that work across all screen sizes using media queries and fluid techniques.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["portfolio-site", "kanban-mobile"],
    prerequisites: ["css-layout-flexbox", "css-layout-grid"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "mobile", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "css-variables-theming",
    name: "CSS Variables & Theming",
    description:
      "Use custom properties to build theme systems with dark mode and user preferences.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["design-system", "css-framework"],
    prerequisites: ["html-css-fundamentals"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "dom-manipulation",
    name: "DOM Manipulation",
    description: "Create, modify, and remove DOM elements dynamically in response to user actions.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["browser-game", "markdown-editor"],
    prerequisites: ["dom-basics"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "browser-events",
    name: "Browser Events",
    description:
      "Handle clicks, keyboard input, scrolling, and custom events with proper delegation.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["browser-game", "form-wizard"],
    prerequisites: ["dom-basics"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "fetch-http",
    name: "Fetch & HTTP",
    description:
      "Make HTTP requests with fetch, handle responses, and work with REST APIs from the client.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "chat-app"],
    prerequisites: ["async-programming"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "react-components",
    name: "React Components",
    description:
      "Build reusable UI components with props, composition, and the component lifecycle.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["react-dashboard", "accessible-components"],
    prerequisites: ["html-css-fundamentals", "functions-scope"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "mobile", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "react-hooks",
    name: "React Hooks",
    description: "Use useState, useEffect, useRef, and custom hooks to manage component logic.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["react-dashboard", "finance-tracker"],
    prerequisites: ["react-components"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "react-state-mgmt",
    name: "React State Management",
    description:
      "Manage complex state across components using context, reducers, and external stores.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["task-board", "ecommerce-checkout"],
    prerequisites: ["react-hooks"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "react-effects",
    name: "React Effects & Data Fetching",
    description:
      "Synchronize components with external systems using effects and data fetching patterns.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["react-dashboard", "chat-app"],
    prerequisites: ["react-hooks", "async-programming"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "react-context",
    name: "React Context",
    description:
      "Share state across the component tree without prop drilling using context providers.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["ecommerce-checkout", "design-system"],
    prerequisites: ["react-components", "react-hooks"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "nextjs-routing",
    name: "Next.js Routing",
    description:
      "Build multi-page applications with file-based routing, dynamic segments, and layouts.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["blog-engine", "documentation-site"],
    prerequisites: ["react-components"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "nextjs-server-components",
    name: "Next.js Server Components",
    description: "Render components on the server for better performance and direct data access.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["blog-engine", "cms-headless"],
    prerequisites: ["nextjs-routing", "react-components"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "understand",
  },
  {
    id: "nextjs-data-fetching",
    name: "Next.js Data Fetching",
    description:
      "Fetch data in server components, use caching strategies, and handle loading states.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["blog-engine", "data-dashboard"],
    prerequisites: ["nextjs-server-components", "fetch-http"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "web-accessibility",
    name: "Web Accessibility",
    description:
      "Build inclusive interfaces with ARIA attributes, keyboard navigation, and screen reader support.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["accessible-components", "design-system"],
    prerequisites: ["semantic-html", "react-components"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "qa-testing", importance: "valuable" },
    ],
    standards: [
      { body: "W3C", reference: "WCAG 2.2" },
      { body: "Section 508", reference: "ICT Accessibility" },
    ],
    bloomLevel: "apply",
  },
  {
    id: "browser-devtools",
    name: "Browser DevTools",
    description:
      "Inspect elements, debug JavaScript, profile performance, and analyze network requests.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["react-dashboard"],
    prerequisites: ["dom-basics"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "qa-testing", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "form-handling",
    name: "Form Handling",
    description: "Build forms with validation, error states, and accessible input patterns.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["form-wizard", "job-tracker"],
    prerequisites: ["react-hooks", "browser-events"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "web-performance",
    name: "Web Performance",
    description: "Optimize load times, reduce bundle size, and improve Core Web Vitals scores.",
    category: "web",
    lessonIds: [],
    tutorialSlugs: ["image-optimizer", "static-site-gen"],
    prerequisites: ["react-components", "browser-devtools"],
    roles: [
      { roleId: "frontend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [{ body: "Google", reference: "Core Web Vitals" }],
    bloomLevel: "analyze",
  },

  // ─── Phase 3 CS (15 skills) ────────────────────────────────────────
  {
    id: "big-o-analysis",
    name: "Big-O Analysis",
    description: "Analyze time and space complexity to evaluate algorithm efficiency.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["functions-scope", "data-structures-basic"],
    roles: [
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Basic Analysis" }],
    bloomLevel: "analyze",
  },
  {
    id: "arrays-strings-algo",
    name: "Array & String Algorithms",
    description:
      "Solve problems involving iteration, searching, and manipulation of arrays and strings.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "regex-tester"],
    prerequisites: ["data-structures-basic", "big-o-analysis"],
    roles: [
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "linked-lists",
    name: "Linked Lists",
    description: "Implement and traverse singly and doubly linked lists for dynamic data storage.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["data-structures-basic"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "stacks-queues",
    name: "Stacks & Queues",
    description:
      "Use LIFO and FIFO structures for parsing, scheduling, and breadth-first traversal.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "task-queue"],
    prerequisites: ["data-structures-basic"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "hash-maps",
    name: "Hash Maps",
    description: "Use hash-based structures for constant-time lookups and frequency counting.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["key-value-store", "algorithm-visualizer"],
    prerequisites: ["data-structures-basic"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "trees-traversal",
    name: "Trees & Traversal",
    description: "Build and traverse binary trees, BSTs, and n-ary trees using DFS and BFS.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "dependency-graph"],
    prerequisites: ["stacks-queues", "recursion"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Fundamental Data Structures" }],
    bloomLevel: "apply",
  },
  {
    id: "graph-algorithms",
    name: "Graph Algorithms",
    description:
      "Model relationships with graphs and solve problems using BFS, DFS, and shortest-path algorithms.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["dependency-graph", "algorithm-visualizer"],
    prerequisites: ["trees-traversal", "hash-maps"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Algorithmic Strategies" }],
    bloomLevel: "analyze",
  },
  {
    id: "sorting-algorithms",
    name: "Sorting Algorithms",
    description:
      "Implement and compare sorting strategies from bubble sort to merge sort and quicksort.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["arrays-strings-algo", "big-o-analysis"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Sorting and Searching" }],
    bloomLevel: "apply",
  },
  {
    id: "binary-search",
    name: "Binary Search",
    description:
      "Apply binary search to sorted data and adapt it for search-space reduction problems.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "search-engine"],
    prerequisites: ["arrays-strings-algo", "big-o-analysis"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Sorting and Searching" }],
    bloomLevel: "apply",
  },
  {
    id: "recursion",
    name: "Recursion",
    description: "Solve problems by breaking them into self-similar sub-problems with base cases.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "static-site-gen"],
    prerequisites: ["functions-scope"],
    roles: [
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Algorithmic Strategies" }],
    bloomLevel: "apply",
  },
  {
    id: "dynamic-programming-skill",
    name: "Dynamic Programming",
    description:
      "Optimize recursive solutions using memoization and tabulation for overlapping sub-problems.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["recursion", "big-o-analysis"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Algorithmic Strategies" }],
    bloomLevel: "analyze",
  },
  {
    id: "greedy-algorithms",
    name: "Greedy Algorithms",
    description: "Make locally optimal choices at each step to find globally optimal solutions.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["big-o-analysis", "sorting-algorithms"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Algorithmic Strategies" }],
    bloomLevel: "apply",
  },
  {
    id: "two-pointer-technique",
    name: "Two-Pointer Technique",
    description:
      "Use converging or parallel pointers to solve array and string problems efficiently.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["arrays-strings-algo"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "bonus" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    description:
      "Maintain a dynamic window over sequential data to solve subarray and substring problems.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer", "streaming-processor"],
    prerequisites: ["arrays-strings-algo"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "backtracking",
    name: "Backtracking",
    description:
      "Explore all possible solutions by building candidates incrementally and pruning invalid paths.",
    category: "cs",
    lessonIds: [],
    tutorialSlugs: ["algorithm-visualizer"],
    prerequisites: ["recursion", "trees-traversal"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "AL/Algorithmic Strategies" }],
    bloomLevel: "apply",
  },

  // ─── Phase 4 Backend (20 skills) ───────────────────────────────────
  {
    id: "nodejs-runtime",
    name: "Node.js Runtime",
    description:
      "Understand the event loop, module system, and built-in APIs for server-side JavaScript.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["http-server", "cli-tool"],
    prerequisites: ["async-programming", "command-line"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "devops", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "understand",
  },
  {
    id: "express-middleware",
    name: "Express & Middleware",
    description:
      "Build HTTP servers with Express, chain middleware for logging, auth, and error handling.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "http-server"],
    prerequisites: ["nodejs-runtime", "fetch-http"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "rest-api-design",
    name: "REST API Design",
    description:
      "Design resource-oriented APIs with proper HTTP methods, status codes, and versioning.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "graphql-api"],
    prerequisites: ["express-middleware", "fetch-http"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [{ body: "IETF", reference: "RFC 7231 HTTP Semantics" }],
    bloomLevel: "apply",
  },
  {
    id: "sql-queries",
    name: "SQL Queries",
    description: "Write SELECT, JOIN, GROUP BY, and subqueries to retrieve and aggregate data.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "analytics-dashboard"],
    prerequisites: ["data-structures-basic"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [{ body: "ISO", reference: "ISO/IEC 9075 SQL Standard" }],
    bloomLevel: "apply",
  },
  {
    id: "schema-design",
    name: "Database Schema Design",
    description:
      "Design normalized schemas with proper relationships, constraints, and data types.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "inventory-system"],
    prerequisites: ["sql-queries"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "data", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "database-indexing",
    name: "Database Indexing",
    description: "Create and optimize indexes to speed up queries while managing write overhead.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["search-engine", "analytics-dashboard"],
    prerequisites: ["sql-queries", "schema-design"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "transactions-acid",
    name: "Transactions & ACID",
    description:
      "Use transactions to ensure atomicity, consistency, isolation, and durability of data operations.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["ecommerce-checkout", "finance-tracker"],
    prerequisites: ["sql-queries"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "data", importance: "core" },
    ],
    standards: [],
    bloomLevel: "understand",
  },
  {
    id: "database-migrations",
    name: "Database Migrations",
    description: "Evolve database schemas safely over time with versioned migration scripts.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["migration-tool", "rest-api"],
    prerequisites: ["schema-design"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "devops", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "jwt-authentication",
    name: "JWT Authentication",
    description:
      "Implement stateless authentication with JSON Web Tokens for API and session management.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["auth-system", "oauth-provider"],
    prerequisites: ["rest-api-design"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "security", importance: "core" },
    ],
    standards: [{ body: "IETF", reference: "RFC 7519 JWT" }],
    bloomLevel: "apply",
  },
  {
    id: "password-hashing",
    name: "Password Hashing",
    description:
      "Securely store passwords using bcrypt or argon2 with proper salting and iteration counts.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["auth-system", "password-manager"],
    prerequisites: [],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "security", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [{ body: "OWASP", reference: "Password Storage Cheat Sheet" }],
    bloomLevel: "apply",
  },
  {
    id: "docker-containers",
    name: "Docker Containers",
    description: "Package applications into containers with Dockerfiles for consistent deployment.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["docker-deploy", "kubernetes-deployer"],
    prerequisites: ["command-line", "nodejs-runtime"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "docker-compose",
    name: "Docker Compose",
    description:
      "Orchestrate multi-container applications with Docker Compose for local development.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["docker-deploy", "saas-starter"],
    prerequisites: ["docker-containers"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "valuable" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "ci-cd-pipelines",
    name: "CI/CD Pipelines",
    description:
      "Automate testing, building, and deploying code with continuous integration and delivery.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["ci-cd-pipeline", "docker-deploy"],
    prerequisites: ["git-version-control", "testing-basics"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "environment-config",
    name: "Environment Configuration",
    description:
      "Manage configuration across environments with env variables, secrets, and config files.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["secrets-manager", "docker-deploy"],
    prerequisites: ["command-line"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
    ],
    standards: [{ body: "12factor.net", reference: "III. Config" }],
    bloomLevel: "apply",
  },
  {
    id: "error-handling-backend",
    name: "Backend Error Handling",
    description:
      "Build robust error handling with structured errors, retries, and graceful degradation.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rest-api", "webhook-relay"],
    prerequisites: ["debugging-errors", "express-middleware"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "full-stack", importance: "core" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "logging-monitoring",
    name: "Logging & Monitoring",
    description:
      "Implement structured logging and monitoring to track application health and debug issues.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["log-aggregator", "monitoring-dashboard"],
    prerequisites: ["error-handling-backend"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "api-documentation",
    name: "API Documentation",
    description: "Document APIs with OpenAPI/Swagger specs, examples, and interactive explorers.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["documentation-site", "rest-api"],
    prerequisites: ["rest-api-design"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [{ body: "OpenAPI Initiative", reference: "OpenAPI 3.1 Specification" }],
    bloomLevel: "apply",
  },
  {
    id: "rate-limiting",
    name: "Rate Limiting",
    description:
      "Protect APIs from abuse with token buckets, sliding windows, and distributed rate limiting.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["rate-limiter", "api-gateway"],
    prerequisites: ["rest-api-design"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "security", importance: "core" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "caching-strategies",
    name: "Caching Strategies",
    description: "Use in-memory, CDN, and database caching to reduce latency and server load.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["key-value-store", "api-gateway"],
    prerequisites: ["rest-api-design"],
    roles: [
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "deployment",
    name: "Deployment",
    description:
      "Deploy applications to production with zero-downtime strategies, rollbacks, and health checks.",
    category: "backend",
    lessonIds: [],
    tutorialSlugs: ["docker-deploy", "kubernetes-deployer"],
    prerequisites: ["docker-containers", "ci-cd-pipelines"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "backend", importance: "valuable" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },

  // ─── Phase 5-6 Advanced (15 skills) ────────────────────────────────
  {
    id: "tcp-ip-networking",
    name: "TCP/IP Networking",
    description:
      "Understand network layers, TCP handshakes, ports, and packet flow for debugging connectivity.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["http-server", "load-balancer"],
    prerequisites: ["nodejs-runtime"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "valuable" },
      { roleId: "security", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "NC/Networked Applications" }],
    bloomLevel: "understand",
  },
  {
    id: "dns-http-deep",
    name: "DNS & HTTP Deep Dive",
    description:
      "Understand DNS resolution, HTTP/2, TLS handshakes, and request lifecycle in depth.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["http-server", "url-health-checker"],
    prerequisites: ["tcp-ip-networking", "fetch-http"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "valuable" },
    ],
    standards: [{ body: "IETF", reference: "RFC 9110 HTTP Semantics" }],
    bloomLevel: "understand",
  },
  {
    id: "operating-system-concepts",
    name: "Operating System Concepts",
    description:
      "Understand processes, memory management, file systems, and scheduling at the OS level.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["cli-dashboard"],
    prerequisites: ["command-line"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "valuable" },
      { roleId: "backend", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SF/Operating Systems" }],
    bloomLevel: "understand",
  },
  {
    id: "concurrency-threads",
    name: "Concurrency & Threads",
    description:
      "Manage concurrent execution with threads, locks, and message passing to avoid race conditions.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["streaming-processor", "task-queue"],
    prerequisites: ["operating-system-concepts", "async-programming"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "SF/Parallelism" }],
    bloomLevel: "understand",
  },
  {
    id: "database-internals",
    name: "Database Internals",
    description: "Understand B-trees, write-ahead logs, query planners, and storage engines.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["key-value-store", "orm-from-scratch"],
    prerequisites: ["sql-queries", "database-indexing"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "data", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "understand",
  },
  {
    id: "distributed-systems-basics",
    name: "Distributed Systems Basics",
    description:
      "Understand CAP theorem, consensus, replication, and failure modes in distributed architectures.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["event-sourcing", "load-balancer"],
    prerequisites: ["tcp-ip-networking", "caching-strategies"],
    roles: [
      { roleId: "backend", importance: "valuable" },
      { roleId: "sre", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [{ body: "ACM CS2023", reference: "PD/Distributed Systems" }],
    bloomLevel: "understand",
  },
  {
    id: "cloud-infrastructure",
    name: "Cloud Infrastructure",
    description:
      "Provision and manage cloud resources including compute, storage, and networking services.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["kubernetes-deployer", "docker-deploy"],
    prerequisites: ["docker-containers", "deployment"],
    roles: [
      { roleId: "devops", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "observability-metrics",
    name: "Observability & Metrics",
    description:
      "Instrument applications with metrics, traces, and logs for full-stack observability.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["monitoring-dashboard", "log-aggregator"],
    prerequisites: ["logging-monitoring"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "backend", importance: "valuable" },
    ],
    standards: [{ body: "CNCF", reference: "OpenTelemetry Specification" }],
    bloomLevel: "apply",
  },
  {
    id: "prompt-engineering-skill",
    name: "Prompt Engineering",
    description:
      "Design effective prompts for LLMs using techniques like few-shot, chain-of-thought, and system prompts.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["ai-code-reviewer", "rag-chatbot"],
    prerequisites: [],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "rag-pipelines",
    name: "RAG Pipelines",
    description:
      "Build retrieval-augmented generation systems that ground LLM responses in domain data.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["rag-chatbot", "embeddings-search"],
    prerequisites: ["prompt-engineering-skill", "rest-api-design"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "backend", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "ai-agents",
    name: "AI Agents",
    description:
      "Build autonomous agents that use tools, plan multi-step tasks, and interact with external systems.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["ai-agent", "chat-bot-framework"],
    prerequisites: ["prompt-engineering-skill", "async-programming"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "llm-evaluation",
    name: "LLM Evaluation",
    description: "Evaluate LLM outputs with metrics, human feedback, and automated benchmarks.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["a-b-testing", "ai-code-reviewer"],
    prerequisites: ["prompt-engineering-skill"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "fine-tuning-skill",
    name: "Fine-Tuning",
    description:
      "Customize pre-trained models on domain-specific data to improve task performance.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["fine-tuning"],
    prerequisites: ["llm-evaluation", "rag-pipelines"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "data", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "mcp-development",
    name: "MCP Development",
    description:
      "Build Model Context Protocol servers that expose tools and resources to AI assistants.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["mcp-server-tutorial"],
    prerequisites: ["ai-agents", "rest-api-design"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
  {
    id: "responsible-ai",
    name: "Responsible AI",
    description:
      "Apply ethical frameworks, detect bias, and build safeguards into AI-powered applications.",
    category: "ai-ml",
    lessonIds: [],
    tutorialSlugs: ["ai-agent", "ai-code-reviewer"],
    prerequisites: ["prompt-engineering-skill"],
    roles: [
      { roleId: "ai-ml", importance: "core" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [{ body: "NIST", reference: "AI Risk Management Framework" }],
    bloomLevel: "evaluate",
  },

  // ─── Phase 7-9 Specialist (15 skills) ──────────────────────────────
  {
    id: "compiler-design",
    name: "Compiler Design",
    description:
      "Build lexers, parsers, and code generators to understand how programming languages work.",
    category: "systems",
    lessonIds: [],
    tutorialSlugs: ["tiny-compiler", "type-checker"],
    prerequisites: ["recursion", "trees-traversal"],
    roles: [
      { roleId: "backend", importance: "bonus" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [{ body: "ACM CS2023", reference: "PL/Language Translation and Execution" }],
    bloomLevel: "create",
  },
  {
    id: "security-threat-modeling",
    name: "Security Threat Modeling",
    description:
      "Identify attack surfaces, model threats, and prioritize security mitigations systematically.",
    category: "security",
    lessonIds: [],
    tutorialSlugs: ["rbac-system", "password-manager"],
    prerequisites: ["jwt-authentication", "rest-api-design"],
    roles: [
      { roleId: "security", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
      { roleId: "sre", importance: "valuable" },
    ],
    standards: [{ body: "OWASP", reference: "Threat Modeling" }],
    bloomLevel: "analyze",
  },
  {
    id: "cryptography-basics",
    name: "Cryptography Basics",
    description: "Understand hashing, symmetric and asymmetric encryption, and digital signatures.",
    category: "security",
    lessonIds: [],
    tutorialSlugs: ["password-manager", "auth-system"],
    prerequisites: ["password-hashing"],
    roles: [
      { roleId: "security", importance: "core" },
      { roleId: "backend", importance: "valuable" },
    ],
    standards: [{ body: "NIST", reference: "SP 800-175B Cryptographic Standards" }],
    bloomLevel: "understand",
  },
  {
    id: "system-design-skill",
    name: "System Design",
    description:
      "Design scalable architectures by combining databases, caches, queues, and services.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["saas-starter", "capstone-platform"],
    prerequisites: ["distributed-systems-basics", "caching-strategies", "schema-design"],
    roles: [
      { roleId: "solutions-architect", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "sre", importance: "core" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
  {
    id: "architecture-patterns",
    name: "Architecture Patterns",
    description:
      "Apply patterns like microservices, event sourcing, CQRS, and hexagonal architecture.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["event-sourcing", "plugin-system"],
    prerequisites: ["system-design-skill"],
    roles: [
      { roleId: "solutions-architect", importance: "core" },
      { roleId: "backend", importance: "valuable" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "analyze",
  },
  {
    id: "code-review-skill",
    name: "Code Review",
    description:
      "Give and receive constructive code review feedback focused on correctness, clarity, and maintainability.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["ai-code-reviewer", "git-hooks-toolkit"],
    prerequisites: ["code-reading", "git-version-control"],
    roles: [
      { roleId: "full-stack", importance: "core" },
      { roleId: "backend", importance: "core" },
      { roleId: "frontend", importance: "core" },
      { roleId: "engineering-manager", importance: "core" },
    ],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "technical-writing",
    name: "Technical Writing",
    description:
      "Write clear documentation, RFCs, ADRs, and tutorials that communicate complex ideas simply.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["documentation-site", "npm-package"],
    prerequisites: ["code-reading"],
    roles: [
      { roleId: "solutions-architect", importance: "core" },
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "full-stack", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
  {
    id: "team-leadership",
    name: "Team Leadership",
    description:
      "Lead engineering teams with clear communication, delegation, and technical mentorship.",
    category: "leadership",
    lessonIds: [],
    tutorialSlugs: ["sprint-tracker"],
    prerequisites: ["code-review-skill", "technical-writing"],
    roles: [
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
  {
    id: "hiring-interviewing",
    name: "Hiring & Interviewing",
    description:
      "Design fair interview processes, evaluate candidates, and build diverse engineering teams.",
    category: "leadership",
    lessonIds: [],
    tutorialSlugs: ["sprint-tracker"],
    prerequisites: ["team-leadership"],
    roles: [{ roleId: "engineering-manager", importance: "core" }],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "product-strategy",
    name: "Product Strategy",
    description:
      "Align engineering work with business goals through roadmapping, prioritization, and user research.",
    category: "leadership",
    lessonIds: [],
    tutorialSlugs: ["sprint-tracker", "a-b-testing"],
    prerequisites: ["team-leadership"],
    roles: [
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "incident-management",
    name: "Incident Management",
    description:
      "Respond to production incidents with structured triage, communication, and blameless postmortems.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["incident-timeline", "monitoring-dashboard"],
    prerequisites: ["logging-monitoring", "observability-metrics"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "devops", importance: "core" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "apply",
  },
  {
    id: "capacity-planning",
    name: "Capacity Planning",
    description:
      "Forecast resource needs, plan for traffic growth, and optimize infrastructure costs.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["load-balancer", "monitoring-dashboard"],
    prerequisites: ["cloud-infrastructure", "observability-metrics"],
    roles: [
      { roleId: "sre", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
      { roleId: "engineering-manager", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "vendor-evaluation",
    name: "Vendor Evaluation",
    description:
      "Assess third-party tools and services on cost, reliability, lock-in risk, and team fit.",
    category: "leadership",
    lessonIds: [],
    tutorialSlugs: ["saas-starter"],
    prerequisites: ["system-design-skill"],
    roles: [
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "solutions-architect", importance: "core" },
    ],
    standards: [],
    bloomLevel: "evaluate",
  },
  {
    id: "stakeholder-communication",
    name: "Stakeholder Communication",
    description:
      "Translate technical decisions into business context for non-technical stakeholders.",
    category: "leadership",
    lessonIds: [],
    tutorialSlugs: ["sprint-tracker"],
    prerequisites: ["technical-writing"],
    roles: [
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
  {
    id: "engineering-process",
    name: "Engineering Process",
    description:
      "Design and improve development workflows including sprint planning, retrospectives, and delivery metrics.",
    category: "professional",
    lessonIds: [],
    tutorialSlugs: ["sprint-tracker", "feature-flags"],
    prerequisites: ["team-leadership"],
    roles: [
      { roleId: "engineering-manager", importance: "core" },
      { roleId: "solutions-architect", importance: "valuable" },
    ],
    standards: [],
    bloomLevel: "create",
  },
];

/** Look up a single skill by its unique ID. */
export function getSkill(id: string): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}

/** Return all skills that list the given role ID in their roles array. */
export function getSkillsForRole(roleId: string): Skill[] {
  return SKILLS.filter((s) => s.roles.some((r) => r.roleId === roleId));
}

/** Return all skills matching a given category string. */
export function getSkillsByCategory(category: string): Skill[] {
  return SKILLS.filter((s) => s.category === category);
}
