/**
 * Education standards alignment reference.
 * Maps DURA phases and modules to K-12, college, and professional standards.
 *
 * Phases 0-3 (K-12 + intro-college coverage): CSTA, AP CSP, AP CSA, ISTE.
 * Phases 4-9 (professional + advanced practice): module-level SFIA work-role
 * summaries, plus OWASP (security modules), IEEE 7000-series (AI/ethics),
 * and NIST NICE (cybersecurity workforce). ACM CS2023, SWEBOK v4, and SFIA
 * level numbers per lesson live on lesson frontmatter; the module-level
 * fields here surface codes that don't fit per-lesson but apply to the
 * whole module's scope of work.
 */

export interface StandardsAlignment {
  phaseId: string;
  moduleId: string;
  csta: string[];
  apCSP: string[];
  apCSA: string[];
  iste: string[];
  /** Module-level SFIA work-role + level summary, plain-language. */
  sfia?: string;
  /** OWASP Top 10 categories addressed by this module (security-relevant only). */
  owasp?: string[];
  /** IEEE 7000-series ethics standards relevant to this module (AI / ethics only). */
  ieee7000?: string[];
  /** NIST NICE Cybersecurity Workforce work-role codes (cyber/devops only). */
  nice?: string[];
  /**
   * Industry / professional standards this module covers.
   * Format: "<body>:<code>" or "<body>:<code>:<title>" for readability.
   * Examples: "IEC:61508", "ISO:10218-1:2025", "MISRA-C:2023", "ISA:95"
   */
  professionalStandards?: string[];
}

// CSTA Standard Codes Reference:
// Level 1 (K-5): 1A-CS-01 through 1B-IC-21
// Level 2 (6-8): 2-CS-01 through 2-IC-23
// Level 3A (9-10): 3A-CS-01 through 3A-IC-30
// Level 3B (11-12): 3B-CS-01 through 3B-IC-28

// AP CSP Big Ideas: 1-Creative Development, 2-Data, 3-Algorithms, 4-Programming, 5-Systems, 6-Internet, 7-Impact
// AP CSA Units: 1-Primitive Types, 2-Using Objects, 3-Boolean, 4-Iteration, 5-Writing Classes, 6-Array, 7-ArrayList, 8-2D Array, 9-Inheritance, 10-Recursion

export const PHASE_STANDARDS: StandardsAlignment[] = [
  // Phase 0: Digital Literacy → CSTA Level 2 + AP CSP Big Ideas 5,6
  {
    phaseId: "0",
    moduleId: "0-1",
    csta: ["2-CS-01", "2-CS-02", "2-CS-03"],
    apCSP: ["CSP-5.1", "CSP-5.2"],
    apCSA: [],
    iste: ["1.1", "1.2"],
  },
  {
    phaseId: "0",
    moduleId: "0-2",
    csta: ["2-NI-04", "2-NI-05", "2-NI-06"],
    apCSP: ["CSP-6.1", "CSP-6.2", "CSP-6.3"],
    apCSA: [],
    iste: ["1.2"],
  },
  {
    phaseId: "0",
    moduleId: "0-3",
    csta: ["2-CS-01", "2-CS-02"],
    apCSP: ["CSP-5.1"],
    apCSA: [],
    iste: ["1.1"],
  },
  {
    phaseId: "0",
    moduleId: "0-4",
    csta: ["2-IC-20", "2-IC-21", "2-IC-23"],
    apCSP: ["CSP-7.1", "CSP-7.2"],
    apCSA: [],
    iste: ["1.2"],
  },

  // Phase 1: Programming Fundamentals → CSTA Level 2/3A + AP CSP 3,4 + AP CSA 1-5
  {
    phaseId: "1",
    moduleId: "1-1",
    csta: ["2-AP-10", "2-AP-11", "3A-AP-14"],
    apCSP: ["CSP-4.1", "CSP-2.1"],
    apCSA: ["CSA-Unit1", "CSA-Unit2"],
    iste: ["1.5"],
  },
  {
    phaseId: "1",
    moduleId: "1-2",
    csta: ["2-AP-12", "3A-AP-15"],
    apCSP: ["CSP-3.1", "CSP-4.1"],
    apCSA: ["CSA-Unit3", "CSA-Unit4"],
    iste: ["1.5"],
  },
  {
    phaseId: "1",
    moduleId: "1-3",
    csta: ["2-AP-13", "2-AP-14", "3A-AP-17"],
    apCSP: ["CSP-3.1", "CSP-4.1"],
    apCSA: ["CSA-Unit5"],
    iste: ["1.5"],
  },
  {
    phaseId: "1",
    moduleId: "1-4",
    csta: ["2-DA-07", "2-DA-08", "3A-DA-09"],
    apCSP: ["CSP-2.1", "CSP-2.2"],
    apCSA: ["CSA-Unit6", "CSA-Unit7", "CSA-Unit8"],
    iste: ["1.5"],
  },
  {
    phaseId: "1",
    moduleId: "1-5",
    csta: ["2-AP-17", "3A-AP-21"],
    apCSP: ["CSP-4.1"],
    apCSA: [],
    iste: ["1.5", "1.6"],
  },
  {
    phaseId: "1",
    moduleId: "1-6",
    csta: ["2-AP-15", "2-AP-18", "2-AP-19", "3A-AP-22", "3A-AP-23"],
    apCSP: ["CSP-1.1", "CSP-1.2", "CSP-1.3"],
    apCSA: [],
    iste: ["1.5", "1.6"],
  },

  // Phase 2: Web Development → CSTA 3A/3B + AP CSP 1,4
  {
    phaseId: "2",
    moduleId: "2-1",
    csta: ["3A-AP-14", "3A-IC-24"],
    apCSP: ["CSP-1.1"],
    apCSA: [],
    iste: ["1.6"],
  },
  {
    phaseId: "2",
    moduleId: "2-2",
    csta: ["3A-AP-14"],
    apCSP: ["CSP-1.1"],
    apCSA: [],
    iste: ["1.6"],
  },
  {
    phaseId: "2",
    moduleId: "2-3",
    csta: ["3A-AP-15", "3A-AP-16", "3A-AP-18"],
    apCSP: ["CSP-4.1"],
    apCSA: [],
    iste: ["1.5", "1.6"],
  },
  {
    phaseId: "2",
    moduleId: "2-4",
    csta: ["3B-AP-14", "3B-AP-15", "3B-AP-16"],
    apCSP: ["CSP-1.2", "CSP-4.1"],
    apCSA: [],
    iste: ["1.5"],
  },
  {
    phaseId: "2",
    moduleId: "2-5",
    csta: ["3B-AP-16", "3B-AP-21"],
    apCSP: ["CSP-1.2", "CSP-1.3"],
    apCSA: [],
    iste: ["1.5", "1.6"],
  },

  // Phase 3: CS Fundamentals → CSTA 3A/3B + AP CSA 6-10
  {
    phaseId: "3",
    moduleId: "3-1",
    csta: ["3A-AP-13", "3B-AP-11"],
    apCSP: ["CSP-3.1"],
    apCSA: [],
    iste: ["1.5"],
  },
  {
    phaseId: "3",
    moduleId: "3-2",
    csta: ["3A-DA-09", "3A-DA-10", "3B-AP-12"],
    apCSP: ["CSP-2.2", "CSP-3.1"],
    apCSA: ["CSA-Unit6", "CSA-Unit8"],
    iste: ["1.5"],
  },
  {
    phaseId: "3",
    moduleId: "3-3",
    csta: ["3B-AP-12", "3B-AP-13"],
    apCSP: ["CSP-3.1"],
    apCSA: ["CSA-Unit7"],
    iste: ["1.5"],
  },
  {
    phaseId: "3",
    moduleId: "3-4",
    csta: ["3B-AP-12", "3B-AP-13"],
    apCSP: ["CSP-3.1"],
    apCSA: ["CSA-Unit10"],
    iste: ["1.5"],
  },
  {
    phaseId: "3",
    moduleId: "3-5",
    csta: ["3B-AP-11", "3B-AP-12", "3B-AP-13"],
    apCSP: ["CSP-3.1"],
    apCSA: ["CSA-Unit10"],
    iste: ["1.5"],
  },

  // Phase 4: Backend Engineering → SWEBOK + SFIA L3-4 + OWASP (API security) + NICE (DevOps)
  {
    phaseId: "4",
    moduleId: "4-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Programming / software development",
  },
  {
    phaseId: "4",
    moduleId: "4-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Programming / software development",
    owasp: ["A01:2021 Broken Access Control", "A07:2021 Identification & Auth Failures"],
  },
  {
    phaseId: "4",
    moduleId: "4-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Database design (DBAD)",
  },
  {
    phaseId: "4",
    moduleId: "4-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Systems integration / sustainability",
    nice: ["SP-DEV-001 Software Developer"],
  },
  {
    phaseId: "4",
    moduleId: "4-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Release & deployment management (RELM)",
    nice: ["OM-NET-001 Network Operations Specialist"],
  },

  // Phase 5: Systems Engineering → SFIA L4-5 + NICE (network/incident response)
  {
    phaseId: "5",
    moduleId: "5-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4–5 — Solution architecture (ARCH)",
  },
  {
    phaseId: "5",
    moduleId: "5-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Network design (NTDS)",
    nice: ["OM-NET-001 Network Operations Specialist"],
  },
  {
    phaseId: "5",
    moduleId: "5-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Performance management (PDSG)",
  },
  {
    phaseId: "5",
    moduleId: "5-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Service level management (SLMO)",
    nice: ["PR-CIR-001 Cyber Incident Response"],
  },

  // Phase 6: AI/ML Engineering → SFIA MLNG + IEEE 7000-series ethics
  {
    phaseId: "6",
    moduleId: "6-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Machine learning (MLNG)",
  },
  {
    phaseId: "6",
    moduleId: "6-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3–4 — Machine learning (MLNG)",
    ieee7000: ["IEEE 7000-2021 (Ethical System Design)"],
  },
  {
    phaseId: "6",
    moduleId: "6-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Machine learning (MLNG)",
    ieee7000: ["IEEE 7000-2021 (Ethical System Design)", "IEEE 7001-2021 (Transparency)"],
  },
  {
    phaseId: "6",
    moduleId: "6-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Machine learning (MLNG)",
    ieee7000: ["IEEE 7000-2021 (Ethical System Design)"],
  },
  {
    phaseId: "6",
    moduleId: "6-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Data engineering (DENG)",
    ieee7000: ["IEEE 7001-2021 (Transparency of Autonomous Systems)"],
  },
  {
    phaseId: "6",
    moduleId: "6-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4–5 — Solution architecture (ARCH)",
    ieee7000: ["IEEE 7007-2021 (Ontological standards for ethical AI)"],
  },
  {
    phaseId: "6",
    moduleId: "6-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4–5 — Programming / agent engineering (PROG, EMRG)",
    ieee7000: [
      "IEEE 7000-2021 (Model process for addressing ethical concerns during system design)",
      "IEEE 7001-2021 (Transparency of autonomous systems)",
    ],
    owasp: ["LLM01 Prompt Injection", "LLM02 Insecure Output Handling", "LLM08 Excessive Agency"],
  },

  // Phase 7: Advanced Systems → SFIA L5 + NICE (security) + OWASP
  {
    phaseId: "7",
    moduleId: "7-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Programming / specialism (PROG)",
  },
  {
    phaseId: "7",
    moduleId: "7-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems development management (DLMG)",
  },
  {
    phaseId: "7",
    moduleId: "7-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4–5 — Information security (SCTY)",
    owasp: ["A02:2021 Cryptographic Failures", "A04:2021 Insecure Design"],
    nice: ["SP-DEV-002 Secure Software Assessor", "OM-CYB-001 Cyber Defense Analyst"],
  },
  {
    phaseId: "7",
    moduleId: "7-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5–6 — Solution architecture (ARCH)",
  },

  // Phase 8: Professional Practice → SFIA L3-4 + SWEBOK + IEEE 7000 ethics
  {
    phaseId: "8",
    moduleId: "8-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Methods & tools (METL)",
  },
  {
    phaseId: "8",
    moduleId: "8-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3–4 — Testing (TEST)",
  },
  {
    phaseId: "8",
    moduleId: "8-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Quality management (QUMG)",
  },
  {
    phaseId: "8",
    moduleId: "8-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3–4 — Technical writing (TECH)",
  },
  {
    phaseId: "8",
    moduleId: "8-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Professional development (PDSV)",
    ieee7000: ["IEEE 7000-2021 (Ethical System Design)", "IEEE 7010-2020 (Wellbeing Metrics)"],
  },

  // Phase 9: CTO Track → SFIA L5-7 strategy + management work roles
  {
    phaseId: "9",
    moduleId: "9-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — People management / mentoring (PEMT)",
  },
  {
    phaseId: "9",
    moduleId: "9-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6–7 — Enterprise & solution architecture (ARCH)",
  },
  {
    phaseId: "9",
    moduleId: "9-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5–6 — Organisational design (RESC)",
  },
  {
    phaseId: "9",
    moduleId: "9-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5–6 — IT strategy & planning (ITSP)",
  },
  {
    phaseId: "9",
    moduleId: "9-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Financial management for IT (FMIT)",
  },
  {
    phaseId: "9",
    moduleId: "9-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — IT strategy & planning (ITSP)",
  },
  {
    phaseId: "9",
    moduleId: "9-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — IT strategy & planning (ITSP)",
  },
  {
    phaseId: "9",
    moduleId: "9-8",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 7 — IT strategy & planning (ITSP)",
  },

  // ── Phase E: Embedded / Firmware (→ Phase 10 after rename) ────────────────
  {
    phaseId: "e",
    moduleId: "e-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Software development (PROG): embedded toolchain setup",
    professionalStandards: ["IEC:61508-3:Functional Safety of Software", "MISRA-C:2023"],
  },
  {
    phaseId: "e",
    moduleId: "e-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Software development (PROG): bare-metal C",
    professionalStandards: ["MISRA-C:2023", "ARM:Cortex-M Architecture Reference Manual"],
  },
  {
    phaseId: "e",
    moduleId: "e-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): interrupts and DMA",
    professionalStandards: ["IEC:61508-3:Functional Safety", "MISRA-C:2023"],
  },
  {
    phaseId: "e",
    moduleId: "e-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): RTOS and scheduling",
    professionalStandards: ["IEC:61508-3", "MISRA-C:2023", "ISO:26262-6:Software (Automotive)"],
  },
  {
    phaseId: "e",
    moduleId: "e-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): peripheral buses",
    professionalStandards: ["IEC:61508-3", "MISRA-C:2023"],
  },
  {
    phaseId: "e",
    moduleId: "e-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): Rust on embedded",
    professionalStandards: ["IEC:61508-3", "ISO:26262-6"],
  },
  {
    phaseId: "e",
    moduleId: "e-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): MISRA-C compliance and static analysis",
    professionalStandards: [
      "MISRA-C:2023",
      "IEC:61508-3:SIL analysis",
      "RTCA:DO-178C:Software Considerations in Airborne Systems",
    ],
  },
  {
    phaseId: "e",
    moduleId: "e-8",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): real-time sensor pipeline",
    professionalStandards: ["IEC:61508-3", "ISO:26262-4:System design", "MISRA-C:2023"],
  },

  // ── Phase H: Hardware Engineering (→ Phase 11 after rename) ───────────────
  {
    phaseId: "h",
    moduleId: "h-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Electronic engineering (ELEN): digital logic and circuits",
    professionalStandards: ["IEEE:1284", "IEC:60068:Environmental Testing"],
  },
  {
    phaseId: "h",
    moduleId: "h-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Electronic engineering (ELEN): PCB design",
    professionalStandards: ["IPC:2221:PCB Design Standard", "IPC:7711", "IEC:60068"],
  },
  {
    phaseId: "h",
    moduleId: "h-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Electronic engineering (ELEN): FPGA design",
    professionalStandards: ["IEEE:1076:VHDL", "IEEE:1800:SystemVerilog"],
  },
  {
    phaseId: "h",
    moduleId: "h-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Electronic engineering (ELEN): JTAG and debug interfaces",
    professionalStandards: ["IEEE:1149.1:JTAG", "IEEE:1149.7:Compact JTAG"],
  },
  {
    phaseId: "h",
    moduleId: "h-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Electronic engineering (ELEN): power electronics",
    professionalStandards: ["IEC:60068", "IEC:61000-4:EMC Testing"],
  },
  {
    phaseId: "h",
    moduleId: "h-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Electronic engineering (ELEN): hardware-software integration",
    professionalStandards: ["IEC:61508", "IPC:2221", "IEEE:1149.1"],
  },

  // ── Phase Q: Quantitative / HFT Systems (→ Phase 12 after rename) ─────────
  {
    phaseId: "q",
    moduleId: "q-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Data analysis (DTAN): financial mathematics",
    professionalStandards: [
      "FIX:Protocol:Financial Information eXchange",
      "ISO:15022:Securities Messaging",
    ],
  },
  {
    phaseId: "q",
    moduleId: "q-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): low-latency systems",
    professionalStandards: ["FIX:Protocol", "IEEE:802.3:Ethernet"],
  },
  {
    phaseId: "q",
    moduleId: "q-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): market microstructure",
    professionalStandards: ["FIX:Protocol", "FINRA:Rule 5310:Best Execution"],
  },
  {
    phaseId: "q",
    moduleId: "q-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Data analysis (DTAN): statistical arbitrage",
    professionalStandards: ["ISO:15022", "SEC:Rule 15c3-5:Market Access Rule"],
  },
  {
    phaseId: "q",
    moduleId: "q-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): risk systems",
    professionalStandards: [
      "Basel:III:Capital Requirements",
      "FINRA:Rule 4370:Business Continuity",
    ],
  },
  {
    phaseId: "q",
    moduleId: "q-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — Data analysis (DTAN): execution algorithms (TWAP/VWAP/IS)",
    professionalStandards: ["FIX:Protocol", "MiFID:II:Best Execution RTS 27/28"],
  },
  {
    phaseId: "q",
    moduleId: "q-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — Software development (PROG): co-location and kernel bypass",
    professionalStandards: ["IEEE:802.3", "Linux:DPDK", "SEC:Rule 15c3-5"],
  },
  {
    phaseId: "q",
    moduleId: "q-8",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 7 — Software development (PROG): production HFT architecture",
    professionalStandards: [
      "FIX:Protocol",
      "MiFID:II",
      "SEC:Rule 15c3-5",
      "ISO:27001:Information Security",
    ],
  },

  // ── Phase R: Robotics Software Engineering (→ Phase 13 after rename) ──────
  {
    phaseId: "r",
    moduleId: "r-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Software development (PROG): ROS fundamentals",
    professionalStandards: ["ISO:10218-1:2025:Robot Safety", "ROS:2:Communication Standard"],
  },
  {
    phaseId: "r",
    moduleId: "r-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): robot kinematics",
    professionalStandards: ["ISO:10218-1:2025", "ISO:9283:Manipulator Performance"],
  },
  {
    phaseId: "r",
    moduleId: "r-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): sensor fusion and perception",
    professionalStandards: ["ISO:10218-1:2025", "IEC:62443-3-3:System Security Requirements"],
  },
  {
    phaseId: "r",
    moduleId: "r-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Software development (PROG): motion planning and navigation",
    professionalStandards: ["ISO:10218-1:2025", "ISO:9283"],
  },
  {
    phaseId: "r",
    moduleId: "r-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): control systems",
    professionalStandards: ["ISO:10218-1:2025", "IEC:61508-3:Functional Safety", "ISO:9283"],
  },
  {
    phaseId: "r",
    moduleId: "r-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): robot cybersecurity",
    professionalStandards: ["IEC:62443-3-3", "IEC:62443-4-2:Component Security", "ISO:27001"],
    owasp: ["A05:2021 Security Misconfiguration", "A01:2021 Broken Access Control"],
  },
  {
    phaseId: "r",
    moduleId: "r-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Software development (PROG): human-robot interaction",
    professionalStandards: ["ISO:10218-2:2025:Robot Integration", "ISO:15066:Collaborative Robots"],
  },
  {
    phaseId: "r",
    moduleId: "r-8",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — Software development (PROG): production robotics architecture",
    professionalStandards: ["ISO:10218-1:2025", "ISO:15066", "IEC:62443-3-3", "IEC:61508-3"],
  },

  // ── Phase M: Manufacturing Systems Engineering (→ Phase 14 after rename) ──
  {
    phaseId: "m",
    moduleId: "m-1",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 3 — Systems design (SYSP): manufacturing systems overview",
    professionalStandards: [
      "ISA:95:Enterprise-Control System Integration",
      "ISO:9001:Quality Management",
    ],
  },
  {
    phaseId: "m",
    moduleId: "m-2",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Systems design (SYSP): ISA-88 batch control",
    professionalStandards: ["ISA:88:Batch Control", "IEC:61512:Batch Control"],
  },
  {
    phaseId: "m",
    moduleId: "m-3",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Systems design (SYSP): MES and SCADA",
    professionalStandards: ["ISA:95", "ISA:88", "IEC:62541:OPC UA"],
  },
  {
    phaseId: "m",
    moduleId: "m-4",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 4 — Systems design (SYSP): industrial networks and protocols",
    professionalStandards: ["IEC:62541:OPC UA", "IEC:61158:Fieldbus", "IEEE:802.3"],
  },
  {
    phaseId: "m",
    moduleId: "m-5",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems design (SYSP): quality management systems",
    professionalStandards: [
      "ISO:9001:Quality Management",
      "IATF:16949:Automotive Quality",
      "ISO:19011:Auditing Management Systems",
    ],
  },
  {
    phaseId: "m",
    moduleId: "m-6",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems design (SYSP): IATF core tools (APQP, FMEA, SPC, MSA, PPAP)",
    professionalStandards: [
      "IATF:16949",
      "AIAG:APQP",
      "AIAG:FMEA",
      "AIAG:SPC",
      "AIAG:MSA",
      "AIAG:PPAP",
    ],
  },
  {
    phaseId: "m",
    moduleId: "m-7",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems design (SYSP): process safety (functional safety for manufacturing)",
    professionalStandards: [
      "IEC:61511:Process Industry Safety",
      "ISA:84:Safety Instrumented Systems",
      "IEC:61508",
    ],
  },
  {
    phaseId: "m",
    moduleId: "m-8",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems design (SYSP): OT/ICS cybersecurity",
    professionalStandards: [
      "IEC:62443-3-3:System Security Requirements",
      "IEC:62443-4-2:Component Security",
      "NIST:SP 800-82:Guide to ICS Security",
    ],
    owasp: ["A05:2021 Security Misconfiguration", "A06:2021 Vulnerable and Outdated Components"],
    nice: ["SP-TRD-001:Technology R&D", "OV-MGT-001:Program/Project Management"],
  },
  {
    phaseId: "m",
    moduleId: "m-9",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 5 — Systems design (SYSP): digital twins and simulation",
    professionalStandards: ["ISO:23247:Digital Twin for Manufacturing", "OPC:UA", "ISA:95"],
  },
  {
    phaseId: "m",
    moduleId: "m-10",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — Systems design (SYSP): supply chain systems and ERP integration",
    professionalStandards: [
      "ISA:95",
      "ISO:28000:Supply Chain Security",
      "GS1:Standards:Barcodes and RFID",
    ],
  },
  {
    phaseId: "m",
    moduleId: "m-11",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 6 — Systems design (SYSP): Industry 4.0 and IIoT",
    professionalStandards: ["IEC:62541:OPC UA", "ISO:23247", "IEEE:2413:IoT Architecture"],
  },
  {
    phaseId: "m",
    moduleId: "m-12",
    csta: [],
    apCSP: [],
    apCSA: [],
    iste: [],
    sfia: "Level 7 — Systems design (SYSP): manufacturing enterprise architecture",
    professionalStandards: [
      "ISA:95",
      "ISA:88",
      "IEC:62443-3-3",
      "ISO:9001",
      "IATF:16949",
      "IEC:62541:OPC UA",
    ],
  },
];

/** Look up the standards alignment for a specific module. */
export function getStandardsForModule(
  phaseId: string,
  moduleId: string
): StandardsAlignment | undefined {
  return PHASE_STANDARDS.find((s) => s.phaseId === phaseId && s.moduleId === moduleId);
}

/** Find all modules that cover a given AP CSP or AP CSA topic. */
export function getModulesByAPTopic(topic: string): StandardsAlignment[] {
  return PHASE_STANDARDS.filter((s) => s.apCSP.includes(topic) || s.apCSA.includes(topic));
}

/** Find all modules that cover a given CSTA standard code. */
export function getModulesByCSTAStandard(code: string): StandardsAlignment[] {
  return PHASE_STANDARDS.filter((s) => s.csta.includes(code));
}
