[env:disco_f407vg]
platform = ststm32@19.6.0
board = disco_f407vg
framework = stm32cube
platform_packages =
  platformio/framework-stm32cubef4@1.28.3
  platformio/toolchain-gccarmnoneeabi@1.70201.0
extra_scripts = post:freertos_build.py
build_flags = -Iinclude -mfpu=fpv4-sp-d16 -mfloat-abi=softfp
monitor_speed = 115200
